mapbox/mapbox-maps-android

.github/pull_request_template.md, README.md
This PR updates the CLA agreement text and adds the badge to the README.md
=> [CLA] Updates CLA agreement text; adds badge

app/src/androidTest/java/com/mapbox/maps/testapp/annotation/UpdateAnnotationTest.kt
This pr add an instrumentation test which will update the position of annotation while changing styles to verify no crash happens during this process.
=> [Annotation plugin] Add instrumentation test for annotation update

app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentAnimationActivity.kt, app/src/main/res/layout/activity_location_component_amimation.xml, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/Evaluators.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimator.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimatorManager.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckPulsingAnimator.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/animators/EvaluatorsTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimatorManagerTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckBearingAnimatorTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckPositionAnimatorTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckPulsingAnimatorTest.kt
`<changelog>[location-component] Add tests for animators.</changelog>`
`<changelog>[location-component] Use custom puck with bearing in animation example.</changelog>`
`<changelog>[location-component] Fix activating location component several times.</changelog>`
- Add animator tests for Location Component.
- Use custom puck with bearing in animation example.
- Fix activating location component several times.
=> [location-component] Add tests for animators

module-telemetry/build.gradle.kts, module-telemetry/src/test/java/com/mapbox/maps/module/telemetry/MapEventFactoryTest.kt
This PR fixes the null values we have been seeing and adds a test so it doesn't regress again. 
cc @sbma44
=> [telemetry] correct versioning in telemetry BuildConfig

plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
Resolves #63 
`<changelog>[camera-animation] Fix using camera animation extension functions with multiple MapView's</changelog>`
Fix using camera animation extension functions with multiple MapView's
=> [camera-animation] Fix using camera animation extension functions

plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/utils/BitmapUtils.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LayerSourceProviderTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImplTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationLayerWrapperTest.kt
Fixes: #68 
This PR adds unit tests for the location component plugin, it also fixes the crash when location plugin puck setting changes during the plugin is  disabled and enabled.
=> [location-component] Add tests to improve code coverage.

.circleci/config.yml, scripts/ci-circleci-start-pipeline.py
This PR adds the CI to trigger internal validation of the generated code.
=> [ci] Add CI validation for the generated code.

plugin-attribution/src/main/java/com/mapbox/maps/plugin/attribution/generated/AttributionAttributeParser.kt, plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/generated/CompassAttributeParser.kt, plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesAttributeParser.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentAttributeParser.kt, plugin-logo/src/main/java/com/mapbox/maps/plugin/logo/generated/LogoAttributeParser.kt, plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/generated/ScaleBarAttributeParser.kt
This PR makes the xml attribute parsers internal, hide them from the public interface.
=> [config] Make xml attribute parsers internal.

DEVELOPING.md
This pr update the download link for android sdk and remove the redundant spaces.
=> [Doc] Update the download link for sdk

app/src/main/java/com/mapbox/maps/testapp/examples/InsetMapActivity.kt, app/src/main/res/layout/activity_inset_map.xml
`<changelog>[examples] Fix InsetMapActivity example</changelog>`
=> [examples] Fix InsetMapActivity example

CHANGELOG.md
=> [docs] update changelog for v10.0.0-beta.13

plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-location/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
Update README files to latest release v10.0.0-beta.13
=> [docs] update README files to latest release v10.0.0-beta.13

app/src/main/java/com/mapbox/maps/testapp/examples/AnimateMapCameraActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/CameraPredefinedAnimatorsActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/LowLevelCameraAnimatorActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/MapOverlayActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/MovingIconWithTrailingLineActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/MultiDisplayActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/SecondaryDisplayActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/SpaceStationLocationActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/TextureViewAnimateActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/WithinExpressionActivity.kt, app/src/main/res/values/interpolators.xml, plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt, plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsListenersTest.kt, plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt, plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt, plugin-compass/src/test/java/com/mapbox/maps/plugin/compass/CompassViewPluginTest.kt, plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt, plugin-location/src/main/java/com/mapbox/maps/plugin/location/LocationCameraAnimatorCoordinator.kt, sdk-base/src/main/java/com/mapbox/maps/dsl/CameraOptionsKtx.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorOptions.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/animation/MapAnimationOptions.kt, sdk/src/androidTest/java/com/mapbox/maps/CameraAnimationsPluginTest.kt
This PR adds kotlin dsl builder for CameraOptions.
This PR also makes the MapAnimationOptions and CameraAnimatorOptions use standard builder pattern to improve Java usability.
=> [ktx] Add kotlin dsl builder for CameraOptions and java builders for CameraAnimatorOptions and MapAnimationOptions.

buildSrc/src/main/kotlin/Project.kt
Cleanup of dependency file by removing obsolete dependencies.
=> [deps] cleanup dependency file

.circleci/config.yml, .gitattributes
This PR adds `union` merge strategy for test app's description and manifest xmls.
What it does:
`Run 3-way file level merge for text files, but take lines from both versions, instead of leaving conflict markers. This tends to leave the added lines in the resulting file in random order and the user should verify the result. `
This PR also increases the `no_output_timeout` to 30m for `verify-docs` CI task.
=> [build] Add merge strategies for test app's description and manifest xml.

app/src/main/java/com/mapbox/maps/testapp/examples/DSLStylingActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/RuntimeStylingActivity.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/image/ImageExtensionImpl.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/Layer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/Light.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/Source.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/Terrain.kt, sdk-base/src/main/java/com/mapbox/maps/extension/style/StyleContract.kt, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt, sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt, sdk/src/test/java/com/mapbox/maps/plugin/MapDelegateProviderTest.kt
This PR renames reference to style plugin and converting them to style extension.
=> [style-extension] Rename reference to style plugin and converting them to style extension.

app/src/main/java/com/mapbox/maps/testapp/examples/annotation/SymbolActivity.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManager.kt
The type of `annotations` in AnnotationManger is Map, which is not convenient for users. This pr change its type from Map to List.
=> [Annotation plugin] Change annotations from map to list

CHANGELOG.md
Update changelog for v10.0.0-beta.14
=> [docs] update changelog for beta.14

app/src/main/AndroidManifest.xml, app/src/main/java/com/mapbox/maps/testapp/examples/AddOneMarkerSymbolActivity.kt, app/src/main/res/values/example_descriptions.xml, app/src/main/res/values/example_titles.xml
This PR add a new example which add a single marker with symbol layer and aligns with the one in gl js https://docs.mapbox.com/mapbox-gl-js/example/add-a-marker/
=> [example] Add a example of add one marker symbol to map

app/src/main/AndroidManifest.xml, app/src/main/java/com/mapbox/maps/testapp/examples/MapboxStudioStyleActivity.kt, app/src/main/res/layout/activity_style_mapbox_studio.xml, app/src/main/res/values/example_descriptions.xml, app/src/main/res/values/example_titles.xml
This PR adds an example of showing a custom style from Mapbox Studio
=> [app] Add Mapbox Studio style example

app/src/main/java/com/mapbox/maps/testapp/examples/SimpleMapActivity.kt, app/src/main/res/layout/activity_simple_map.xml, app/src/main/res/values/example_descriptions.xml, app/src/main/res/values/example_titles.xml
In this pr:
- Update simple map camera align with gl js https://docs.mapbox.com/mapbox-gl-js/example/simple-map/
- Update title and description for add a marker
- Update title for simple map
=> [app] Update simple map camera

CHANGELOG.md
The pr update the changelog for beta.15
=> Update CHANGELOG.md for beta.15

plugin-overlay/README.md
- Fixed a minor typo in the MapOverlay README
=> Fix typo in MapOverlay README

sdk/src/main/java/com/mapbox/maps/MapView.kt, sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
Based on mutliple user feedback, we want still want to allow same experience as with v9.0.0 of the product with having the ability to extend MapView and make a custom implementation of it.
=> [map] make public API entry points as MapView and Snapshotter

sdk/src/main/java/com/mapbox/maps/MapController.kt, sdk/src/main/java/com/mapbox/maps/PluginRequirementException.kt
Current configuration isn't ideal as it doesn't permit getting the binary size changes we want to achieve. 
Long term such restrictions will be enforced through a feature flag API.
=> [plugins] remove PluginRequirementException

plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
This is not a true solution, just an intermediate patch to make the experience usable. Todo comment inline in the code indicates what true solution  would look like, calculating the y offset based on triangulation, but will require exposing some functionality in the C++ core to convert zoom level to a pixel value.
=> Patch scroll gesture with a pitched camera

app/src/main/java/com/mapbox/maps/testapp/examples/annotation/AnnotationUtils.kt, app/src/main/java/com/mapbox/maps/testapp/examples/annotation/SymbolClusterActivity.kt
=> Fix main after gl bump

plugin-location/src/main/java/com/mapbox/maps/plugin/location/LocationCameraAnimatorCoordinator.kt, plugin-location/src/main/java/com/mapbox/maps/plugin/location/LocationCameraController.kt, plugin-location/src/test/java/com/mapbox/maps/plugin/location/LocationCameraControllerTest.kt
Use handler in order to check if we need to start another animation __after__ all map camera events are delivered.
=> Fix legacy location plugin stackoverflow error

CHANGELOG.md
This PR adds the changelog entry for v10.0.0-beta.16 release
=> [changelog] Update change log for v10.0.0-beta.16

extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-location/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
This PR updates the plugin version to v10.0.0-beta.16 in the README.
=> [doc] Update plugin version to v10.0.0-beta.16 in the README.

app/src/main/java/com/mapbox/maps/testapp/examples/AnimatedMarkerActivity.kt, buildSrc/src/main/kotlin/Project.kt, plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt, plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GestureOptionsTest.kt, plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturePluginTest.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapProjectionDelegate.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapTransformDelegate.kt, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt, sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt, sdk/src/main/java/com/mapbox/maps/Style.kt, sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt, sdk/src/test/java/com/mapbox/maps/NativeMapTest.kt
=> [dependencies] Use gl-native beta.18, adopt changes

CHANGELOG.md
This PR fixes the change log entry in beta.16.
=> [changelog] Fix the change log for beta.16.

sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapProjectionDelegate.kt, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
=> [javadoc] Update docs about right time to call some transformation functions

.circleci/config.yml, .gitignore, Makefile, scripts/update-android-docs.sh
This pr add the script to auto generate docs and then create pr for review.
It will also create a pr to doc repo to update sdk version number.
=> [docs] Add script to auto generate docs and create pull request while releasing 

app/src/main/java/com/mapbox/maps/testapp/examples/SimpleMapActivity.kt, sdk/src/androidTest/java/com/mapbox/maps/StyleLoadTest.kt, sdk/src/main/java/com/mapbox/maps/MapController.kt, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt, sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt, sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
This pr add check fin `onResume`, if there is no style provided, we will load MAPBOX_STREET by default.
=> Load streets by default if no style is provided

app/src/main/java/com/mapbox/maps/testapp/examples/MapOverlayActivity.kt, plugin-overlay/src/main/java/com/mapbox/maps/plugin/overlay/MapOverlayPluginImpl.kt, sdk-base/src/main/java/com/mapbox/maps/MapboxExperimental.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/overlay/MapOverlayPlugin.kt
This pr add `opt-in` annotation to make overlay plugin experimental for users.
=> Make overlay plugin experimental

CHANGELOG.md
=> Update changelog for v10.0.0-beta.17

scripts/update-android-docs.sh
While doing the release we will update the version name in `gradle.properties` which will prevent checking new branch in the script.  This pr makes it force checkout new branch. Since the android docs are generated before, it will not have side effects.
```
+ prepare_branch_with_documentation android-v10.0.0-beta.17
+ INTERIM_BRANCH_WITH_DOCUMENTATION=publisher-production_android-v10.0.0-beta.17
+ git checkout publisher-production
error: Your local changes to the following files would be overwritten by checkout: …
```
=> Force checkout branch while preparing branch with documentation

extension-style/README.md, plugin-animation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-location/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
=> Bump sdk version to v10.0.0-beta.17 in readme

.circleci/config.yml, DEVELOPING.md
=> Disable codecov

plugin-attribution/src/main/java/com/mapbox/maps/plugin/attribution/AttributionViewImpl.kt, plugin-attribution/src/test/java/com/mapbox/common/ShadowLogger.java, plugin-attribution/src/test/java/com/mapbox/maps/plugin/attribution/AttributionViewImplTest.kt, plugin-logo/src/main/java/com/mapbox/maps/plugin/logo/LogoViewImpl.kt, plugin-logo/src/main/java/com/mapbox/maps/plugin/logo/LogoViewPlugin.kt, plugin-logo/src/test/java/com/mapbox/maps/plugin/logo/LogoViewImplPluginTest.kt, sdk-base/src/main/res/values/strings.xml, sdk/src/main/java/com/mapbox/maps/MapController.kt
Fix disabling logo in xml with `mapbox_logoEnabled` attribute.
=> [logo] Fix disabling logo in xml

plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
=> [gestures] Properly reset anchor after some gestures

app/src/main/AndroidManifest.xml, app/src/main/java/com/mapbox/maps/testapp/examples/LegacyOfflineActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt, app/src/main/res/layout/activity_legacy_offline.xml, app/src/main/res/layout/activity_offline.xml, app/src/main/res/values/example_descriptions.xml, app/src/main/res/values/example_titles.xml, app/src/main/res/values/strings.xml, app/src/main/res/values/styles.xml
This PR adds an example of the usage of the new OfflineManager and TileStore to download style pack and tile regions.
https://user-images.githubusercontent.com/2764714/115440277-3c543b00-a218-11eb-9d50-11cfd0c7de71.mp4
=> Add offline activity example.

CHANGELOG.md
=> Add changelog for beta.18

extension-style/README.md, plugin-animation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
=> Bump sdk version to beta.18 in README.md

app/src/main/java/com/mapbox/maps/testapp/examples/MapViewCustomizationActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/MapboxStudioStyleActivity.kt, app/src/main/res/layout/activity_style_mapbox_studio.xml, sdk/src/main/java/com/mapbox/maps/MapController.kt, sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt, sdk/src/main/java/com/mapbox/maps/MapView.kt, sdk/src/main/java/com/mapbox/maps/ResourcesAttributeParser.kt, sdk/src/main/res-public/values/public.xml, sdk/src/main/res/values/attrs.xml, sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt, sdk/src/test/java/com/mapbox/maps/MapInitOptionsTest.kt, sdk/src/test/java/com/mapbox/maps/MapViewTest.kt
=> Add styleUri property in MapInitOptions

sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
=> Fix test due to missed rebase

app/src/androidTest/java/com/mapbox/maps/testapp/integration/BaseIntegrationTest.kt, app/src/main/java/com/mapbox/maps/testapp/examples/SurfaceRecyclerViewActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/DataDrivenMapSnapshotterActivity.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/generated/Expression.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/types/FormatSection.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/CustomGeometrySource.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/types/FormattedSection.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotation.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManager.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationOptions.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotation.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManager.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationOptions.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotation.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManager.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationOptions.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotation.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManager.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationOptions.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/ClusterOptions.kt, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt, sdk/src/main/java/com/mapbox/maps/Style.kt
PR updates generated/non-generated code to remove all `<p> / <br>` instances in our code.
=> [docs] cleanup kdoc documentation, remove html tags

CHANGELOG.md, extension-style/README.md, plugin-animation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
=> Update changelog for beta.19

app/src/androidTest/java/com/mapbox/maps/testapp/annotation/UpdateAnnotationTest.kt
- Increate the wait time avoid the timeout error
- Update the logic for changing style
=> Update UpdateAnnotationTest to make it more robust

sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
Sometimes, MapboxRenderThreadTest will fail in CI. This pr makes it more robust by adding CountDownLatch to wait the async execution.
=> Make MapboxRenderThreadTest robust.

extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SkyLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/light/LightPosition.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/Light.kt
`&#xB0` is not supported by kdoc, so replace them with word `degree`
=> [docs] Replace the unsupported character with word

CHANGELOG.md, extension-style/README.md, plugin-animation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
=> Update changelog for beta.20

CHANGELOG.md
=> Adjust changelog for v10.0.0-beta.20

CHANGELOG.md
=> Better changelog entries for v10.0.0-beta.20

package-lock.json, package.json
Removal of NPM dependencies, these are no longer used in this repository. 
Refs #347
=> [build] cleanup npm used dependencies

app/src/main/java/com/mapbox/maps/testapp/examples/DebugModeActivity.kt, app/src/main/res/layout/activity_debug.xml, app/src/main/res/menu/menu_debug_mode.xml, app/src/main/res/values/strings.xml
Fixes: https://github.com/mapbox/mapbox-maps-android/issues/359
This PR fixes the UX for the debug mode activity, moving the configs from a linear layout to the menu, to be able to work with smaller screens.
=> Fix usability of DebugModeActivity.

app/src/androidTest/java/com/mapbox/maps/testapp/integration/events/StyleLoadedEventTest.kt, app/src/main/java/com/mapbox/maps/testapp/examples/TransparentBackgroundActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/sky/SkyLayerSnapshotterActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/DataDrivenMapSnapshotterActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/LocalStyleMapSnapshotterActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/MapSnapshotterActivity.kt, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt, sdk/src/main/java/com/mapbox/maps/Snapshotter.kt, sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt, sdk/src/test/java/com/mapbox/maps/SnapshotterDelegateTest.kt, sdk/src/test/java/com/mapbox/maps/SnapshotterTest.kt
Align naming for loading style for both `Snapshotter` and `MapboxMap`.
```
Snapshotter.setUri(uri: String) -> Snapshotter.setStyleUri(styleUri: String)
Snapshotter.getUri()-> Snapshotter.getStyleUri()
Snapshotter.setJson(styleJson: String) -> Snapshotter.setStyleJson(styleJson: String)
Snapshotter.getJson()-> Snapshotter.getStyleJson()
MapboxMap.loadStyleJSON(styleJson: String) -> MapboxMap.loadStyleJson(styleJson: String)
```
=> Align load style functions for MapboxMap and Snapshotter

extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt, sdk/src/androidTest/java/com/mapbox/maps/MapIntegrationTest.kt
Fixes: #376 
Call style loaded callback if data set directly to geojson.
=> Call style loaded callback if data set directly to geojson

app/src/main/AndroidManifest.xml, app/src/main/java/com/mapbox/maps/testapp/ExampleOverviewActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/java/DSLStylingJavaActivity.java, extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt, plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt, sdk/src/main/java/com/mapbox/maps/MapView.kt
This pr adds java annotations to StyleExtensionImpl to enable users to call these API from java codes.
=> Add java example for DSL and add java annotations to StyleExtensionImpl

.circleci/config.yml, gradle/sdk-registry.gradle
This pr install mbx-ci and setup aws confidential for release job
A successful test job could be found [here](https://app.circleci.com/pipelines/github/mapbox/mapbox-maps-android/1445/workflows/5748c73e-35f8-4f4e-8633-d14cf634857d/jobs/10647)
=> Add mbx-ci for release

CHANGELOG.md
=> Update changelog for beta.21

extension-style/README.md, plugin-animation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
Bump the README.md to use beta.21 reference.
=> Bump the README.md to use beta.21 reference.

app/src/main/java/com/mapbox/maps/testapp/examples/java/DSLStylingJavaActivity.java, plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
=> Fix typo in MapboxMapUtils jvm name.

app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt, sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
Remove usage of ambient cache from the codebase.
=> Remove usage of ambient cache from the codebase.

CHANGELOG.md
Add changelog for v10.0.0-rc.1 release.
=> Add changelog for v10.0.0-rc.1 release.

CHANGELOG.md, extension-style/README.md, plugin-animation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
This PR updates README.md to use v10.0.0-rc.1.
=> Update README.md to use v10.0.0-rc.1.

sdk/src/androidTest/java/com/mapbox/maps/RenderCacheTest.kt, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
Fixes: #402 
Introduce cache size check when setting render cache.
=> Introduce size check for render cache

Makefile
This pr add command for generate-changelog which will generate github token with `mbx-ci` and create the change log.
=> Add command for generate-changelog

Makefile, scripts/update-android-docs.sh
This pr updates the command and script to generate android docs and upload branches to remote repos.
PRs need to be created manually after all branches are upload to repos because of mbx-ci token authentication issue.
=> Add command to generate and upload docs locally

scripts/update-android-docs.sh
This pr fix the wrong path of android doc repo and clone it if not exists.
=> Fix the wrong path in update-android-docs.sh

buildSrc/src/main/kotlin/Project.kt
</changelog>`.
[Refs](https://github.com/mapbox/mapbox-events-android/releases/tag/telem-8.1.0-core-5.0.0),
This PR bumps telemetry to 8.1.0
=> [deps] Bump telemetry to 8.1.0

app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PointAnnotationActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PointAnnotationClusterActivity.kt, app/src/main/res/menu/menu_symbol.xml, app/src/main/res/values/strings.xml, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapFeatureQueryDelegate.kt, sdk/src/main/java/com/mapbox/maps/MapController.kt, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt, sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt, sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
By changing AnnotationManagerImpl#queryMapForFeatures function to synchronous, we are able to handle the return value of MapClick in AnnotationManager correctly
=> Perform annotation click synchronously

CHANGELOG.md
=> Changelog for rc.3

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
=> Update md files to use v10.0.0-rc.3

app/src/main/AndroidManifest.xml, app/src/main/java/com/mapbox/maps/testapp/examples/RuntimeStylingActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/java/RuntimeStylingJavaActivity.java, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/Layer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/LayerExt.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/Light.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/LightExt.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/Source.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/SourceExt.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/Terrain.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/TerrainExt.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImplTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
This pr add example RuntimeStylingJavaActivity and add annotation `@file:JvmName` to Layer, Source, Light and Terrain.
=> Add RuntimeStylingJavaActivity

app/src/main/AndroidManifest.xml, app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/FillExtrusionActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/SantaCatalinaActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/Terrain3DShowcaseActivity.kt, app/src/main/res/values/example_categories.xml, app/src/main/res/values/example_descriptions.xml, app/src/main/res/values/example_titles.xml
Update the title, packages and categories for 3D example screens in order to align with ios and gl-js.
=> Update title, package and category for 3D examples

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
=> Add changelog for rc.4

sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
Update offline tests to reflect to latest upstream changes.
=> Update offline tests to reflect to latest upstream changes

sdk/src/androidTest/java/com/mapbox/maps/MapSnapshotterTest.kt
As it's fixed upstream we should be safe to un-ignore the test.
Additionally added couple more checks for the test to pass.
=> Re-enable snapshotter sanity test

DEVELOPING.md
This PR adds instructions on how to use snapshot in DEVELOPING.md
=> [doc] Add guide to snapshot releases in DEVELOPING.md

plugin-lifecycle/src/main/java/com/mapbox/maps/plugin/lifecycle/MapboxLifecyclePluginImpl.kt
Fixes: https://github.com/mapbox/mapbox-maps-android/issues/525
=> Fix memory leak in lifecycle plugin

CHANGELOG.md, extension-androidauto/README.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
Add change log for v10.0.0-rc.5 release.
=> Add change log for v10.0.0-rc.5 release.

.circleci/config.yml, scripts/ci-circleci-start-pipeline.py
Migrate from mapbox-maps-stylegen to internal repository for validating generated code.
=> [ci] move from mapbox-maps-stylegen to mapbox-maps-android-internal

sdk/src/main/java/com/mapbox/maps/FontUtils.kt
=> Fix ktlint on main branch

app/src/androidTest/java/com/mapbox/maps/testapp/overlay/MapOverlayPluginTest.kt, app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceTest.java, app/src/main/java/com/mapbox/maps/testapp/examples/MapOverlayActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/java/DSLStylingJavaActivity.java, app/src/main/java/com/mapbox/maps/testapp/examples/java/RuntimeStylingJavaActivity.java, extension-style/src/main/java/com/mapbox/maps/extension/style/image/ImageExt.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/image/ImageExtensionImpl.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/image/ImageNinePatchExtensionImpl.kt, plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesExt.kt, plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentExt.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt, plugin-logo/src/main/java/com/mapbox/maps/plugin/logo/LogoExt.kt, plugin-logo/src/main/java/com/mapbox/maps/plugin/logo/LogoViewPlugin.kt, plugin-overlay/src/main/java/com/mapbox/maps/plugin/overlay/MapOverlayExt.kt, plugin-overlay/src/main/java/com/mapbox/maps/plugin/overlay/MapOverlayPluginImpl.kt, plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarExt.kt, plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginImpl.kt, sdk-base/src/main/java/com/mapbox/maps/MapboxExperimental.kt
Move extension functions into separate files and update the Java Api to Java style.
change `mapView.overlay()` to `mapView.mapboxOverlay` because `mapView.overlay` would conflict with `ViewGroup.getOverlay()`
API changes
`mapView.overlay() -> mapView.mapboxOverlay`
```
MapboxMapUtils. addOnFlingListener -> GesturesUtils.addOnFlingListener
MapboxMapUtils. removeOnFlingListener -> GesturesUtils.removeOnFlingListener
MapboxMapUtils. addOnMapClickListener -> GesturesUtils.addOnMapClickListener
MapboxMapUtils. …
```
=> Update java API name for extension functions

plugin-locationcomponent/build.gradle.kts
This PR removes turf dependency from the location component plugin since it is not used.
=> [deps] Remove turf dependency of location component plugin.

app/src/main/AndroidManifest.xml, app/src/main/java/com/mapbox/maps/testapp/examples/featurestate/FeatureStateActivity.kt, app/src/main/res/layout/activity_feature_state.xml, app/src/main/res/values/example_descriptions.xml, app/src/main/res/values/example_titles.xml, app/src/main/res/values/strings.xml, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
This PR ports the [Create interactive hover effects using feature state](https://docs.mapbox.com/help/tutorials/create-interactive-hover-effects-with-mapbox-gl-js/?size=n_10_n) js example to Android.
https://user-images.githubusercontent.com/2764714/128202661-3a90f5c7-0d5c-4052-8a70-d4ecba84c7d1.mp4
=> [testapp] Add feature state example.

buildSrc/src/main/kotlin/Project.kt
=> Bump gl-native to v10.0.0-rc.7.1

build.gradle.kts, buildSrc/src/main/kotlin/Project.kt, gradle/sdk-registry.gradle
This PR fixes the maven publish configurations due to the Android Gradle Plugin version bump.
=> Fix maven publish configurations.

app/src/androidTest/java/com/mapbox/maps/testapp/featurestate/FeatureStateTest.kt
Instrumentation test for feature state api.
=> [Feature state] Add instrumentation test for feature state

plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotation.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotation.kt
=> fix uppercase bug

CHANGELOG.md, extension-androidauto/README.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
=> Update change log for rc.7

CHANGELOG.md, extension-androidauto/README.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
=> Add changelog for rc.8

.circleci/config.yml
This PR adds a mvp CI setup to build the Android Auto test app.
=> Add Android Auto CI setup.

extension-localization/src/test/java/com/mapbox/maps/extension/localization/SupportedLanguagesTest.kt, sdk-base/src/test/java/com/mapbox/maps/util/MathUtilsTest.kt
This PR adding parametrized tests where applicable.
=> Add parametrized tests

app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/CircleAnnotationManagerAndroidTest.kt, app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PointAnnotationManagerAndroidTest.kt, app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PolygonAnnotationManagerAndroidTest.kt, app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PolylineAnnotationManagerAndroidTest.kt, app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PointAnnotationActivity.kt, app/src/main/res/menu/menu_symbol.xml, app/src/main/res/values/strings.xml, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManager.kt
=> Add support for SymbolZOrder in PointAnnotationManager

buildSrc/src/main/kotlin/Project.kt, extension-style/build.gradle.kts, extension-style/src/test/java/com/mapbox/maps/extension/style/EqualHashCodeTest.kt, module-telemetry/build.gradle.kts, module-telemetry/src/main/java/com/mapbox/maps/module/telemetry/MapLoadEvent.kt, module-telemetry/src/main/java/com/mapbox/maps/module/telemetry/PerformanceEvent.kt, module-telemetry/src/test/java/com/mapbox/maps/module/telemetry/EqualHashCodeTest.kt, sdk-base/build.gradle.kts, sdk-base/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorOptions.kt, sdk-base/src/test/java/com/mapbox/maps/EqualHashCodeTest.kt
In this PR added tool that allows to check manually generated `equals` and `hashCode` method. And makes sure not to forget update them after modification.
=> Equals and hashcode tests

DEVELOPING.md
Fixes: #647 
fixed typo in path to `developer-config.xml`
=> Fix typo in developing.md

extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
=> Revert "Change the logic of handling geojson update"

extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/GeoJsonSourceTest.kt, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/VectorSourceTest.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/VectorSource.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/VectorSourceTest.kt
PromoteId does not have a default value in source property. Removed the tests for default values.
=> Fix promoteid style test

CHANGELOG.md
This PR adds change log for v10.0.0-rc.9 release.
=> Add change log for v10.0.0-rc.9

buildSrc/src/main/kotlin/Project.kt, plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesExt.kt, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt, sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Exception will be thrown when gestures functionality trying to use but plugin was not added to MapView. Reported in #554
=> Throw exception when gestures plugin is missing when trying to use

CHANGELOG.md, extension-androidauto/README.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
This PR bumps SDK version to rc.9 in READMEs.
=> [doc] Bump SDK version to rc.9 in READMEs.

.circleci/config.yml, CHANGELOG.md, plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
- Added camera crash fix.
- Added config for snapshot release.
- Added changelog for patch release v10.0.0-beta.19.1
=> hotfix for release v10.0.0-beta.19.1

.github/pull_request_template.md
Update pull request template with Jvm annotations so as not to forget optimize code for java consumption
=> Update pull request template with jvm annotations

mapbox-lint/src/main/java/com/mapbox/maps/lint/LifecycleMethodDetector.kt, mapbox-lint/src/test/java/com/mapbox/maps/lint/LifecycleMethodDetectorTest.kt
=> Fix failed lint tests

app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java
Fix JavaInterfaceChecker due to gesture settings change.
=> Fix JavaInterfaceChecker due to gesture settings change.

sdk/src/main/java/com/mapbox/maps/MapboxConfigurationException.kt
Fixes: https://github.com/mapbox/mapbox-maps-android/issues/705
Fix wrong attribute reference in runtime exception when token is missing.
=> Fix wrong attribute reference when token is missing

.circleci/config.yml
=> Update deprecated robo device

extension-androidauto/build.gradle.kts
This PR stop publishing the experimental Android Auto extension together with the SDK.
We will come up with a plan to iterate some plugin/extensions separately and have different versioning for it. The last Android Auto extension release is still available and can be used together with the SDK.
=> Stop publishing Android Auto extension together with the SDK.

plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarImpl.kt, plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/ScaleBarImplTest.kt
Scalebar's width and height are the same as MapView, so we always draw scalebar on the top-left.
In this pr, Scalebar's width changes to half of the width of MapView, and height changes to the content height of scaleBar and unit text, and the `position` property can works.
Force RTL
=> Fix scaleBar position property not working issue.

plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewImpl.kt, plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt, plugin-compass/src/main/res/values/dimens.xml
- Add JvmOverloads for Compass View constructor to simplify the code
- Move compass view size to dimensions.
=> Add JvmOverloads for Compass plugin

.gitignore, Makefile, scripts/update-android-docs.sh, sdk/build.gradle.kts
- need to update documentation and scripts to publish documentation
- fine tune dokka configuration to replace the title in screenshot to `mapbox-maps-android`
=> [docs] append upstream documentation to project

extension-localization/README.md, extension-style/README.md, gradle.properties, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
Update README versions to v10.1.0-rc.1, update snapshot version.
=> Update README versions to v10.1.0-rc.1, update snapshot version.

.circleci/config.yml, Makefile, scripts/update-android-docs.sh
This PR updates the script to enable creating PR in CI automatically by changing the remote url to https style combined with a token generated by `mbx-ci`.
Test PRs generated by internal [CI job](https://app.circleci.com/pipelines/github/mapbox/mapbox-maps-android-internal/1504/workflows/bb916257-8915-406c-8a21-09dd93049120/jobs/3873)
https://github.com/mapbox/mapbox-maps-android/pull/801
https://github.com/mapbox/mapbox-maps-android/pull/802
=> Enable create pr in CI automatically

.circleci/config.yml, scripts/generate-docs-start-pipeline.py
This pr add the script to trigger generating docs and PRs in the internal repo.
A successful [job](https://app.circleci.com/pipelines/github/mapbox/mapbox-maps-android-internal/1520/workflows/61aa6987-2d79-44e1-a733-873e8d5a9144/jobs/3920) triggered from local verifies the result.
=> Add pipline to trigger generating docs in internal repo

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
=> Update change log for 10.1.0

scripts/update-android-docs.sh
The key name for the version number in android docs has been changed.
This pr updates the key name to the new one.
=> Update key name for version number

.circleci/config.yml
To speed up CI checks we can save `apks` for instrumentation test in [workspace](https://selleo.com/til/posts/8tdwoeekl3-persisting-files-between-jobs-in-circlecis-worklow)
=> refactor build stages. save apk to workspace before instrumentation tests

scripts/update-android-docs.sh
We have moved the command for generating docs to the internal repo, however the path in update-android-docs.sh still points to the former path, so the CI in android-doc will keep fails
This PR applies the correct path to the script.
=> Update update-android-docs.sh to upload the correct docs

app/src/androidTest/java/com/mapbox/maps/testapp/annotation/UpdateAnnotationTest.kt, app/src/androidTest/java/com/mapbox/maps/testapp/annotation/UpdateAnnotationWithMultiManagersTest.kt, app/src/main/java/com/mapbox/maps/testapp/examples/GesturesActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/annotation/AnimatePointAnnotationActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PointAnnotationActivity.kt
Remove deprecated methods for annotation manager which uses param `mapview`.
=> Annotation manager cleanup

sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotationManagerImpl.kt
Reduce allocating new collections when drawing views as this is called generally 60 times per second.
=> View annotation: view draw performance

extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/expressions/ExpressionTest.kt
Number format functionality needs to use a fixed locale configuration and not rely on device locale.
=> fix number format test

.github/pull_request_template.md
[example of usage](https://github.com/mapbox/mapbox-maps-android/pull/847)
=> add template for before-after block in PR template for better visualization

sdk/src/main/java/com/mapbox/maps/MapView.kt, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt, sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt, sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt, sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotation.kt
- Move `ViewAnnotationManagerImpl` to `com.mapbox.maps`. Some public records are now also internal.
- Add fix for view jumping.
| Before | After | 
| ----- | -----|
| <video src='https://user-images.githubusercontent.com/15800566/141281400-0e418995-90f9-4768-befc-2dde138cce8c.mp4' width=250/>  | <video src='https://user-images.githubusercontent.com/15800566/141281102-6a4e0624-1392-4c01-a74b-543715b2bb49.mp4  ' width=250/>|
- Use translationX / translationY instead of setting margin of the view group.
=> View annotations: final core fixes

.circleci/config.yml
Now we have two steps for debug and release flavors for one module. We can merge them in one and speed up job
For the first run get such results:
| ----- | -----|
| 3min 23s (release) + 2min 35s (debug) | 4min 17s (together) |
=> merge flavors build for app on CI

sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt
=> View annotations: native error handling

app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt, sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
This PR implement 3 easy to use functions for cluster on top of queryFeatureExtensions
```
getClusterExpansionZoom
getClusterChildren
getClusterLeaves
```
=> Implement cluster API on top of queryFeatureExtensions

.circleci/config.yml, scripts/ci-circleci-start-pipeline.py
Add new flag for running benchmark tests only when merge PR to the main branch
=> add merge-main flag for circle ci pipeline

.circleci/config.yml
This pr enables to trigger the needed release job while making a release by tag.
=> Trigger release job for release tag.

DEVELOPING.md
- Adding instructions to set ndk path (especially for mac m1 users) while installing dependencies using sdkmanager.
- Updated ndk version.
=> update developing.md file

app/src/main/AndroidManifest.xml, app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationBasicAddActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationShowcaseActivity.kt, app/src/main/res/values/example_descriptions.xml, app/src/main/res/values/example_titles.xml
Add view annotation on top of the map on click.
https://user-images.githubusercontent.com/15800566/142606276-007956ac-91ec-46f4-b2c7-b312a0a65448.mp4
=> [examples] Basic view annotation example activity

plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt
This PR refactors the fling gesture tests to be parameterised tests.
=> [gestures] Refactor fling gestures test to be parameterised tests.

app/src/main/res/layout/item_single_example.xml
Fixed descriptions in the list were cut at the bottom, changed layout to avoid that.
| <img src="https://user-images.githubusercontent.com/2265924/142622306-98c0df24-00a9-4654-a4df-1b284f873e3e.png" width = 250/> | <img src="https://user-images.githubusercontent.com/2265924/142622316-bde94086-ba9f-467d-be4a-6ee3e1e77b6a.png" width = 250/> |
=> Fixed description text cut at the bottom in the example list.

package-lock.json
This PR bumps aws-sdk and base64-js npm packages to address the vulnerabilities.
=> Fix npm vulnerabilities.

.github/pull_request_template.md
=> Add step to PR template

.circleci/config.yml, buildSrc/src/main/kotlin/Project.kt, scripts/update-android-docs.sh
This PR revert dokka to 1.4.10.2 so that the generated docs will keep the original structure.
Also update the CI config, now only the stable release can trigger the job of generating docs.
=> Revert Dokka to 1.4.10.2; only generate docs for stable releases.

sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt, sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerTest.kt
Prevent multiple usage of `associatedFeatureId` in view annotations. Runtime exception will be thrown if some view annotation will be assigned `associatedFeatureId` (by either adding or updating) if some another view annotation has already this `associatedFeatureId`. Rule is that one and only one view annotation could have `associatedFeatureId`.
=> Prevent multiple usage of associatedFeatureId in view annotations

sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt, sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerTest.kt
Port: https://github.com/mapbox/mapbox-maps-android/pull/896
=> Port: prevent multiple usage of associatedFeatureId in view annotations

DEVELOPING.md
Updated codestyle section of doc a bit. 
Added mention of script that installs pre-commit git hook to check ktlint.
=> Update developing doc about codestyle

sdk/src/androidTest/java/com/mapbox/maps/TestUtils.kt, sdk/src/androidTest/java/com/mapbox/maps/ViewAnnotationTest.kt, sdk/src/androidTest/res/layout/view_annotation.xml
=> View annotations: add instrument tests

extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt, sdk-base/src/main/java/com/mapbox/maps/extension/style/StyleContract.kt, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt, sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
In the past we can't load an empty style uri as it's not valid, we will only get a black screen and some error log.
This pr adds a check for empty uri and will load an empty json `{}` if the uri is empty so that users can load an empty uri and then add sources and layers.
The screenshot for ImageSourceActivity with empty style uri
=> Allow load empty style uri

CHANGELOG.md, build.gradle.kts, buildSrc/src/main/kotlin/Project.kt, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
Patch release v10.0.1 holding billing fix.
=> Prepare patch release v10.0.1

CHANGELOG.md
=> Add changelog for v10.0.1

.github/pull_request_template.md
Reordered sections in the PR template, so that most important for the review were popped to the top.
=> Reorder sections in PR template

.circleci/config.yml, scripts/java-api-check-all.sh, scripts/java-api-check.json, scripts/java-api-check.sh, scripts/semver-check.sh
This pr update api check scripts to align with the lastest gl-native
Verified locally by changing a public method in `MapView` and run command ` ./scripts/java-api-check-all.sh "android-v10.2.0"
` then got the following result
```
========================  Checking module: sdk, module aar name: sdk  ====================================
+ ./scripts/java-api-check.sh android-v10.2.0 ./sdk/build/outputs/aar/sdk-release.aar sdk
...
Compare result: major
+ ./scripts/semver-check.sh v10.2.0 10.1.0 major
Semver-check …
```
=> Update api check script

extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/BaseStyleTest.kt, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/GeoJsonSourceTest.kt, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/ImageSourceTest.kt, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/RasterDemSourceTest.kt, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/RasterSourceTest.kt, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/VectorSourceTest.kt
Geojson tests should check `STYLE_DATA_LOADED ` event in order to validate the data is applied.
=> [Testing] Fix Geojson flaky test

app/src/androidTest/java/com/mapbox/maps/testapp/gestures/generated/GesturesAttributeParserDefaultValueTest.kt, app/src/androidTest/java/com/mapbox/maps/testapp/gestures/generated/GesturesAttributeParserTest.kt, app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java, app/src/main/res/layout/generated_test_gestures.xml, plugin-gestures/build.gradle.kts, plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt, plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesAttributeParser.kt, plugin-gestures/src/main/res-public/values/public.xml, plugin-gestures/src/main/res/values/attrs.xml, plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt, plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/generated/GesturesAttributeParserTest.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettings.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettingsBase.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettingsInterface.kt
This PR adds a config `simultaneousRotateAndPinchToZoomEnabled` in `GesturesSettings` to control whether to allow simultaneous zoom and rotate gesture or not.
The default value for `simultaneousRotateAndPinchToZoomEnabled` is true, which means simultaneous zoom and rotate gesture is enabled by default. If users want to disable this function, just set its value to false like this:
`
mapView.gestures.simultaneousRotateAndPinchToZoomEnabled = false
`
=> Simultaneous zoom and rotate gesture

app/src/main/java/com/mapbox/maps/testapp/examples/linesandpolygons/SnakingDirectionsRouteActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationShowcaseActivity.kt
Fix an error caught by robo test:
```
java.util.ConcurrentModificationException
FATAL EXCEPTION: GEOJSON_PARSER
Process: com.mapbox.maps.testapp, PID: 13082
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.next(ArrayList.java:860)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(Unknown Source:19)
at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.write(Unknown Source:2)
at com.mapbox.geojson.FeatureCollection$GsonTypeAdapter.write(Unknown Source:126)
at com.mapbox.geojson.FeatureCollection$GsonTypeAdapter.write(Unknown Source:2)
at com.google.gson.Gson.toJson(Unknown Source:34)
at com.google.gson.Gson.toJson(Unknown Source:8)
at com.google.gson.Gson.toJson(Unknown Source:5)
at com.google.gson.Gson.toJson(Unknown Source:13) …
```
=> Fix concurrent modification exception in example

CHANGELOG.md
For some reason gl-native did not add this change to their changelog so we missed it as well. Adding it back as it's a pretty important feature.
=> Add missing changelog entry for v10.2.0-beta.1

plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt, plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturePluginTest.kt
=> Port : shove gesture angle

CHANGELOG.md
=> update changelog for v10.1.1

plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt, plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt
This PR introduces a fix to the issue that gestures moving too dramatic at high camera pitch near the horizon line.
* The scroll gesture started above the horizon line will be ignored(until the touch point exceed below the horizon line).
* The fling(scroll deceleration) above the horizon line will be skipped.
* Reduces drag sensitivity around and above horizon.
| <video src="https://user-images.githubusercontent.com/2764714/144038814-91ea047f-c757-4625-98b7-d37c3acd0cc1.mp4" width = 250/> | <video src="https://user-images.githubusercontent.com/2764714/144037524-0878b9eb-4a5d-46eb-b8f6-fe7e608071ea.mp4" width = 250/> |
PRs must be submitted under the terms of our …
=> [gestures] Fix gestures at high camera pitch near horizon line.

plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt, plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt
This PR ports https://github.com/mapbox/mapbox-maps-android/pull/869 and https://github.com/mapbox/mapbox-maps-android/pull/927 to the v10.2 release branch.
=> [gestures] Port gestures test refactor and drag api fixes.

app/src/androidTest/java/com/mapbox/maps/testapp/gestures/generated/GesturesAttributeParserDefaultValueTest.kt, app/src/androidTest/java/com/mapbox/maps/testapp/gestures/generated/GesturesAttributeParserTest.kt, app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java, app/src/main/res/layout/generated_test_gestures.xml, plugin-gestures/build.gradle.kts, plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt, plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesAttributeParser.kt, plugin-gestures/src/main/res-public/values/public.xml, plugin-gestures/src/main/res/values/attrs.xml, plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt, plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/generated/GesturesAttributeParserTest.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettings.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettingsBase.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettingsInterface.kt
=> port simultaneous zoom and rotate gesture

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
- Add changelog for v10.2.0-rc.1
=> Add changelog for v10.2.0-rc.1

DEVELOPING.md
=> Remove section about release management

.circleci/config.yml, build.gradle.kts, buildSrc/src/main/kotlin/Project.kt, scripts/update-android-docs.sh, settings.gradle.kts
=> [Port] Rollback dokka to 1.4.10.2

app/src/main/java/com/mapbox/maps/testapp/examples/WithinExpressionActivity.kt, plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/animation/MapAnimationOptions.kt, sdk/src/androidTest/java/com/mapbox/maps/CameraAnimationsPluginTest.kt
This PR adds startDelay property for MapAnimationOptions.kt and users can delay the high-level animation with it.
=> Add startDelay property for MapAnimationOptions.kt

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
* add changelog for v10.2.0-rc.1
=> Port changelog for v10.2.0-rc.1

app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java, plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesExt.kt
Deprecate map extension function to get gesture settings.
```kotlin
// Kotlin deprecated
mapboxMap.getGesturesSettings().focalPoint
// should be replaced with code to get e.g. current focal point
mapView.gestures.focalPoint
```
```java
// Java deprecated
GesturesUtils.getGesturesSettings(mapboxMap).getFocalPoint();
// should be replaced with code to get e.g. current focal point
GesturesUtils.getGestures(mapView).getFocalPoint();
```
=> Deprecate map extension function to get gesture settings

DEVELOPING.md, scripts/install-pre-commit/install-pre-commit.sh, scripts/install-pre-commit/pre-commit.sh
This PR adds token shield instructions and pre-commit scripts.
=> Add token shield instruction and pre-commit scripts.

module-telemetry/gradle.properties, plugin-annotation/gradle.properties, plugin-attribution/gradle.properties, plugin-compass/gradle.properties, scripts/update-android-docs.sh, sdk-base/gradle.properties, sdk/gradle.properties
This PR removes the mentioning of carbon in our docs.
=> Remove carbon from our docs.

extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/generated/Expression.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/image/ImageExtensionImpl.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/image/ImageNinePatchExtensionImpl.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/image/NinePatchUtils.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/Layer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/LayerExt.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/Light.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/Source.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/Terrain.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/types/FormattedSection.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/types/PromoteId.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/utils/ExpectedUtils.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/utils/TypeUtils.kt, plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationOptions.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationOptions.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationOptions.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationOptions.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LayerSourceProvider.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationLayerWrapper.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelSourceWrapper.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentAttributeParser.kt, sdk-base/src/main/java/com/mapbox/maps/MapboxExceptions.kt, sdk-base/src/main/java/com/mapbox/maps/util/MapboxExceptions.kt, sdk/src/main/java/com/mapbox/maps/MapController.kt, sdk/src/main/java/com/mapbox/maps/MapProjectionUtils.kt, sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt, sdk/src/main/java/com/mapbox/maps/plugin/MapPluginRegistry.kt
Introduce Mapbox exceptions instead of regular runtime exceptions allowing more precise control of catching them from user's end. Additionally use `IllegalArgumentException` / `IllegalStateException` / `UnsupportedOperationException` also inherited from `RuntimeException` where applicable to provide better experience when catching exceptions coming from an SDK.
Users already catching and processing exceptions should not be affected as all exception classes introduced are inherited from `RuntimeException`.
=> Introduce Mapbox exceptions instead of runtime

app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/MapViewSnapshotActivity.kt, sdk/src/main/java/com/mapbox/maps/MapSurface.kt, sdk/src/main/java/com/mapbox/maps/MapView.kt, sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt, sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt, sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt, sdk/src/test/java/com/mapbox/maps/renderer/MapboxRendererTest.kt
Previously reading pixels from GPU did not respect swap buffers moment. That led to blank snapshots on some devices (e.g. Huawei-s) since snapshot was taken after framebuffer which was purged after swapBuffers.
This PR fixes snapshot to always happen before `swapBuffers` is called.
Fixes: #923 
=> Fix empty snapshot on certain devices

extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/LightExt.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/light/generated/LightTest.kt
Removing API to remove light as it could not be actually removed from the style.
Skipping changelog here as changelog entry was modified in https://github.com/mapbox/mapbox-maps-android/pull/906 to say that only terrain remove API was added.
=> Remove API to remove light

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
patch release to fix billing issue
=> patch release v10.0.2

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
patch release to fix billing issue.
=> patch release v10.1.2

buildSrc/src/main/kotlin/Project.kt
=> update common deps

DEVELOPING.md, sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLConfigChooser.kt
Fix black screen issue on some devices caused by incorrect EGL config.
It should also fix the [black screen issue](https://github.com/mapbox/mapbox-maps-android/issues/976).
=> Fix egl config attributes that may lead to GL fails

DEVELOPING.md, sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLConfigChooser.kt
This is ported #980 to the release branch that fixes black screen issue on some devices.
=> Port EGL fix to 10.2

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
=> Add changelog for v10.2.0

app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/CircleAnnotationActivity.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
Remove the checking for `isDraggable` in `startDragging`, so that if users change the draggable to true in the long click, the dragging annotation could be dragged in the following drag events.
=> Enable drag annotation while changing the annotation to draggable in long click

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
=> Port-Add changelog for v10.2.0 (#996)

app/src/androidTest/java/com/mapbox/maps/testapp/locationcomponent/generated/LocationComponentAttributeParserDefaultValueTest.kt, app/src/androidTest/java/com/mapbox/maps/testapp/locationcomponent/generated/LocationComponentAttributeParserTest.kt, app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt, app/src/main/res/layout/activity_location_component.xml, app/src/main/res/layout/generated_test_locationcomponent.xml, app/src/main/res/menu/menu_location_component.xml, app/src/main/res/values/strings.xml, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationCompassEngine.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationProviderImpl.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentAttributeParser.kt, plugin-locationcomponent/src/main/res-public/values/public.xml, plugin-locationcomponent/src/main/res/values/attrs.xml, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationCompassEngineTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImplTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationProviderImplTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentAttributeParserTest.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/ConfigProperties.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettings.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsBase.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsInterface.kt
This PR adds the LocationCompassEngine for `PuckBearingSource.HEADING` mode to show the device heading correctly, users can also set to `PuckBearingSource.COURS` mode for GPS navigation. 
=> Add LocationCompassEngine for location component

app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/AnnotationWithCalloutActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationBasicAddActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationShowcaseActivity.kt, app/src/main/res/layout/item_callout_view.xml, sdk/src/androidTest/java/com/mapbox/maps/ViewAnnotationTest.kt, sdk/src/androidTest/res/layout/view_annotation_wrap_content.xml, sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt, sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotation.kt, sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotationManager.kt
Support WRAP_CONTENT dimensions for root views representing view annotations.
Fixes: https://github.com/mapbox/mapbox-maps-android/issues/874
=> Support wrap content dimensions for view annotations

app/src/main/java/com/mapbox/maps/testapp/examples/viewport/AdvancedViewportGesturesExample.kt, app/src/main/java/com/mapbox/maps/testapp/examples/viewport/ViewportShowcaseActivity.kt, plugin-viewport/build.gradle.kts, plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/ViewportPluginImpl.kt, plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/state/FollowingViewportStateImpl.kt, plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/state/OverviewViewportStateImpl.kt, plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransitionImpl.kt, plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/transition/ImmediateViewportTransition.kt, plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/ViewportPluginImplTest.kt, plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/ViewportTestConstants.kt, plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/state/FollowingViewportStateImplTest.kt, plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/state/OverviewViewportStateImplTest.kt, plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransitionImplTest.kt, plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/ImmediateViewportTransitionImplTest.kt, plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/MapboxViewportTransitionFactoryTest.kt, plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/TransitionUtilsTest.kt
Add unit tests to the viewport plugin.
=> [viewport] Add unit tests to ViewportPlugin.

Makefile
This PR replaces mbx ci token with private, which is safer.
=> Update mbx-ci token to private

scripts/java-api-check.json, scripts/java-api-check.sh
This PR update the config for revapi to check all the packages
=> Let api check all the packages

scripts/update-android-docs.sh
For unstable releases, we still need to update the version number in docs repo but not update in constats.
=> Only update release version in constants of android-docs repo for stable release

plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentExt.kt
This PR polish the codes for https://github.com/mapbox/mapbox-maps-android/pull/1012#discussion_r782139029
=> Polish codes for LocationComponentPlugin.createDefault2DPuck

.circleci/config.yml, Makefile, scripts/java-api-check-all.sh, scripts/java-api-check.json, scripts/java-api-check.sh
- Update config for java-api-check to include all classes
- Skip new added modules
=> Update api-check script to skip new module and fail the job when find major change

.circleci/config.yml, Makefile, scripts/check-changelog.sh
This pr add the job to check whether changelog is updated with new PR.
All PRs without `skip changlog` label must add the needed update into the changelog, otherwise CI job would fail.
=> Add job to check changelog

plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransitionImpl.kt, plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransitionImplTest.kt
This PR fixes the default viewport transition's anchor point, so that the default transition will end up in the correct camera position.
| <video src="https://user-images.githubusercontent.com/2764714/150799628-a81fef83-8865-4e80-af02-9d11766127de.mp4" width = 250/> | <video src="https://user-images.githubusercontent.com/2764714/150799660-6e22f173-c73e-40e9-996b-be65809f818c.mp4" width = 250/> |
=> [viewport] Fix default viewport transition's anchor point.

app/src/androidTest/java/com/mapbox/maps/testapp/viewport/ViewportPluginTest.kt, app/src/main/java/com/mapbox/maps/testapp/examples/viewport/ViewportShowcaseActivity.kt, plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/transition/ImmediateViewportTransition.kt, plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/ViewportPluginImplTest.kt, plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/state/FollowPuckViewportStateImplTest.kt, plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/state/OverviewViewportStateImplTest.kt, plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransitionImplTest.kt, plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/ImmediateViewportTransitionImplTest.kt, plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/MapboxViewportTransitionFactoryTest.kt
This PR refines the viewport plugin unit tests and added instrumentation test.
=> [viewport] Refine tests.

scripts/update-android-docs.sh
=> [Port]Only update release version in constants of android-docs repo for stable release. (#1059)

CHANGELOG.md
=> Rebase v10.3 changelog to main

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
This PR adds change log for v10.3.0-rc.1 release.
=> Add changelog for v10.3.0-rc.1

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md
This PR ports the v10.3.0-rc.1 changelog to main branch.
=> Port 10.3.0-rc.1 changelog

app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt
The download jobs for offline would continue even the host activity is closed. This PR fix this to avoid memory leak issue 
=> Cancel offline jobs in onDestroy

scripts/java-api-check.sh
Instead of checking the api based on the last release, it will be based on the last stable release, so that changes between beta and rc will not be recognized as breaking change.
=> Check api based on the last stable release

sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt, sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
This is #1100 port to the release branch.
Changelog for script :  `<changelog>Fix issue with map rendering when limiting max FPS.</changelog>`.
=> PR #1100 port to release branch

gradle.properties
Needed for several purposes but mostly for correct minor version when cutting snapshots.
=> Update minor version in gradle.properties

.gitignore, Makefile, scripts/java-api-check-all.sh, scripts/java-api-check.sh
This PR improve api-check scripts to show more granular breaking changes, and remove unnecessary prints.
=> Improve api-check scripts to show more granular breaking changes.

app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java, sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/ViewportStatusChangeReason.kt
This PR optimise viewport Java APIs and add validation to the JavaInterfaceChecker.
=> [viewport] Optimise viewport Java APIs and add validation.

app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java, sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/ViewportStatusChangeReason.kt
This PR ports https://github.com/mapbox/mapbox-maps-android/pull/1126 to v10.3 release branch
This PR optimise viewport Java APIs and add validation to the JavaInterfaceChecker.
=> [viewport] Optimise viewport Java APIs and add validation. (#1126)

app/src/main/AndroidManifest.xml, app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationWithPointAnnotationActivity.kt, app/src/main/res/values/example_descriptions.xml, app/src/main/res/values/example_titles.xml
=> Rename view annotation activity using point annotation

app/src/main/AndroidManifest.xml, app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationWithPointAnnotationActivity.kt, app/src/main/res/values/example_descriptions.xml, app/src/main/res/values/example_titles.xml
Port of https://github.com/mapbox/mapbox-maps-android/pull/1132
=> v10.3 port: Rename view annotation activity using point annotation

CHANGELOG.md, build.gradle.kts, buildSrc/src/main/kotlin/Project.kt, sdk/build.gradle.kts
this pr port plugins version to v10.3
=> [port] Add plugins version #1123

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt
=> [Deps] Bump gl-native to v10.3.2

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt
=> [port] update gl-native (#1134)

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
=> Add changelog for v10.3

sdk-base/src/main/java/com/mapbox/maps/plugin/ConfigProperties.kt
Fixed an incorrect comment for LocationPuck3D
Moderately better documentation :smile: 
=> Fix erroneous comment

extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
This PR updates the generated file according to the latest style-spec.
=> Update the generated style docs

.circleci/config.yml
This PR applies sdkRegistryPublish in the release job, so it will generate PR in api-download automatically.
The generated test pr: https://github.com/mapbox/api-downloads/pull/1211
=> Apply RegistryPublish in release job

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
=> Update changelog and readme for 10.4.0-beta.1

sdk/build.gradle.kts
=> Update dokka syntax to fix build.

.circleci/config.yml
Bringing back nokia for instrumentation test.
=> Use pixel3 to fix instrumentation tests flaky device

CHANGELOG.md, plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt, plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/DefaultLocationProvider.kt, sdk/src/main/java/com/mapbox/maps/NativeObserver.kt, sdk/src/main/java/com/mapbox/maps/StyleObserver.kt, sdk/src/main/java/com/mapbox/maps/plugin/MapPluginRegistry.kt
This PR changes the `CopyOnWriteArrayList` to `CopyOnWriteArraySet` in the sdk to hold listeners. And avoid similar issues as in https://github.com/mapbox/mapbox-maps-android/issues/301 that duplicated subscription would be invoked multiple times.
=> Change CopyOnWriteArrayList to CopyOnWriteArraySet in the sdk to hold listeners.

CHANGELOG.md, plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt, plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/DefaultLocationProvider.kt, sdk/src/main/java/com/mapbox/maps/NativeObserver.kt, sdk/src/main/java/com/mapbox/maps/StyleObserver.kt, sdk/src/main/java/com/mapbox/maps/plugin/MapPluginRegistry.kt
Port of https://github.com/mapbox/mapbox-maps-android/pull/1183
This PR changes the CopyOnWriteArrayList to CopyOnWriteArraySet in the sdk to hold listeners. And avoid similar issues as in https://github.com/mapbox/mapbox-maps-android/issues/301 that duplicated subscription would be invoked multiple times.
=> Port of #1183 to v10.4

.circleci/config.yml
Porting the device changes to v10.4.
=> [port] Port ci changes to fix instrumentation tests device (#1180)

app/src/main/java/com/mapbox/maps/testapp/examples/viewport/AdvancedViewportGesturesExample.kt, app/src/main/java/com/mapbox/maps/testapp/examples/viewport/ViewportShowcaseActivity.kt, plugin-locationcomponent/README.md, plugin-viewport/README.md
This PR updates the docs to link to the user location guide.
=> Update doc to link to user location guide.

extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
=> Update version number in README.

CHANGELOG.md, sdk-base/api/metalava.txt, sdk-base/api/sdk-base.api, sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapCameraManagerDelegate.kt, sdk/api/metalava.txt, sdk/api/sdk.api, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt, sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Add `MapboxMap#coordinateBoundsForCameraUnwrapped` method for API consistency.
=> Expose `MapboxMap#coordinateBoundsForCameraUnwrapped`.

CHANGELOG.md, plugin-annotation/api/metalava.txt, plugin-annotation/api/plugin-annotation.api, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/ConvertUtils.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotation.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotation.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/ShadowProjection.java, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
Fix #1218 
`mapCameraManagerDelegate.coordinateForPixel` doesn't work well when 3D terrain is enabled.
This pr applies the center of Polygon and Polyline as the start point to calculate the dragging shift, uses Mercator coordinates to avoid distorting while dragging to poles. 
| <video src="https://user-images.githubusercontent.com/8577318/158313808-6cce6a85-f063-43fb-8ab2-b168f421ca21.mp4" width = 250/> | <video src="https://user-images.githubusercontent.com/8577318/158313628-168d0f10-e78b-4054-aee0-b38f328cd7c0.mp4" width = 250/> | …
=> Fix PolygonAnnotation and PolylineAnnotation distorted while dragging with 3D terrain

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
Add missing changelog entry for 3D rendering, update versions in README.
=> Add missing changelog entry for 3D rendering, update versions in README.

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
This PR adds change log entries for v10.4.0 release.
=> Update change log for v10.4.0 (#1235)

CHANGELOG.md, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPositionManager.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerRenderer.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationLayerRenderer.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationLayerWrapper.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerRenderer.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelSourceWrapper.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImplTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPositionManagerTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerRendererTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerWrapperTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationLayerWrapperTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerRendererTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapperTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelSourceWrapperTest.kt, sdk/src/main/java/com/mapbox/maps/Style.kt, sdk/src/main/java/com/mapbox/maps/StyleObserver.kt, sdk/src/test/java/com/mapbox/maps/StyleTest.kt
Treat `Style` object as invalid when new style is loaded. Accessing invalid object will log errors.
As a result, location component plugin was revisited to use correct (latest loaded) style.
Another plugin that is dependent on style change - annotation plugin - was not touched as it always uses latest style by calling `MapDelegateProvider.getStyle { }` and not storing direct references to any `Style` objects.
=> Mark style as invalid when new style is loaded and apply it to location component

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
=> bump gl-native to 10.4.2

CHANGELOG.md
=> port changelog 10.4.1

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, gradle.properties, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
=> Prepare 10.5.0-beta.1 changelog

CHANGELOG.md, plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt, sdk/src/androidTest/java/com/mapbox/maps/CameraAnimationsPluginTest.kt
CP for https://github.com/mapbox/mapbox-maps-android/pull/1271
=> V10.5 port: Fix latitude being NaN during flyTo

android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarCameraController.kt, android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarMapWidgets.kt, extension-androidauto/README.md, extension-androidauto/build.gradle.kts, extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/widgets/CompassWidget.kt, extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/widgets/LogoWidget.kt
This PR updates README.md, adds documentation to the widgets features that are only usable with Maps SDK v10.4.0 and above.
This PR also makes the GoogleCarApp library as an api dependency, so that users don't have to include the GoogleCarApp dependency themselves, users can still provide their own version of the GoogleCarApp library in their app, in that case, [Gradle dependency resolution](https://docs.gradle.org/current/userguide/dependency_resolution.html#sec:version-conflict) will take place.
> Gradle will consider all requested versions, wherever they appear in the dependency graph. Out of these versions, it will select the highest one.
PRs must be submitted under the terms of our Contributor …
=> [android-auto] Improve dependency management and documentation.

extension-androidauto/CHANGELOG.md
Adding first changelog for a new release track https://github.com/mapbox/mapbox-maps-android/pull/1246
changelog for `extension-androidauto-v0.1.0`
=> [Android Auto] Add changelog for extension-androidauto

CHANGELOG.md, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt, sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Port https://github.com/mapbox/mapbox-maps-android/pull/1226 to v10.5 release branch
=> Limit  to the bounds of MapView. (#1226)

.circleci/config.yml, scripts/ci-compatibility-start-pipeline.py, scripts/mobile-metrics-start-pipeline.py
Test to validate downstream job integration
=> [ci] integrate downstream validation job

.circleci/config.yml, scripts/mobile-metrics-start-pipeline.py
Partial revert of #1254, didn't pay attention to the changes and seem to have duplicated some on the wrong file.
=> [ci] revert unforseen changes to CI scripts

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
=> prepare v10.5.0-rc.1 changelog

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
=> [port] update readme and changelog (#1291)

CHANGELOG.md, sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
Some tasks scheduled by core with `MapClient.scheduleTask(task: Task)` may have been skipped when starting loading the map resulting in different visual bugs, most commonly tile not being loaded like in the screen below
This fix has been verified by running pixelmatch tests for 500 times and making sure that map looks as expected. Additionally GPU metrics were gathered making sure we do not regress in terms of performance.
FlyTo, 18 zoom
|metric|main branch| current fix| diff |
| ----- | ----- | ----- | ----- |
| jankyFrames                     | 47.0         | 45.5         | -3.1915%     |
| numberFrameDeadlineMissed       | 47.0         | 45.5         | -3.1915%     |
| jankyFramesPercent              | 3.735        | 3.61         | -3.3467%     |
| totalFramesRendered             | …
=> Fix some render tasks being skipped

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md, sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
port of https://github.com/mapbox/mapbox-maps-android/pull/1304
=> V10.4 port: Fix non render event scheduling

CHANGELOG.md
=> Port changelog for v10.4.3

CHANGELOG.md, app/src/main/java/com/mapbox/maps/testapp/examples/GlobeActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/HeatmapLayerActivity.kt, sdk-base/api/sdk-base.api, sdk-base/src/main/java/com/mapbox/maps/plugin/MapProjection.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapProjectionDelegate.kt, sdk/api/sdk.api, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt, sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
port https://github.com/mapbox/mapbox-maps-android/pull/1314
=> V10.5 port: Revert map projection functions

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt
=> Bump gl-native 10.5.0, common to 21.3.1

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt
Port of https://github.com/mapbox/mapbox-maps-android/pull/1315 to release branch
=> Port yds bump gl native

.circleci/config.yml
Currently, our docs generation job uses `main` branch of internal, which will not always be in sync with older releases (eg in case of patch releases), and ci will fail to generate docs. 
Since we now use the same release branch strategy, we can extract the branch from TAG and use it to trigger docs on specific internal branche. 
Note: this will always align us to use the same branch naming in main and internal repo.
=> [Docs] use internal branch to publish docs

.circleci/config.yml
port docs generation pr to v10.5
=> [port] use internal branch to publish docs (#1311)

CHANGELOG.md, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/Source.kt, sdk/src/main/java/com/mapbox/maps/Style.kt
port for https://github.com/mapbox/mapbox-maps-android/pull/1324
=> V10.5 port: Fix persistent layer update style change

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt
=> Bump gl-native to 10.5.1

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt
=> Port bump gl native 10.5.1

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
=> Add beta and rc entries to 10.5.0 changelog.

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
This is https://github.com/mapbox/mapbox-maps-android/pull/1329 port to the release branch.
Changelog for script :
=> PR #1329 port to release branch

extension-style/api/metalava.txt, sdk-base/api/metalava.txt, sdk/api/metalava.txt
It seems metalava API files are finally generated as expected, adding entries that were missed during some development time.
=> Update metalava API files

CHANGELOG.md, sdk-base/api/metalava.txt, sdk-base/src/main/java/com/mapbox/common/MapboxCommonLogger.kt, sdk-base/src/main/java/com/mapbox/maps/MapboxLogger.kt
Start using package-private non-deprecated Mapbox common logger. This does not bring any new functionality.
cc @mr1sunshine 
=> Use non-deprecated common logger

CHANGELOG.md, plugin-animation/api/metalava.txt, plugin-animation/api/plugin-animation.api, plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt
Expose camera factory methods that are used to build high-level animations.
This functionality should be used with caution as animators returned by those factory methods should be treated as low-level animators. Example how to obtain camera animators for e.g. `flyTo`:
```
val camera = mapView.camera as CameraAnimationsPluginImpl
val flyToAnimators = camera.cameraAnimationsFactory.getFlyTo(cameraOptions)
// work with those animators as with low-level animators
``` 
=> Expose camera animators factory methods

CHANGELOG.md, plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt, sdk/src/androidTest/java/com/mapbox/maps/CameraAnimationsPluginTest.kt
=> [Port] Fix latitude being NaN during flyTo

.circleci/config.yml
Remove useless step for CI task that just triggered internal build.
Also change environment to a `small` machine.
It will save about 30 seconds for each run + using smaller machine.
=> optimize verify internal CI task

CHANGELOG.md
=> Update change log for 10.4.4

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt, sdk-base/build.gradle.kts
Update gl-native to 10.6.0-beta.2.
=> update gl-native to v10.6.0-beta.2

CHANGELOG.md, app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/Terrain3DShowcaseActivity.kt, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/BaseStyleTest.kt, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/atmosphere/generated/AtmosphereTest.kt, extension-style/api/extension-style.api, extension-style/api/metalava.txt, extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/atmosphere/generated/Atmosphere.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/atmosphere/generated/AtmosphereExt.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/types/TypeDSLs.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/atmosphere/generated/AtmosphereTest.kt, sdk-base/api/metalava.txt, sdk-base/api/sdk-base.api, sdk-base/src/main/java/com/mapbox/maps/extension/style/StyleContract.kt, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt, sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
Introduce Atmosphere API.
It could be applied either using Style DSL  during runtime styling e.g.:
```kotlin
+atmosphere {
starIntensity(0.5)
color(Color.CYAN)
}
```
or build atmosphere object and set it to `Style` directly:
```kotlin
style.setAtmosphere(
atmosphere {
highColor("red")
}
)
```
| Fog | Atmosphere |
| <img src="https://user-images.githubusercontent.com/15800566/168617344-e2e71e3d-9a56-40d7-90b4-6880efb20d01.jpg" width = 250/> | <img src="https://user-images.githubusercontent.com/15800566/168617249-1fada145-08f7-4c8b-bd37-83d6f2e9eacd.jpg" width = 250/> | …
=> Add style atmosphere support

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt
=> [Deps] bump gl-native v10.6.0-beta.3

sdk/src/main/java/com/mapbox/maps/MapController.kt, sdk/src/main/java/com/mapbox/maps/MapProvider.kt, sdk/src/main/java/com/mapbox/maps/NativeMapProvider.java
This PR rewrites our map provider implementation.
=> [provider] rework map providers

CHANGELOG.md, app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt, app/src/main/res/menu/menu_location_component.xml, app/src/main/res/values/strings.xml, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
This PR add mercator scale to 3D location puck.
| Before(mercator) | After(mercator) |
| <video src="https://user-images.githubusercontent.com/2764714/169026416-a24df62b-386e-4998-b33d-ab876a5305cf.mp4" width = 250/> | <video src="https://user-images.githubusercontent.com/2764714/169026829-f0be6e02-75a4-4175-a81e-971241ceb3b6.mp4" width = 250/> |
| Before(globe) | After(globe) |
| <video src="https://user-images.githubusercontent.com/2764714/169027013-49e2295e-7320-474c-bc13-2f2bc8543dbf.mp4" width = 250/> | <video src="https://user-images.githubusercontent.com/2764714/169027153-b277dded-8916-42a1-b133-c93063455a96.mp4" width = 250/> |
PRs must be submitted under …
=> Add mercator scale to 3D location puck.

build.gradle.kts, buildSrc/src/main/kotlin/Project.kt, compose/build.gradle, extension-androidauto/build.gradle.kts, extension-localization/build.gradle.kts, extension-style/build.gradle.kts, module-telemetry/build.gradle.kts, plugin-animation/build.gradle.kts, plugin-annotation/build.gradle.kts, plugin-attribution/build.gradle.kts, plugin-compass/build.gradle.kts, plugin-gestures/build.gradle.kts, plugin-lifecycle/build.gradle.kts, plugin-locationcomponent/build.gradle.kts, plugin-logo/build.gradle.kts, plugin-overlay/build.gradle.kts, plugin-scalebar/build.gradle.kts, plugin-viewport/build.gradle.kts, sdk-base/build.gradle.kts, sdk/build.gradle.kts, settings.gradle.kts
- update dokka to v1.5.31.
- Remove jcenter
=> [docs] update dokka to 1.5.31 and remove jcenter

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, gradle.properties, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md, sdk/api/metalava.txt
=> Prepare for v10.6.0-beta.1 release

app/src/main/AndroidManifest.xml, app/src/main/java/com/mapbox/maps/testapp/examples/DebugModeActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/GesturesActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/camera/RestrictBoundsActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/localization/LocalizationActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/style/TileJsonActivity.kt
Back button was not working in some activities since we hide it via onOptionsItemSelected returning true
=> Fix back button not working in some activities.

CHANGELOG.md, plugin-attribution/src/main/res/values/strings.xml, plugin-locationcomponent/src/main/res/values/strings.xml
| <img src="https://user-images.githubusercontent.com/1478430/169321018-27d333fa-a81a-4384-8764-894c7bbf6a33.png" width = 250/> | <img src="https://user-images.githubusercontent.com/1478430/169321394-6705bb79-fadb-4900-be8d-1135a467e524.png" width = 250/> |
=> Update SDK name in attribution dialog

CHANGELOG.md, plugin-attribution/src/main/res/values/strings.xml, plugin-locationcomponent/src/main/res/values/strings.xml
Port for https://github.com/mapbox/mapbox-maps-android/pull/1375
=> V10.6 port: Update attribution SDK name

CHANGELOG.md, app/src/main/AndroidManifest.xml, app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/ModelLayerActivity.kt, app/src/main/res/values/example_descriptions.xml, app/src/main/res/values/example_titles.xml, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/ModelLayerTest.kt, extension-style/api/extension-style.api, extension-style/api/metalava.txt, extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/LayerExt.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/ModelLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/properties/generated/Property.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/model/ModelExt.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/model/ModelExtensionImpl.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/ModelLayerTest.kt, sdk-base/api/metalava.txt, sdk-base/api/sdk-base.api, sdk-base/src/main/java/com/mapbox/maps/extension/style/StyleContract.kt, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
This PR ports https://github.com/mapbox/mapbox-maps-android/pull/1369 to v10.6 release branch.
=> Port ModelLayer to v10.6 release branch

extension-style/src/main/java/com/mapbox/maps/extension/style/atmosphere/generated/Atmosphere.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/BackgroundLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/CircleLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/HeatmapLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/HillshadeLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LineLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LocationIndicatorLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/ModelLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/RasterLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SkyLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SymbolLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/Light.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/projection/generated/Projection.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/Terrain.kt
This PR improves the API documentation to use the doc inside style spec for all the getter/setter functions.
=> [docs] Improve style extension documentation.

extension-style/src/main/java/com/mapbox/maps/extension/style/atmosphere/generated/Atmosphere.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/BackgroundLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/CircleLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/HeatmapLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/HillshadeLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LineLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LocationIndicatorLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/ModelLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/RasterLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SkyLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SymbolLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/Light.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/projection/generated/Projection.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/Terrain.kt
This PR ports https://github.com/mapbox/mapbox-maps-android/pull/1383 to v10.6 release branch.
=> Port documentation improvements to Style API

extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
=> Update md files to use v10.6.0-beta.2

sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
Correct argument values for `checkNativeMap` in  `cameraForCoordinates` method.
=> fix checkNativeMap function call for cameraForCoordinates

extension-style/src/main/java/com/mapbox/maps/extension/style/layers/Layer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterDemSource.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterSource.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/VectorSource.kt
Port for https://github.com/mapbox/mapbox-maps-android/pull/1394
=> V10.6 port: some fixes

CHANGELOG.md, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
Optimise the frequency to update location layer's visibility, to avoid unnecessary gl-native calls.
=> Optimise the frequency to update location layer's visibility.

CHANGELOG.md
=> Clean up changelog after 10.6.0-rc.1

CHANGELOG.md, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
Fix the delay in the first appearance of the location puck.
| <video src="https://user-images.githubusercontent.com/2764714/171624231-900d8503-ef13-4518-a783-b2169cddf131.mp4" width = 250/> | <video src="https://user-images.githubusercontent.com/2764714/171624291-f3abe491-3eba-4ca3-9158-5c5bd9be93cb.mp4" width = 250/> |
=> Fix the delay in the first appearance of the location puck.

CHANGELOG.md, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
This PR ports https://github.com/mapbox/mapbox-maps-android/pull/1399 and https://github.com/mapbox/mapbox-maps-android/pull/1403 to the v10.6 release branch.
=> Port Fix the delay in the first appearance of the location puck. 

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
Update latest maps sdk version in READMEs and updated change log for v10.6.0 release.
=> Update docs for v10.6.0 release.

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
This PR ports README and CHANGELOG updates from v10.6 release branch.
=> Update docs for v10.6.0 release. (#1435)

plugin-attribution/src/main/res/values/strings.xml, plugin-locationcomponent/src/main/res/values/dimens.xml, plugin-locationcomponent/src/main/res/values/strings.xml, plugin-logo/src/main/res/values/strings.xml, sdk-base/src/main/res/values/strings.xml, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt, sdk/src/main/java/com/mapbox/maps/attribution/AttributionParser.kt, sdk/src/main/res/values/strings.xml
remove some unused resources and update doc.
=> [lint] remove unused resources and fix some docs MAPSAND-93

CHANGELOG.md, sdk/api/metalava.txt, sdk/api/sdk.api, sdk/build.gradle.kts, sdk/src/androidTest/java/com/mapbox/maps/renderer/egl/RendererSetupTest.kt, sdk/src/main/java/com/mapbox/maps/MapControllable.kt, sdk/src/main/java/com/mapbox/maps/MapController.kt, sdk/src/main/java/com/mapbox/maps/MapSurface.kt, sdk/src/main/java/com/mapbox/maps/MapView.kt, sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt, sdk/src/main/java/com/mapbox/maps/renderer/RendererError.kt, sdk/src/main/java/com/mapbox/maps/renderer/RendererSetupErrorListener.kt, sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLConfigChooser.kt, sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLCore.kt, sdk/src/test/java/com/mapbox/maps/EqualsHashCodeTest.kt, sdk/src/test/java/com/mapbox/maps/MapViewTest.kt
Introduce `addRendererSetupErrorListener`/`removeRendererSetupErrorListener` methods for `MapView` and `MapSurface` to listen to renderer setup errors and give opportunity to control some edge cases.
This could be useful to use this API and listen to `RendererError.OutOfMemory` error when initiating the `MapView`. Then, in case of no resources, it could be an option try cleaning up the memory for your app and re-create the `MapView`. Sample use-case was added as the test in `RendererSetupTest`.
=> Introduce API to control errors during renderer creation

sdk/src/main/java/com/mapbox/maps/renderer/RendererError.kt
Add missing API doc for eglErrorCode, which blocks uploading snapshots on main branch.
=> Add missing API doc for eglErrorCode.

.circleci/config.yml, scripts/kdoc-validate.sh
Fix verify-docs CI scripts, increase CI container size for flaky bots.
=> Fix verify-docs CI scripts, increase CI container size for flaky bots.

CHANGELOG.md, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/atmosphere/generated/AtmosphereTest.kt, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/terrain/generated/TerrainTest.kt, extension-style/api/extension-style.api, extension-style/api/metalava.txt, extension-style/src/main/java/com/mapbox/maps/extension/style/atmosphere/generated/Atmosphere.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/Terrain.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/atmosphere/generated/AtmosphereTest.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/terrain/generated/TerrainTest.kt
Following properties have been added:
1. Atmosphere:
- colorTransition
- highColorTransition
- horizonBlendTransition
- rangeTransition
- spaceColorTransition
- starIntensityTransition
2. Terrain:
- exaggerationTransition
=> Add missing transition properties for atmosphere and terrain

CHANGELOG.md, app/src/main/java/com/mapbox/maps/testapp/examples/RuntimeStylingActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/java/RuntimeStylingJavaActivity.java, app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/FillExtrusionActivity.kt, app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/Terrain3DShowcaseActivity.kt, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/light/generated/LightTest.kt, extension-style/api/extension-style.api, extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/Light.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/light/generated/LightTest.kt
Added experimental shadow apis. 
=> [shadow-api] Add experimental shadow api MAPSAND-165

CHANGELOG.md, app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PointAnnotationManagerAndroidTest.kt, app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/FillExtrusionActivity.kt, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/FillExtrusionLayerTest.kt, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/SymbolLayerTest.kt, extension-style/api/extension-style.api, extension-style/api/metalava.txt, extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/dsl/generated/ExpressionDsl.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/generated/Expression.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/HeatmapLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SymbolLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/properties/generated/Property.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayerTest.kt, plugin-annotation/api/metalava.txt, plugin-annotation/api/plugin-annotation.api, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotation.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManager.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationOptions.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
* Updated latest API docs from style spec.
* Introduce `FillExtrusionLayer.fillExtrusionAmbientOcclusionIntensity` and `FillExtrusionLayer.fillExtrusionAmbientOcclusionRadius` properties for FillExtrusionLayer.
* Introduce `PointAnnotation.textLineHeight` and deprecated `PointAnnotationManager.textLineHeight`, as `text-line-height` is data-driven property now.
| Without fill-extrusion-ambient-occlusion | With fill-extrusion-ambient-occlusion |
| <img src="https://user-images.githubusercontent.com/2764714/175900858-28d94530-c25f-4f71-a67f-873c204c300d.png" width = 250/> | <img src="https://user-images.githubusercontent.com/2764714/175900836-4aefd8c4-fbc8-4e5e-9608-a5a081af7437.png" width = 250/> |
Fixes: < Link to related issues that will be fixed by this pull request, if …
=> Update style spec docs and introduce fill-extrusion-ambient-occlusion.

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, gradle.properties, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
=> Update docs for v10.7.0-beta.1 release

extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/ModelLayerTest.kt
Fix modelIdAsExpression instrumentation test.
=> Fix modelIdAsExpression instrumentation test.

CHANGELOG.md, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/expressions/ExpressionTest.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/generated/Expression.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/utils/TypeUtils.kt
This PR ports #1444 to v10.6 release branch.
=> Fix using arrays inside match expression dsl - MAPSAND-226 (#1444)

CHANGELOG.md, app/src/main/java/com/mapbox/maps/testapp/examples/SimulateNavigationRouteActivity.kt, app/src/main/java/com/mapbox/maps/testapp/utils/NavigationSimulator.kt, app/src/main/java/com/mapbox/maps/testapp/utils/SimulateRouteLocationProvider.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/DefaultLocationProvider.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/Evaluators.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/DefaultLocationProviderTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerWrapperTest.kt
Fixes https://github.com/mapbox/mapbox-maps-android/issues/1320
This PR supports altitude interpolation in location component, and pass through GPS altitude information from the DefaultLocationProvider.
This PR also improves the performance of the navigation simulator, by not calculating the progress on every frame and use interpolated value instead. 
=> Support altitude interpolation in location component. - MAPSAND-291

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt
=> Port mme 8.1.5

CHANGELOG.md, app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/ModelLayerTest.kt, extension-style/api/extension-style.api, extension-style/api/metalava.txt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/ModelLayer.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/ModelLayerTest.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LayerSourceProvider.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapper.kt, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentAttributeParser.kt, plugin-locationcomponent/src/main/res-public/values/public.xml, plugin-locationcomponent/src/main/res/values/attrs.xml, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LayerSourceProviderTest.kt, plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapperTest.kt, sdk-base/api/metalava.txt, sdk-base/api/sdk-base.api, sdk-base/src/main/java/com/mapbox/maps/plugin/ConfigProperties.kt
=> [Port] Add modelCastShadow property to model layer

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
=> Bump gl native 10.6.2, MME 8.1.5

app/src/main/AndroidManifest.xml, app/src/main/java/com/mapbox/maps/testapp/examples/style/ThirdPartyVectorSourceActivity.kt, app/src/main/res/values/example_descriptions.xml, app/src/main/res/values/example_titles.xml
Example conform to https://docs.mapbox.com/mapbox-gl-js/example/third-party/
=> Add third party vector source example

.github/CODEOWNERS
This PR adds Maps SDK iOS team as the code owner of the public api files. Any public API changes should be reviewed by iOS team to make us better aligned across platform.
=> Add Maps SDK iOS team as the code owner of the public api files.

extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/projection/generated/Projection.kt
=> Add docs about behaviour when globe projection is not supported

extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/projection/generated/Projection.kt
Port for https://github.com/mapbox/mapbox-maps-android/pull/1523
=> V10.7 port: improve fallback of terrian globe rendering failures

CHANGELOG.md, sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt, sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
This is #1527 port to the release branch.
=> PR #1527 port to release branch

CHANGELOG.md, sdk/src/main/java/com/mapbox/maps/StyleObserver.kt, sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt
This is #1532 port to the release branch.
=> PR #1532 port to release branch

sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapCameraManagerDelegate.kt, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
Update API reference docs to include not supported for globe projection.
The engine will return a no-op result.
=> [camera] update api reference docs to include not supported for globe

CHANGELOG.md, plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt, plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt
For the shove gesture (changing the pitch) we should always explicitly use screen center as an anchor point.
| <video src="https://user-images.githubusercontent.com/15800566/182842886-9faaaf3a-cde9-4e8d-8798-d5992d1fa544.mp4" width = 250/> | <video src="https://user-images.githubusercontent.com/15800566/182842976-44399725-abff-4051-add6-478da58b6159.mp4" width = 250/> |
=> Fix camera flying away when pitching

extension-androidauto/CHANGELOG.md
* Destroy previous surface when new surface becomes available. This adds better support for `androidx.car.app:app-automotive`. ([#1509](https://github.com/mapbox/mapbox-maps-android/pull/1509))
* Android Auto car library `androidx.car.app:app:1.1.+`
* Supports any version of Mapbox Maps 10.+
=> [Android Auto] Release changelog 0.2.0

.circleci/config.yml
Fix the git release tag matching for continuous deployment.
=> Fix the git release tag matching for CI/CD.

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt
=> Bump gl-native to v10.8.0-beta.1, common to v23.0.0-beta.1

sdk/api/metalava.txt
Update api file after https://github.com/mapbox/mapbox-maps-android/pull/1477
=> Update metalava file with new param name

plugin-locationcomponent/src/main/res-public/values/public.xml, plugin-locationcomponent/src/main/res/values/attrs.xml, sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettings.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsBase.kt, sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsInterface.kt
Fixing docs generated for location component.
=> [docs] update location component docs

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt
=> Bump gl-native 10.8.0-beta.2

CHANGELOG.md, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LineLayer.kt, plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManager.kt
Update the generated doc to match style spec.
Also moved incorrectly rebased changelog entries to the correct section.
=> Update the generated doc to match style spec.

CHANGELOG.md, extension-localization/README.md, extension-style/README.md, gradle.properties, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
=> Update changelog for 10.8.0-beta.1

.circleci/config.yml, scripts/ci-e2e-job-trigger-checker.sh
=> fix e2e script path

CHANGELOG.md, sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt, sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLCore.kt
Port of https://github.com/mapbox/mapbox-maps-android/pull/1589
=> V10.8 port: Try recreate EGL surface when it throws exception

scripts/update-android-docs.sh
=> [Port]update script for generate docs (#1586)

CHANGELOG.md, sdk/src/main/java/com/mapbox/maps/renderer/MapboxWidgetRenderer.kt
Port of https://github.com/mapbox/mapbox-maps-android/pull/1597
=> V10.8 port: fix concurrent modification exception when using widgets

.circleci/config.yml, package.json
=> Notify private repo about main update [MAPSAND-374]

android-auto-app/build.gradle.kts, android-auto-app/src/main/AndroidManifest.xml, android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/app/MainActivity.kt, android-auto-app/src/main/res/layout/activity_main.xml, android-auto-app/src/main/res/values/themes.xml
This is updating the `android-auto-app` example to have an Activity. You do not have to open it to run the app, but this helps reproduce issues like this one https://github.com/mapbox/mapbox-maps-android/issues/1413
=> [Android Auto] Add activity to android auto app

.circleci/config.yml
Remove useless download dependencies command
Save cache only once 
Set executor class as `xlarge`
=> refactor gradle-cache CI commands

app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/infowindow/MarkerManager.kt
Changing view visibility from `VISIBLE` to `INVISIBLE` does not actually trigger `ViewTreeObserver.OnGlobalLayoutListener.onGlobalLayout()` as the view still remains in the layout. Because of that handling view annotation visibility does not work and info window example was broken.
Marking view as `GONE` when we want to hide it fixes the issue.
=> Fix info window activity example

app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/infowindow/MarkerManager.kt
Port for https://github.com/mapbox/mapbox-maps-android/pull/1613
=> v10.8 port: fix info window activity example

app/src/main/java/com/mapbox/maps/testapp/examples/InsetMapActivity.kt
- Fixed crash when `insetMap` is not initialised.
- Update insetFragment to set style on configuration change.
=> [example] fix inset activity MAPSMBL-156

app/src/main/java/com/mapbox/maps/testapp/examples/InsetMapActivity.kt
=> port fix inset activity (#1614)

package-lock.json
Bumps [ejs](https://github.com/mde/ejs) from 2.7.4 to 3.1.7.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/mde/ejs/releases">ejs's releases</a>.</em></p>
<blockquote>
<h2>v3.1.7</h2>
<p>Version 3.1.7</p>
<h2>v3.1.6</h2>
<p>Version 3.1.6</p>
<h2>v3.1.5</h2>
<p>Version 3.1.5</p>
<h2>v3.0.2</h2>
<p>No release notes provided.</p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a href="https://github.com/mde/ejs/blob/main/CHANGELOG.md">ejs's changelog</a>.</em></p>
<blockquote>
<h2>v3.0.1: 2019-11-23</h2>
<ul>
<li>Removed require.extensions (<a href="https://github.com/mde"><code>@​mde</code></a>)</li>
<li>Removed legacy preprocessor include (<a href="https://github.com/mde"><code>@​mde</code></a>)</li> …
=> Bump ejs from 2.7.4 to 3.1.7

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
This PR ports https://github.com/mapbox/mapbox-maps-android/pull/1623 to v10.8 release branch.
=> [port] Bump gl-native to 10.8-rc.1 (#1623)

CHANGELOG.md
=> Add release date to v10.8.0-rc.1 change log.

sdk/src/main/java/com/mapbox/maps/Style.kt
While reading documentation for [Style](https://docs.mapbox.com/android/maps/api/10.7.0/mapbox-maps-android/com.mapbox.maps/-style/), I noticed that the docs could use some cleaning.
N/A
=> Small improvements on `Style` docs

DEVELOPING.md
There was an extra \` in the `Public API changes tracking` section of the `DEVELOPING.md` file. That caused some issues in the formatting.
N/A
=> Small format fix to DEVELOPING.md

CHANGELOG.md
Port change log date from release branch.
=> Add release date to changelog. (#1627)

scripts/ci-circleci-start-pipeline.py
Add converter from python boolean argument to proper pipeline value
=> fix boolean flag parser

.circleci/config.yml, extension-localization/gradle.properties, plugin-lifecycle/gradle.properties, plugin-overlay/gradle.properties, scripts/ci-circleci-start-pipeline.py
- Added notifications about release branch updates
- Changed python script to send single relevant parameter with the merged branch name
=> Notify about release branch update MAPSMBL-152

scripts/ci-circleci-start-pipeline.py
port https://github.com/mapbox/mapbox-maps-android/pull/1639
=> port fix string flag

extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayer.kt
Updated doc with the latest changes from stylegen
N/A
=> Updated docs fill extrusion layer

CHANGELOG.md, plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt, plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt
In https://github.com/mapbox/mapbox-maps-android/pull/1645 gesture library was bumped but  MotionEvents need to be marked nullable to fix the original issue #1019. 
=> Mark motion events nullable.

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt, sdk-base/src/main/java/com/mapbox/common/MapboxMapsAndroidLogger.kt, sdk-base/src/main/java/com/mapbox/maps/MapboxLogger.kt
* Add experimental line-edge-clip property
* Introduce `location-indicator-opacity` to location indicator layer that allows to control layer opacity.
* Enable asyncronous tile uploader by default to improve animation performance
* Vector tiles without symbols are not hold for fade-out animation so that less amount of vector tiles are managed at a time
* Introduce maps Version API
* Added `line-border-width` and `line-border-color` experimental line layer properties.
* Fix pixel flickering between tiles on darker styles in globe view.
* Fix incorrect shading of rounded corners in fill extrusions when ambient occlusion and/or shadow is enabled.
* Fix shadows when the light radial coordinate is zero
* Location indicator layer is occluded by terrain to align rendering behavior with other …
=> Bump gl-native to v10.9.0-beta.1, common to v23.1.0-beta.1.

scripts/update-android-docs.sh
Update android-docs will be executed by the Release train app. This approach is better than the current one because the app checks the version in https://docs.mapbox.com/android/maps/api/VERSION_NAME before creating a PR in the android-docs. It guarantees green checks and easy merge.
=> Remove update android docs from update script

CHANGELOG.md, app/src/main/java/com/mapbox/maps/testapp/utils/NavigationSimulator.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/properties/PropertyValue.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/utils/TypeUtils.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/utils/TypeUtilsTest.kt
Throw exception when constructing `Value` with not a finite number, so we get meaningful crash stacktrace early.
According to [JSON](https://www.json.org/json-en.html)  NAN isn't part of the JSON specification, and it will cause issues when we pass the Double.NaN to gl-native, where we serialise it to a JSON string.
=> Throw exception when constructing Value with NaN or infinite numbers.

android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/testing/CarJavaInterfaceChecker.java, extension-androidauto/CHANGELOG.md, extension-androidauto/api/extension-androidauto.api, extension-androidauto/api/metalava.txt, extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceOwner.kt, extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMap.kt, extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapGestureHandler.java, extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapObserver.java, extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/MapboxCarMapTest.kt
Moving the `MapboxCarMapObserver` to a java interface so that functions may be added in the future https://github.com/mapbox/mapbox-maps-android/pull/1670
Adding the `onStableAreaChanged` in case there are usages for it.
Improved the javadocs as they are slightly different in java files.
=> [Android Auto] Add stable area changed callback

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt
Bump common sdk to v23.1.0-beta.2.
=> Bump common sdk to v23.1.0-beta.2.

CHANGELOG.md, sdk/src/main/java/com/mapbox/maps/MapController.kt, sdk/src/main/java/com/mapbox/maps/MapProvider.kt
Cherry pick `[telem] provide telemetry module as a singleton`
=> Provide telemetry module as a singleton (#1695)

CHANGELOG.md, app/src/main/java/com/mapbox/maps/testapp/utils/NavigationSimulator.kt, extension-localization/README.md, extension-style/README.md, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/properties/PropertyValue.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/utils/TypeUtils.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/utils/TypeUtilsTest.kt, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-overlay/README.md, plugin-scalebar/README.md, plugin-viewport/README.md, sdk/src/main/java/com/mapbox/maps/MapController.kt, sdk/src/main/java/com/mapbox/maps/MapProvider.kt, sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
Port https://github.com/mapbox/mapbox-maps-android/pull/1658, https://github.com/mapbox/mapbox-maps-android/pull/1681, https://github.com/mapbox/mapbox-maps-android/pull/1695 to v10.8 release branch.
=> Port fixes for v10.8.1 release.

CHANGELOG.md
Add release date for v10.8.1 release
=> Add release date for v10.8.1 release.

.circleci/config.yml, android-auto-app/build.gradle.kts, app/build.gradle.kts, build.gradle.kts, buildSrc/src/main/kotlin/Project.kt, compose-app/build.gradle.kts, extension-androidauto/build.gradle.kts, extension-localization/build.gradle.kts, extension-style-app/build.gradle.kts, extension-style/build.gradle.kts, gradle/dependency-updates.gradle, mapbox-lint/build.gradle, module-telemetry/build.gradle.kts, plugin-animation/build.gradle.kts, plugin-annotation/build.gradle.kts, plugin-attribution/build.gradle.kts, plugin-compass/build.gradle.kts, plugin-gestures/build.gradle.kts, plugin-lifecycle/build.gradle.kts, plugin-locationcomponent/build.gradle.kts, plugin-logo/build.gradle.kts, plugin-overlay/build.gradle.kts, plugin-scalebar/build.gradle.kts, plugin-viewport/build.gradle.kts, scripts/merge-gradle-dependency-output.py, sdk-base/build.gradle.kts, sdk/build.gradle.kts
With our dependency organisation Android Studio can't highlight new dependencies. This plugin allows us to check all of them and print in one file.
CI will run this plugin automatically once a week.
=> add gradle dependency checker MAPSAND-341

CHANGELOG.md
Update change log for v10.8.1 release.
=> Update change log for v10.8.1 release.

gradle/script-git-version.gradle
Use latest tag names to filter tags size in git version script.
=> fix git version script to include latest tags

gradle/script-git-version.gradle
* fix git version script to include latest tags
* Update gradle/script-git-version.gradle
=> [port] git version script fix

.circleci/config.yml
This PR makes the release branch matching more strict.
=> [ci] Make release branch name matching more strict. [MAPSAND-509]

CHANGELOG.md, sdk/src/androidTest/java/com/mapbox/maps/StyleLoadTest.kt, sdk/src/main/java/com/mapbox/maps/MapboxMap.kt, sdk/src/main/java/com/mapbox/maps/StyleObserver.kt, sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt, sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt
This is #1717 port to the release branch.
=> PR #1717 port to release branch

CHANGELOG.md, sdk/src/main/java/com/mapbox/maps/MapController.kt, sdk/src/main/java/com/mapbox/maps/renderer/MapboxWidgetRenderer.kt, sdk/src/main/java/com/mapbox/maps/renderer/widget/BitmapWidget.kt, sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
Port for https://github.com/mapbox/mapbox-maps-android/pull/1708
=> Port add widget fix

metalava/README.md, plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentExt.kt
=> Fix typo location component and README

.circleci/config.yml, build.gradle.kts, buildSrc/src/main/kotlin/Project.kt
Added Mapbox snapshot maven repository.
Filter it out if CI is building a release or the target branch for the PR that triggered the CI build is a release one.
N/A
=> Add Mapbox snapshot Maven repository configuration

.circleci/config.yml
Replaced missing device, added device model names to the description
=> Replace device that is missing on firebase.

extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/BackgroundLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/CircleLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/HeatmapLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/HillshadeLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LineLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LocationIndicatorLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/RasterLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SkyLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SymbolLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/ImageSource.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterDemSource.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterSource.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/VectorSource.kt
=> [docs] link default property to style property getter/setter docs.

extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/BackgroundLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/CircleLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/HeatmapLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/HillshadeLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LineLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LocationIndicatorLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/RasterLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SkyLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SymbolLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/ImageSource.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterDemSource.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterSource.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/VectorSource.kt
=> [Port] default property docs link

.circleci/config.yml, android-auto-app/build.gradle.kts, app/build.gradle.kts, build.gradle.kts, buildSrc/src/main/kotlin/Project.kt, compose-app/build.gradle.kts, extension-androidauto/build.gradle.kts, extension-localization/build.gradle.kts, extension-style-app/build.gradle.kts, extension-style/build.gradle.kts, gradle/dependency-updates.gradle, mapbox-lint/build.gradle, module-telemetry/build.gradle.kts, plugin-animation/build.gradle.kts, plugin-annotation/build.gradle.kts, plugin-attribution/build.gradle.kts, plugin-compass/build.gradle.kts, plugin-gestures/build.gradle.kts, plugin-lifecycle/build.gradle.kts, plugin-locationcomponent/build.gradle.kts, plugin-logo/build.gradle.kts, plugin-overlay/build.gradle.kts, plugin-scalebar/build.gradle.kts, plugin-viewport/build.gradle.kts, scripts/merge-gradle-dependency-output.py, sdk-base/build.gradle.kts, sdk/build.gradle.kts
Port for https://github.com/mapbox/mapbox-maps-android/pull/1637
=> [port] gradle dependency checker

scripts/java-api-check-all.sh, scripts/java-api-check.sh
Fixed revapi check both for release and main branches. Currently it 
- fails on PRs to release branch picking incorrect `android-v10.6.0` release - [the build](https://app.circleci.com/pipelines/github/mapbox/mapbox-maps-android/6793/workflows/aad95f19-6525-40e9-b090-44692f009e5f/jobs/57080)
```
$1:
$2:./plugin-compass/build/outputs/aar/plugin-compass-release.aar
$3:compass
$4:android-v10.6.0
Path to previous version of aar is not set, using 10.6.0
aar path is: s3://mapbox-api-downloads-production/v2/mobile-maps-android-compass/releases/android/10.6.0/maven/maps-compass-10.6.0.aar, checking file
```
- succeedes without any actual comparison on PRs to the main branch - [the build](https://app.circleci.com/pipelines/github/mapbox/mapbox-maps-android/6781/workflows/50301da3-815e-4f4a-9fa1-c33 …
=> Fix revapi release check

scripts/java-api-check-all.sh, scripts/java-api-check.sh
Fixed revapi check both for release and main branches. Currently it 
- fails on PRs to release branch picking incorrect `android-v10.6.0` release - [the build](https://app.circleci.com/pipelines/github/mapbox/mapbox-maps-android/6793/workflows/aad95f19-6525-40e9-b090-44692f009e5f/jobs/57080)
```
$1:
$2:./plugin-compass/build/outputs/aar/plugin-compass-release.aar
$3:compass
$4:android-v10.6.0
Path to previous version of aar is not set, using 10.6.0
aar path is: s3://mapbox-api-downloads-production/v2/mobile-maps-android-compass/releases/android/10.6.0/maven/maps-compass-10.6.0.aar, checking file
```
- succeedes without any actual comparison on PRs to the main branch - [the build](https://app.circleci.com/pipelines/github/mapbox/mapbox-maps-android/6781/workflows/50301da3-815e-4f4a-9fa1-c33 …
=> Fix revapi release branch

CHANGELOG.md, sdk/api/metalava.txt, sdk/api/sdk.api, sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt, sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotationManager.kt, sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerTest.kt
Introduce view annotation `ViewAnnotationManager.annotations` API to access list of added view annotations.
=> [viewannotation] Introduce get annotations list api MAPSAND-463

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt, sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt, sdk/src/test/java/com/mapbox/maps/NativeMapTest.kt
=> bump gl-native to 10.10.0-beta.1, common to 23.2.0-beta.1

extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SkyLayer.kt
=> Add sky layer deprecation docs

app/src/main/java/com/mapbox/maps/testapp/examples/java/DSLStylingJavaActivity.java
Show image source + raster layer in Java integration example. Previously it was not working.
=> Fix Java example to show image source with raster layer

extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/SkyLayer.kt
Port https://github.com/mapbox/mapbox-maps-android/pull/1806
=> Port: Add sky layer deprecation docs

LICENSE.md, buildSrc/src/main/kotlin/Project.kt
Bump gradle-license-plugin to v0.9.0
=> [deps] bump license plugin to v0.9.0

CHANGELOG.md
=> port changelog v10.9.1

extension-androidauto/CHANGELOG.md
This is essentially a `1.0.0` preview. Creating a separate release as we are removing experimental annotations from the [navigation sdk](http://github.com/mapbox/mapbox-navigation-android)
=> Add changelog extension-androidauto-v0.4.0

.circleci/config.yml
Update [num-flaky-test-attempts](https://cloud.google.com/sdk/gcloud/reference/beta/firebase/test/android/run#--num-flaky-test-attempts) value for our tests. Right now after one flaky test we rerun whole shard test list.
I guess it's enough to rerun flaky test only once.
=> update num-flaky-test-attempts for firebase device lab

module-telemetry/build.gradle.kts, module-telemetry/src/main/java/com/mapbox/maps/module/telemetry/MapLoadEvent.kt, module-telemetry/src/main/java/com/mapbox/maps/module/telemetry/MapTelemetryImpl.kt, module-telemetry/src/test/java/com/mapbox/maps/module/telemetry/MapEventFactoryTest.kt, module-telemetry/src/test/java/com/mapbox/maps/module/telemetry/MapTelemetryTest.kt, sdk-base/build.gradle.kts, sdk/src/main/java/com/mapbox/maps/MapController.kt, sdk/src/main/java/com/mapbox/maps/MapProvider.kt, sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt, sdk/src/test/java/com/mapbox/maps/shadows/ShadowEventsService.kt, sdk/src/test/java/com/mapbox/maps/shadows/ShadowTelemetryService.kt
This PR ports https://github.com/mapbox/mapbox-maps-android/pull/1801 and https://github.com/mapbox/mapbox-maps-android/pull/1820 to v10.10 release branch.
=> [port] Change to queued events and flush events on map controller's stop lifecycle event.

buildSrc/src/main/kotlin/Project.kt, mapbox-lint/src/main/java/com/mapbox/maps/lint/LifecycleIssueRegistry.kt
For reference http://googlesamples.github.io/android-custom-lint-rules/api-guide.md.html
> The vendor property is new as of 7.0, and gives lint authors a way to indicate where the lint check came from. When users use lint, they're running hundreds and hundreds of checks, and sometimes it's not clear who to contact with requests or bug reports. When a vendor has been specified, lint will include this information in error output and reports.
=> [mapbox-lint] Add vendor configuration to LifecycleIssueRegistry.

CHANGELOG.md, sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt, sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerTest.kt
This is #1831 port to the release branch.
=> PR #1831 port to release branch

CHANGELOG.md, extension-style/api/extension-style.api, extension-style/api/metalava.txt, extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/atmosphere/generated/AtmosphereExt.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/atmosphere/generated/AtmosphereTest.kt
Add API for removing atmosphere:
```
mapboxMap.getStyle()?.removeAtmosphere()
```
https://user-images.githubusercontent.com/4403635/201973390-ad615f4c-ea8e-4c9a-b336-1c20f0087993.mp4
=> add remove atmosphere api MAPSAND-601

CHANGELOG.md, extension-style/api/extension-style.api, extension-style/api/metalava.txt, extension-style/src/main/java/com/mapbox/maps/extension/style/atmosphere/generated/AtmosphereExt.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/atmosphere/generated/AtmosphereTest.kt
Port of https://github.com/mapbox/mapbox-maps-android/pull/1841
=> [port] remove atmosphere api

CHANGELOG.md, LICENSE.md, buildSrc/src/main/kotlin/Project.kt, plugin-locationcomponent/build.gradle.kts
As of Common SDK 23.2.0-rc.2 MME Location API in `mapbox-android-core` is now available in Common SDK 23.2.0-rc.2.
This PR removes the `api` dependency to `mapbox-android-core`.
User needs to remove any explicit dependency to `com.mapbox.mapboxsdk:mapbox-android-core:<version>` they might have in their project dependencies declaration.
=> Update gl-native to v10.10.0-rc.1, common to v23.2.0-rc.3

extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMap.kt, extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapScreenInstaller.kt, extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapSessionInstaller.kt
Fix metalava issues from androidauto.
=> MAPSAND-636 Update metalava for Builder return types

app/build.gradle.kts, buildSrc/src/main/kotlin/Project.kt, gradle/script-git-version.gradle
- Fixes playstore error to target api 31 (see screenshot).
- Update `tagsize` in gradle script to fix automatic deploy to playstore
=> [testapp] fix example app build for playstore publish

app/build.gradle.kts, buildSrc/src/main/kotlin/Project.kt, gradle/script-git-version.gradle
=> [port] fix for playstore publish (#1858)

CHANGELOG.md, sdk/src/main/java/com/mapbox/maps/MapView.kt
Fix displaying MapView in Android Studio Layout Preview.
Fixes https://github.com/mapbox/mapbox-maps-android/issues/1788
=> Fix displaying MapView in Android Studio Layout Preview

CHANGELOG.md, sdk/src/main/java/com/mapbox/maps/MapView.kt
This is #1881 port to the release branch.
=> PR #1881 port to release branch

.circleci/config.yml, app/src/main/java/com/mapbox/maps/testapp/examples/LargeGeojsonPerformanceActivity.kt, buildSrc/src/main/kotlin/Project.kt, extension-style/api/extension-style.api, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt, sdk/api/metalava.txt, sdk/api/sdk.api, sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt, sdk/src/main/java/com/mapbox/maps/Style.kt
=> Improve performance by setting geojson data directly

scripts/java-api-check.json
Ignore API changes for BitmapWidgetRenderer as it's internal class.
=> [ci] Ignore API changes for internal WidgetRenderer and BitmapWidgetRenderer.

.circleci/config.yml, app/src/main/java/com/mapbox/maps/testapp/examples/LargeGeojsonPerformanceActivity.kt, extension-style/api/extension-style.api, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt, sdk/api/metalava.txt, sdk/api/sdk.api, sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt, sdk/src/main/java/com/mapbox/maps/Style.kt
This is #1876 port to the release branch.
Not merging until stable GL-Native is out.
=> PR #1876 port to release branch

.circleci/config.yml
This is #1895 port to the release branch.
=> PR #1895 port to release branch

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt
This PR ports #1898 to v10.10 release branch.
Bump common SDK to v23.2.1
=> Port #1898 to v10.10 release branch.

gradle/wrapper/gradle-wrapper.properties, scripts/checksum.sh
Update gradle version to [7.5.1](https://docs.gradle.org/7.5.1/release-notes.html).
Also it's unblock us in using new dependency system.
=> bump gradle to 7.5.1

CHANGELOG.md, app/src/main/AndroidManifest.xml, app/src/main/java/com/mapbox/maps/testapp/examples/SecondaryDisplayPresentationActivity.kt, app/src/main/res/layout/activity_secondary_display_presentation.xml, app/src/main/res/layout/item_display_info.xml
Added new example `SecondaryDisplayPresentationActivity` to showcase how to use [Presentation](https://developer.android.com/reference/android/app/Presentation) to show a `Mapview` on a secondary display.
The main difference is that `Presentation` inherits from `Dialog` and it's embedded in an `Activity` which doesn't inherit from `AppCompatActivity`. Therefore, lifecycle needs to be managed manually and also apply a theme that inherits from `Theme.AppCompat`.
New demo:
=> Added example for secondary display using Presentation

.circleci/config.yml, scripts/ci-weekly-trigger.py
- run PRs only against a single device on firebase testlab on a PR basis
- run against multiple devices on a weekly basis (cron job)
=> [ci] optimize device configuration for firebase testlab

CHANGELOG.md, extension-style/api/extension-style.api, extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt, plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
Set direct geojson setter as a default option
related pr: https://github.com/mapbox/mapbox-maps-android/pull/1876
=> set direct geojson setter as a default option MAPSAND-656

app/src/main/java/com/mapbox/maps/testapp/examples/CircleLayerClusteringActivity.kt
Improve the circle layer cluster example so that it becomes compatible with [GL JS](https://docs.mapbox.com/mapbox-gl-js/example/cluster/) / [iOS](https://github.com/mapbox/mapbox-maps-ios/blob/v10.10.1/Apps/Examples/Examples/All%20Examples/Annotations/SymbolClusteringExample.swift) example codes
GL JS and iOS examples uses `stop` expression to change the circle color. Therefore, this PR uses same technique.
The code change does not affect the behavior like;
before:
after:
This update helps users understand how to implement same stuff on different environment.
PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-android/blob/main/CONTRIB …
=> Make  'Cluster points within a layer' example code compatible with GL JS / iOS

CHANGELOG.md
Update known issues for `10.11.0-beta.1` release
=> Update known issues for 10.11.0-beta.1

.circleci/config.yml
Remove unnecessary SSH key fingerprint from CircleCI config
N/A
=> Remove unnecessary SSH key fingerprint from CircleCI config

compose-app/src/main/AndroidManifest.xml
Handle orientation changes in compose-app so that map retains its center point etc when device is rotated
=> Handle orientation changes so that map retains its center point etc when device is rotated

CHANGELOG.md
Port https://github.com/mapbox/mapbox-maps-android/pull/1942 to `v10.11` branch.
N/A
=> [port] Update known issues for 10.11.0-beta.1 (#1942)

CHANGELOG.md, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/BackgroundLayerTest.kt, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/FillExtrusionLayerTest.kt, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/FillLayerTest.kt, extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/LineLayerTest.kt, extension-style/api/metalava.txt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/BackgroundLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillLayer.kt, extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LineLayer.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/BackgroundLayerTest.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayerTest.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/FillLayerTest.kt, extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/LineLayerTest.kt
* update style code for removed apis
* deprecate transition properties
* fix indentation in generated files
* update changelog
* added log error for deprecated methods
* update changelog and api
=> [port]deprecate transition api

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt
=> bump gl native v10.10.1, common to v23.2.2 MAPSAND-745

CHANGELOG.md
=> remove date for release train

CHANGELOG.md
=> [port] changelog for 10.10.1

extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
Revert back changes made in [this PR](https://github.com/mapbox/mapbox-maps-android/pull/1960/)
=> revert back sdk version

LICENSE.md
=>  port license fix

.circleci/config.yml, CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt
=> bump gl-native to v10.11.0-rc.1, common to v23.3.0-rc.1

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt
=> [port] changelog 10.11 rc.1

CHANGELOG.md
=> fix release title

.circleci/config.yml
Added slack notification with snapshot version to speedup and ease the snapshot flow, now the version could be copied directly from slack. 
[Job](https://app.circleci.com/pipelines/github/mapbox/mapbox-maps-android/7711/workflows/d73f76e3-08f9-4944-9f4d-ac8d8aec2dbc/jobs/66207) and corresponding [slack message](https://mapbox.slack.com/archives/C02K0FP7BKP/p1674817980668199) 
=> Added slack notification when snapshot is published

extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/GeoJsonSourceTest.kt
- Fix geojson style tests, after fixes from https://github.com/mapbox/mapbox-maps-android/pull/1920.
=> [MAPSAND-716] fix geojson tests

CHANGELOG.md, app/build.gradle.kts, app/src/androidTest/java/com/mapbox/maps/testapp/gestures/GestureInterceptedOnViewAnnotationTest.kt, app/src/androidTest/java/com/mapbox/maps/testapp/gestures/GestureUiUtils.kt, app/src/androidTest/res/layout/view_annotation.xml, sdk/src/main/java/com/mapbox/maps/MapView.kt
Testing fix of MAPSAND-720, MAPSAND-699 and #1897 
Notice how new pin is added to the map before fix after closing the view annotation - meaning onLongPress was fired by the SDK without actual gesture.
Important notice - gestures that involve `MotionEvent.ACTION_UP` (double tap to zoom, tap and scroll to zoom) are still _not_ intercepted from ViewAnnotations. This works differently than on iOS, however implementation seems complicated, since to implement them we'll need to notify gesture handlers in `onInterceptTouchEvent` instead of `onTouchEvent`. 
| Before  | After |
| ------------- | ------------- |
| <video src="https://user-images.githubusercontent.com/2265924/214882613-9bcf659e-4698-4fc6-8fa7-96538f033165.mp4">  |  <video src="https://user-images.githubusercontent.com/2265924/214882 …
=> Fix wrong longtouch

CHANGELOG.md, app/build.gradle.kts, app/src/androidTest/java/com/mapbox/maps/testapp/gestures/GestureInterceptedOnViewAnnotationTest.kt, app/src/androidTest/java/com/mapbox/maps/testapp/gestures/GestureUiUtils.kt, app/src/androidTest/res/layout/view_annotation.xml, sdk/src/main/java/com/mapbox/maps/MapView.kt
This is #1954 port to the release branch.
=> PR #1954 port to release branch

sdk/src/main/java/com/mapbox/maps/MapProvider.kt
Improve MapProvider.getMapTelemetryInstance execution time.
MapView initialisation should be improved.
=> MAPSAND-684 Deferred running of mapTelemetry.onAppUserTurnstileEvent so that construction of MapProvider can complete faster

compose-app/src/main/AndroidManifest.xml, compose-app/src/main/java/com/mapbox/maps/compose/MainActivity.kt, compose-app/src/main/java/com/mapbox/maps/compose/testapp/MainActivity.kt, compose-app/src/main/java/com/mapbox/maps/compose/testapp/ui/theme/Color.kt, compose-app/src/main/java/com/mapbox/maps/compose/testapp/ui/theme/Shape.kt, compose-app/src/main/java/com/mapbox/maps/compose/testapp/ui/theme/Theme.kt, compose-app/src/main/java/com/mapbox/maps/compose/testapp/ui/theme/Type.kt, extension-compose/api/extension-compose.api, extension-compose/api/metalava.txt, extension-compose/src/main/java/com/mapbox/maps/extension/compose/MapEffect.kt, extension-compose/src/main/java/com/mapbox/maps/extension/compose/MapboxMap.kt, extension-compose/src/main/java/com/mapbox/maps/extension/compose/MapboxMapComposable.kt, extension-compose/src/main/java/com/mapbox/maps/extension/compose/MapboxMapScope.kt, extension-compose/src/main/java/com/mapbox/maps/extension/compose/internal/MapApplier.kt, extension-compose/src/main/java/com/mapbox/maps/extension/compose/internal/MapPreviewPlaceholder.kt, extension-compose/src/main/java/com/mapbox/maps/extension/compose/internal/MapboxMapNode.kt
* Create entry point composable function MapboxMap, take MapInitOptions as parameter.
* Add map click listener hooks as the input to the MapboxMap composable function
* Add MapEffect class, pass through map controller.
* Create a small test application in the compose project.
=> [compose] Add MapboxMap compose entry point, expose map controller through MapEffect.

scripts/java-api-check-all.sh
Treat `develop` branch as another iteration of target branch next to main.
=> [script] treat develop as a target branch for revapi

CHANGELOG.md, plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GestureState.kt, plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt, plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GestureOptionsTest.kt, plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GestureStateTest.kt, plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt
port  #1989 MAPSAND-709 Remember GesturesManager state during gesture handling
=> port gesture state handle pr (#1989)

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt
=> bump common to v23.2.3

extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
=> update readme files

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
=> update common to v23.3.2 and readme files

CHANGELOG.md
=> Changelog 10.11.2. (#2038)

CHANGELOG.md, buildSrc/src/main/kotlin/Project.kt, extension-localization/README.md, extension-style/README.md, plugin-animation/README.md, plugin-annotation/README.md, plugin-attribution/README.md, plugin-compass/README.md, plugin-gestures/README.md, plugin-lifecycle/README.md, plugin-locationcomponent/README.md, plugin-logo/README.md, plugin-scalebar/README.md, plugin-viewport/README.md
Bump gl-native with the fix for tileset descriptor. 
=> Bump gl-native 10.10.2.
