app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/LocationTrackingActivity.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimatorManager.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckBearingAnimator.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckPositionAnimator.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPlugin.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/OnIndicatorBearingChangedListener.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/OnIndicatorPositionChangedListener.kt

This PR adds the OnIndicatorPositionChangedListener and OnIndicatorBearingChangedListener to the location component plugin, these two callbacks will be called on each position and bearing change of the location indicator, including each animation frame.
This PR also updates the LocationComponentActivity to utilise the OnIndicatorPositionChangedListener and always have the location indicator centered.  And LocationTrackingActivity is updated to use LocationComponentPlugin instead of deprecated LocationPlugin.

[location-component] Add OnIndicatorPositionChangedListener and OnIndicatorBearingChangedListener.

---

plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationProviderImpl.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationProviderImplTest.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt

This PR improves the default location provider implementation by moving to the last known location when new location consumer is registered.
This PR also improves the handling when disabling the location component.

[location-component] Improve the default location provider and improve handling of location updates.

---

app/src/main/java/com/mapbox/maps/testapp/examples/annotation/SymbolActivity.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Circle.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Fill.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Line.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/LineManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Symbol.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolOptions.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/SymbolManagerTest.kt

This pr add the bitmap API for Symbol to enable users to add a bitmap to Symbol directly instead of adding it to style.

[Annotation plugin] Add bitmap API for Symbol

---

app/src/main/java/com/mapbox/maps/testapp/examples/annotation/CircleActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/annotation/FillActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/annotation/LineActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/annotation/SymbolActivity.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleOptions.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/FillOptions.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/LineOptions.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolOptions.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/FillManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/LineManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/SymbolManagerTest.kt

This pr add  convenient `colorInt` API for annotation options to enable users use `colorInt` to set annotation color while creating annotations.

[Annotation plugin] Add colorInt API for annotation options

---

sdk/src/androidTest/java/com/mapbox/maps/MapboxMapIntegrationTest.kt
sdk/src/main/java/com/mapbox/maps/MapboxMapOptions.kt
sdk/src/main/java/com/mapbox/maps/MapboxOptions.kt
sdk/src/test/java/com/mapbox/maps/MapboxMapOptionsTest.kt

This pr add the function that checks and use the cached `resourceOptions` if it's initialized instead of recreate it from ResourcesOptions

[sdk] Use cached resourceOptions if it's initialized.

---

app/src/main/java/com/mapbox/maps/testapp/examples/DebugModeActivity.kt
app/src/main/res/layout/activity_debug.xml
sdk/src/main/java/com/mapbox/maps/MapControllable.kt
sdk/src/main/java/com/mapbox/maps/MapController.kt
sdk/src/main/java/com/mapbox/maps/MapSurface.kt
sdk/src/main/java/com/mapbox/maps/MapView.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
sdk/src/main/java/com/mapbox/maps/renderer/OnFpsChangedListener.kt
sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
sdk/src/test/java/com/mapbox/maps/MapViewTest.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt

`<changelog>[rendering] Expose setting FPS listener</changelog>`
Expose setting listener to measure FPS for map rendering and show FPS in debug activity example.
Breaking change in terms of extending public interface `MapControllable`.

[rendering] Expose setting FPS listener

---

DEVELOPING.md

This PR fixes the code snippet to download unstripped binary.

[doc] Fix code snippet to download unstripped binary.

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/mapbox/maps/testapp/examples/MapViewCustomizationActivity.kt
app/src/main/res/layout/activity_map_view_customization.xml
app/src/main/res/values/example_descriptions.xml
app/src/main/res/values/example_titles.xml
sdk/src/main/res-public/values/public.xml
sdk/src/main/res/values/attrs.xml

Fixes: #83 
`<changelog>Add example activity of creating MapView</changelog>`

Add example activity of creating MapView

---

app/src/main/java/com/mapbox/maps/testapp/examples/AnimatedImageSourceActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/IconSizeChangeOnClickActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/ImageSourceActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/MapOverlayActivity.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/Source.kt

`<changelog>Allow StyleManagerInterface.getSourceAs return null</changelog>`
Allow returning null for `getSourceAs` function when no such source is found or could not cast to given source.

Allow StyleManagerInterface.getSourceAs return null

---

plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt

This PR changes the default interpolator from `Decelerate` to `LinearOutSlowInInterpolator`. Conceptually they do the same thing but the latter was introduced as part of material design spec as an improved version of the former. 
See https://material.io/design/motion/speed.html > decelerate easing. 
cc @kiryldz

Change default gesture interpolator to LinearOutSlowInInterpolator

---

app/src/androidTest/java/com/mapbox/maps/testapp/annotation/UpdateAnnotationTest.kt
app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/CircleManagerAndroidTest.kt
app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/FillManagerAndroidTest.kt
app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/LineManagerAndroidTest.kt
app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/SymbolManagerAndroidTest.kt
app/src/main/java/com/mapbox/maps/testapp/examples/annotation/CircleActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/annotation/FillActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/annotation/LineActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/annotation/SymbolActivity.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImpl.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/FillManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/LineManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolManager.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPlugin.kt

Fixes: #102 
This PR renames the `getAnnotationManager` to `createAnnotationManager`.
This PR also renames the following methods:
`getLineManager` to `createLineManager`
`getCircleManager` to `createCircleManager`
`getFillManager` to `createFillManager`
`getSymbolManager` to `createSymbolManager`

[annotation] Rename getAnnotationManager to createAnnotationManager.

---

sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
sdk/src/test/java/com/mapbox/maps/NativeMapTest.kt

The renderStill API wasn't supposed to be exposed. Users can leverage snapshot() instead.

[map] remove renderStill API, this is an internal API

---

plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Symbol.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolOptions.kt

Fixes: #97 
This PR changes the default value of textFont to null and adds size check in Symbol while enabling data-driven properties.

[Annotation plugin] Change the default value of textFont to null; Add size check for properties in Symbol

---

app/src/main/java/com/mapbox/maps/testapp/examples/DebugModeActivity.kt
plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt
plugin-compass/src/test/java/com/mapbox/maps/plugin/compass/CompassViewPluginTest.kt

Fixes: #41 
This pr will hide the compass while opening a map that faces north.
In the past, the opacity will change from 1.0 to 0.0 while the compass is hiding even user sets the compass opacity, this pr fix this issue too.

[Compass plugin] Hidden the compass if facing north; apply the opacity correctly.

---

app/src/main/java/com/mapbox/maps/testapp/examples/annotation/SymbolActivity.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolManager.kt

By default, symbols will not be shown if there are overlaps or collide. 
This pr change these default values to show all symbols by default.

[Annotation plugin] Show all icons and texts of symbols by default

---

extension-style/src/main/java/com/mapbox/maps/extension/style/layers/Layer.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/FillManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/LineManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolManager.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/FillManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/LineManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/SymbolManagerTest.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationConfig.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationSourceOptions.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/GeoJsonOptions.kt

This pr add a config class `GeoJsonOptions` to allow to configure the underlying used GeoJsonSource and add `toString` method for `Layer`

[Annotation plugin] Add GeoJsonOptions to allow to configure the underlying used GeoJsonSource

---

plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Symbol.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/FillManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/LineManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/SymbolManagerTest.kt

Fixes: #71 
The same bitmap could be added to style for multi times if multi symbols use this bitmap.
This PR adds the check to avoid adding the same image multi times.

[Annotation plugin] Avoid adding same image multi times

---

plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsChangeListenersTest.kt
plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt
plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPlugin.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorNullableChangeListener.kt

Fixes: #82 
`<changelog>[animations] Cache map anchor in animation plugin, fix anchor camera animators</changelog>`
Treat `CameraOptions.anchor(ScreenCoordinate)` as all other camera options (zoom, bearing, etc). It means that if some animator did change an anchor - it will be saved and cached in `CameraAnimationPlugin` and used as initial start value for all upcoming animators if start value not specified explicitly.
This change fixes using anchor animators in gesture plugin.
`CameraAnimationsPlugin.anchor` override var is added to get / set anchor values.

[animations] Process anchor animators correctly

---

app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/LocationTrackingActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/sky/SkyLayerSnapshotterActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/DataDrivenMapSnapshotterActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/LocalStyleMapSnapshotterActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/MapSnapshotterActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/MapViewSnapshotActivity.kt
sdk-base/src/main/java/com/mapbox/maps/ExtensionUtils.kt
sdk/src/main/java/com/mapbox/maps/CustomSnapshotInterface.kt
sdk/src/main/java/com/mapbox/maps/SnapshotCreatedListener.kt
sdk/src/main/java/com/mapbox/maps/SnapshotStyleListener.kt
sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
sdk/src/test/java/com/mapbox/maps/SnapshotterDelegateTest.kt

`<changelog>[snapshotter] Introduce interfaces for style events and snapshot result</changelog>`
Clear division of interfaces for `Snapshotter` for taking an actual snapshot and loading a style for a `Snapshotter`.
Now functional interface `SnapshotCreatedListener` is used to perform an actual snapshot (or return null if not successful) and `SnapshotStyleListener` is used to listen to all style related callbacks.

[snapshotter] Introduce interfaces for style events and snapshot result

---

app/src/main/java/com/mapbox/maps/testapp/examples/annotation/SymbolActivity.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolOptions.kt

Fixes: https://github.com/mapbox/mapbox-maps-android/issues/97
<changelog>[annotation] Fix text-font issue in annotation plugin.</changelog>
We should set the default value of textFont
```
var textFont: List<String> = listOf(
"Open Sans Regular",
"Arial Unicode MS Regular"
)
```
Otherwise, if one of the symbols has provided the textFont, we will enable the data driven property of textFont and thus other symbols that don't specify the textFont property to have an empty text-font list, and result in
The resource 'https://api.mapbox.com/fonts/v1/mapbox//0-255.pbf' not found
And this blocks the annotation from …

[annotation] Fix text font issue in annotation plugin.

---

plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImpl.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/FillManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/LineManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/SymbolManagerTest.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManager.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPlugin.kt

This pr implement MapStyleObserverPlugin listen in annotation plugin to prevent reload failed issue.

[Annotation plugin] Implement MapStyleObserverPlugin to listen style load event to reload layer and source

---

plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/animator/CameraAnimator.kt
plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/animator/Evaluators.kt
plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturePluginTest.kt

Fixes: #168 
Fix a crash by actually revisiting approach for initing `CameraAnimator` - now it works not depending on Android SDK version.

[gestures] Fix crash if zooming for SDK <= 23

---

plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Circle.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleOptions.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Fill.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/FillOptions.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Line.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/LineOptions.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/Symbol.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/SymbolOptions.kt

Fixes: #169 
This pr change the default value to null for properties in annotation options to avoid triggering to many data-driven properties.

[Annotation plugin] Set default values for annotation option properties to null.

---

.circleci/config.yml

Recent regression showed we need to be testing against x86_64 ABIs.

[ci] add pixel2 for validating x86_64 abi

---

sdk/src/main/java/com/mapbox/maps/MapControllable.kt
sdk/src/main/java/com/mapbox/maps/MapController.kt
sdk/src/main/java/com/mapbox/maps/MapSurface.kt
sdk/src/main/java/com/mapbox/maps/MapView.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxSurfaceRenderer.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxTextureViewRenderer.kt
sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxRendererTest.kt

Fixes: #156 
Renderer now could execute basically 2 types of events on render (GL) thread. One does require true drawing (swapping buffers) and another simply executes `Task` or `Runnable` on render thread without actually swapping buffers.
`MapView` has updated API for `queueEvent`:
```
queueEvent(event: Runnable, needRender: Boolean)
```

[rendering] Differentiate render tasks and non-render tasks

---

app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentAnimationActivity.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimator.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimatorManager.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimatorManagerTest.kt

Fixes: #183 
Fix jitter animations if interrupting animations.
Such jittering happened before if location (or bearing) updates were arriving not evenly and animations cancelled each other making new animation start not from actual interpolated value but from end value of interrupted animation.

[locationcomponent] Fix jitter animations if interrupting animations

---

plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt

Fixes: #196 
- Use standard `AnimatorListener` if animation duration is zero to get correct results if changing several `CameraOptions` properties
- Register only `CameraAnimator`s for medium-level API like `playAnimatorsSequentially`  and `playAnimatorsTogether` and not all provided `ValueAnimator`s

[animation] Fix zero duration animators, fix medium-level animators

---

plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturePluginTest.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPlugin.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapTransformDelegate.kt
sdk/src/main/java/com/mapbox/maps/MapboxMap.kt

All gestures related to moving a map following if necessary with fling animation afterwards are now considered to use __drag API__. This API is designed to work both with or without 3D Terrain and should use following functions:
- `dragStart` - must be called before map starts dragging
- `getDragCameraOptions` - used to calculate correctly elevated `CameraOptions` that is used as target point for `easeTo` animation
- `dragEnd` - must be called when dragging a map has finished.
Dragging means operating with `center` …

[gestures] Introduce platform-driven drag API to move a map

---

plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt

We were using regular pixels instead of dpi that actually made zoom and center interpolation not work as designed.

[animations] Fix interpolation for flyTo

---

app/src/main/java/com/mapbox/maps/testapp/examples/SurfaceActivity.kt
app/src/main/java/com/mapbox/maps/testapp/wallpaper/MapWallpaper.kt
sdk/src/main/java/com/mapbox/maps/MapSurface.kt

MapSurface's creation shouldn't rely on the MapObserver. Users can subscribe to the map's events using `mapSurface.getMapboxMap().subscribe()` API.

[sdk] Remove MapObserver from MapSurface's constructor.

---

sdk/src/main/java/com/mapbox/maps/Style.kt
sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt

This PR removes the MapObserver reference from the codebase.

[doc] Remove MapObserver reference from the codebase.

---

app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/FillManagerAndroidTest.kt
app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/LineManagerAndroidTest.kt
app/src/main/java/com/mapbox/maps/testapp/examples/annotation/AnnotationUtils.kt
extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/utils/TypeUtilsTest.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/utils/TypeUtils.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/utils/TypeUtilsTest.kt

This PR changes how we marshal GeoJSON data across the JNI boundary. Instead of converting each Feature/Geometry to nested value types. We are taking the String representation of the GeoJSON data and wrapping that into a Value instead. Benchmark upstream has shown that this can result in a +3x improvement for ~10000 GeoJSON points. 
cc @alexshalamov, thank you for leading out this improvement and stopgap solution.

Use String protocol for passing GeoJSON data 

---

sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
sdk/src/test/java/com/mapbox/maps/SnapshotterDelegateTest.kt
sdk/src/test/java/com/mapbox/maps/SnapshotterTest.kt

This PR removes the usage of MapSnapshotterObserver and use Observerable API instead.

Remove usage of MapSnapshotterObserver and use Observerable API instead.

---

app/build.gradle.kts
app/src/androidTest/java/com/mapbox/maps/testapp/integration/fragment/EmptyFragment.kt
app/src/androidTest/java/com/mapbox/maps/testapp/integration/fragment/FragmentScenarioTest.kt
app/src/androidTest/java/com/mapbox/maps/testapp/integration/fragment/FragmentTest.kt
app/src/androidTest/java/com/mapbox/maps/testapp/integration/fragment/MapFragment.kt
app/src/main/res/layout/activity_multi_map.xml
buildSrc/src/main/kotlin/Project.kt

We recently had a regression with #191. This wasn't noticed directly in this repository but only in a downstream project we use for running benchmarks. To make sure we don't regress these use-cases, this PR adds a bunch of fragment integration tests. 
2 files with tests were added:
- **FragmentTest**: contains traditional testing of fragments
- **FragmentScenarioTest**: contains tests using the [fragment test library](https://developer.android.com/guide/fragments/test)

[test] add integration testing of MapView through fragments

---

sdk/src/main/java/com/mapbox/maps/MapController.kt

Fix runtime crash if logo / attribution not enabled

---

plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt
plugin-compass/src/test/java/com/mapbox/maps/plugin/compass/CompassViewPluginTest.kt

Keep CompassPlugin enabled/disabled state after other properties update (margin, opacity, etc.)

Keep CompassPlugin enabled/disabled state after other properties update

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/mapbox/maps/testapp/ExampleOverviewActivity.kt

Fixes: #114 
Root cause for the crash is that if we searched some text, the example list will show the searched result. Then if the search text is deleted, although it will show all examples, the `currentlyDisplayedExampleList` isn't updated and keeps the previous searched result. At this time if click an item with a bigger index the crash will occur.
This pr also fix the scenario that if we click the back arrow on the left top of an example back to the example list activity, the example list activity will be recreated and not be able to keep the previous state.

[example] Fix IndexOutOfBoundsException in test app

---

scripts/update-android-docs.sh

The previous script for auto-generating docs would use the tag name directly, which created a wrong dir for docs and need to be updated for[ beta.17](https://github.com/mapbox/mapbox-maps-android/pull/264).
This pr removes the "android-v" prefix from tag name to fix this issue.

Remove the prefix for tag name in update-android-docs.sh

---

app/src/main/java/com/mapbox/maps/testapp/examples/CameraPredefinedAnimatorsActivity.kt
app/src/main/res/layout/activity_camera_predefined_animators.xml
app/src/main/res/values/strings.xml
plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/HighLevelAnimatorSet.kt
plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt
plugin-compass/src/test/java/com/mapbox/maps/plugin/compass/CompassViewPluginTest.kt
plugin-location/src/test/java/com/mapbox/maps/plugin/location/LocationCameraControllerTest.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPlugin.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/animation/Cancelable.kt

High-level animation functions like `flyTo`, `easeTo` etc now return `Cancelable` interface allowing to cancel that high-level animation if needed.

[animation] High-level animations return cancelable interface

---

app/src/main/java/com/mapbox/maps/testapp/examples/MapViewCustomizationActivity.kt
sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
sdk/src/main/java/com/mapbox/maps/ResourcesAttributeParser.kt
sdk/src/test/java/com/mapbox/maps/MapInitOptionsTest.kt

This PR fixes a regression is introduced in https://github.com/mapbox/mapbox-maps-android/pull/269, the default rasterizationMode should be set to IDEOGRAPHS_RASTERIZED_LOCALLY, the default fontFamily should be set to "sans-serif" and constrainMode should be set to HEIGHT_ONLY.
The MapInitOptions default values are listed as below:
```
ResourceOptions:
cachePath: ${context.filesDir.absolutePath}/$DATABASE_NAME, where DATABASE_NAME = "mbx.db"
assetPath: context.filesDir.absolutePath
cacheSize: 50_000_000 (50 MB) …
```

Fix the MapOptions and ResourceOptions default values.

---

plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt

Remove animator cancel listeners logic because same logic is duplicated in `onAnimationEnd` callbacks. That means that if animator is cancelled end code will be executed twice.

[gestures] Remove animator cancel listeners logic

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/mapbox/maps/testapp/examples/OrnamentMarginActivity.kt
app/src/main/res/values/example_descriptions.xml
app/src/main/res/values/example_titles.xml
plugin-attribution/src/main/java/com/mapbox/maps/plugin/attribution/AttributionPluginImpl.kt
plugin-attribution/src/test/java/com/mapbox/maps/plugin/attribution/AttributionViewPluginImplTest.kt
plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewImpl.kt
plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt
plugin-compass/src/test/java/com/mapbox/maps/plugin/compass/CompassViewPluginTest.kt
plugin-logo/src/main/java/com/mapbox/maps/plugin/logo/LogoViewImpl.kt
plugin-logo/src/main/java/com/mapbox/maps/plugin/logo/LogoViewPlugin.kt
plugin-logo/src/test/java/com/mapbox/maps/plugin/logo/LogoViewImplPluginTest.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/attribution/AttributionView.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/compass/CompassView.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/logo/LogoView.kt

- adds an example to reproduce the user reported bug
- makes sure we call requestLayout after we have set margins of an ornament
- correct calling set margins correctly with the LTRB order
Developers now can see margins of the ornaments updating automatically when they set the values (workaround could be to call request layout yourself on the MapView).

Request layout when updating ornaments margins

---

sdk/src/main/java/com/mapbox/maps/CustomMapInterface.kt
sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
sdk/src/test/java/com/mapbox/maps/StyleTest.kt

Remove temporary CustomMapInterface used for testing, obsolete with having interface inheritance from upstream.
CustomMapInterface has been removed from public API

[sdk] remove temporary CustomMapInterface

---

app/build.gradle.kts
sdk/build.gradle.kts

Remove the exclude kotlin_module rule from package option, which caused some extension functions(observable extension functions) not discoverable from downstream projects.
Also tried to build a snapshot 10.0.0-beta.18-SNAPSHOT to verify the fix with downstream projects.

Remove the exclude kotlin_module rule from package options.

---

app/src/main/java/com/mapbox/maps/testapp/examples/MapViewCustomizationActivity.kt
sdk/src/main/java/com/mapbox/maps/MapController.kt
sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
sdk/src/main/java/com/mapbox/maps/MapSurface.kt
sdk/src/main/java/com/mapbox/maps/MapView.kt
sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
sdk/src/test/java/com/mapbox/maps/MapInitOptionsTest.kt

closes #195 
This PR refactors the plugin setup to avoid the boiler plate of try/catch blocks and allowing developers to provide their own set of plugin classes to be initialized. This allows them to avoid using underlying reflection calls and limit them to only the plugins needed.
Users have the ability when creating a MapView programmatically to limit the amount of plugins we attempt to load.

[plugin] refactor plugin setup

---

sdk/src/main/java/com/mapbox/maps/MapController.kt
sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
sdk/src/main/java/com/mapbox/maps/NativeObserver.kt
sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
sdk/src/test/java/com/mapbox/maps/NativeObserverTest.kt
sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt

Replaces https://github.com/mapbox/mapbox-maps-android/pull/178
This PR reworks how we do style loading internally to expose these to developers. We make sure to clear any set listeners when a new style will be loaded. This avoids calling OnStyleLoaded on an old obsolete instance of a previous set style. 
When a user load a style and it errors out and load a new style. Only the secondary interface provided to the second style loading will be invoked. The first one will be ignored.

[sdk] rework style loading to avoid invoking previously set listeners

---

plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt
plugin-compass/src/test/java/com/mapbox/maps/plugin/compass/CompassViewPluginTest.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/MapCameraPlugin.kt
sdk/src/androidTest/java/com/mapbox/maps/MapIntegrationTest.kt

Fixes: #308 
Every consumer (in our case it's compass plugin) should make sure that `MapCameraPlugin.onCameraMove` is called from correct thread.

Fix crash if doing setCamera during map loading

---

sdk-base/build.gradle.kts
sdk-base/src/main/java/com/mapbox/maps/dsl/CameraOptionsKtx.kt
sdk-base/src/test/java/com/mapbox/maps/dsl/CameraOptionsKtxTest.kt

```
<changelog>Added a `cameraOptions(cameraState, builderBlock)` inline method that helps mutate an existing `CameraState` object.</changelog>
```
Adds an option to use a `CameraState` as a mutation base for the `cameraOptions` inline DSL.

Add an option to mutate camera state using the CameraOptionsKtx.kt DSL

---

sdk/src/androidTest/java/com/mapbox/maps/RenderCacheTest.kt
sdk/src/main/java/com/mapbox/maps/MapControllable.kt
sdk/src/main/java/com/mapbox/maps/MapController.kt
sdk/src/main/java/com/mapbox/maps/MapSurface.kt
sdk/src/main/java/com/mapbox/maps/MapView.kt
sdk/src/main/java/com/mapbox/maps/RenderCache.kt

Introduce API to enable render cache feature that could bring up rendering performance improvement.

Add render cache API

---

plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginImpl.kt

Fix scalebar doesn't update issue.

---

app/src/main/java/com/mapbox/maps/testapp/examples/annotation/CircleAnnotationActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PointAnnotationActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PolyfillAnnotationActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PolylineAnnotationActivity.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImpl.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImplTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPlugin.kt

Fixes: #291 
- Add removeAnnotationManager API to enable users remove the useless annotation manager and the inside layer and source
- If user set the belowLayerId in config and the current style doesn't have this layer, it will crash while adding the annotation layer. This pr adds the check for this below layer and will add the annotation layer directly if the below layer doesn't esist.

Add removeAnnotationManager API;  Fix crash if the belowLayerId doesn't exist on the current style

---

plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt

In case of starting high-level animation in `onAnimationEnded` of another high-level animation the nested one would not report animation end / cancel etc callbacks. This is now fixed.

[animation] Trigger nested high-level animator listener correctly

---

plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewPlugin.kt
plugin-compass/src/test/java/com/mapbox/maps/plugin/compass/CompassViewPluginTest.kt

Previous implementation used a camera state but we weren't caching it. When you had the compass disabled, rotated the camera and renabled the compass after. It wasn't showing, you had to mutate the camera again to make the compass visible.

[compass] make compassview visible when enabled

---

plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationProviderImpl.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationProviderImplTest.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt

Fixes: #323 #324 
- The root cause for location not shown when accepting permissions is we need to get the style to active location component 
and the style has not been set yet while init location component.
This pr listen to the style load event and trigger `applySettings ` to reactive location component and apply a loop request to get the location update after location permission is granted.
- This pr also make the location puck invisible before getting the real location from the device to fix the null island issue

Auto active LocationComponent while style loaded.

---

app/src/main/java/com/mapbox/maps/testapp/examples/MapViewCustomizationActivity.kt
sdk/src/main/java/com/mapbox/maps/CredentialsManager.kt
sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
sdk/src/main/java/com/mapbox/maps/MapboxConstants.kt
sdk/src/main/java/com/mapbox/maps/ResourceOptionsManager.kt
sdk/src/main/java/com/mapbox/maps/ResourcesAttributeParser.kt
sdk/src/main/res-public/values/public.xml
sdk/src/main/res/values/attrs.xml
sdk/src/test/java/com/mapbox/maps/MapInitOptionsTest.kt
sdk/src/test/java/com/mapbox/maps/ResourceAttributeParserTest.kt
sdk/src/test/java/com/mapbox/maps/ResourceOptionsManagerTest.kt

Fixes:  #329 
This PR introduces ResourceOptionsManager to configure the default resource options, and removed the xml configuration options for cache path and tile store path.

Introduce ResourceOptionsManager to configure default resource options, remove xml config for paths.

---

.circleci/config.yml
sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
sdk/src/main/java/com/mapbox/maps/MapboxConstants.kt
sdk/src/test/java/com/mapbox/maps/MapInitOptionsTest.kt
sdk/src/test/java/com/mapbox/maps/ResourceAttributeParserTest.kt
sdk/src/test/java/com/mapbox/maps/ResourceOptionsManagerTest.kt

This is to align with iOS in https://github.com/mapbox/mapbox-maps-ios/pull/324.
No public API is impacted but I'm dubbing this as a breaking change as users will lose previous stored data from the ambient cache. 
This PR changes the the ambient cache name of the database to ambient_cache.db to align with iOS.
Previous stored ambient cache data will be lost when migrating to a newer version of the SDK.
cc @LukasPaczos

[sdk] rename ambient cache database to ambient_cache.db 

---

app/src/main/java/com/mapbox/maps/testapp/examples/MapViewCustomizationActivity.kt

Restore the default resource options when exiting the MapViewCustomizationActivity, since it will affect other activities as well.

Restore the default resource options when exiting the MapViewCustomizationActivity.

---

app/src/androidTest/java/com/mapbox/maps/testapp/integration/events/StyleLoadedEventTest.kt
sdk/src/main/java/com/mapbox/maps/StyleObserver.kt

Fixes: https://github.com/mapbox/mapbox-maps-android/issues/348
Avoid clearing styleLoadedListeners inside mapLoadingErrorListener, and vice versa.

Avoid clearing styleLoadedListeners inside mapLoadingErrorListener, and vice versa.

---

plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt
plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsListenersTest.kt
plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt
sdk-base/src/main/java/com/mapbox/maps/ExtensionUtils.kt
sdk/src/androidTest/java/com/mapbox/maps/CameraAnimationsPluginTest.kt

Fixes: #363 
The camera plugin impl executes camera jumps on a tick of first animator. The animator is registered _also_ when it first ticks, but it was registered last. Because the logic to execute the updates checks for the registered animators, and the animators was registered last in that logical block, the first tick of the animation was effectively ignored.
This skipped update was causing a little bit of desynchronization when paired with other animations (like location puck animation)
Example before (notice puck moving forward and back when animations starts): …

Make sure to execute first camera update

---

sdk/src/main/java/com/mapbox/maps/MapboxConstants.kt
sdk/src/test/java/com/mapbox/maps/MapInitOptionsTest.kt
sdk/src/test/java/com/mapbox/maps/ResourceAttributeParserTest.kt
sdk/src/test/java/com/mapbox/maps/ResourceOptionsManagerTest.kt

This PR changes the default ambient cache path to `.mabox/maps/ambient_cache.db` to align with default tile_store path.

Change default ambient cache path to .mabox/maps/ambient_cache.db

---

app/src/androidTest/java/com/mapbox/maps/testapp/annotation/UpdateAnnotationTest.kt
app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PointAnnotationManagerAndroidTest.kt
app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PointAnnotationActivity.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotation.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationOptions.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManager.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt

Property `text-font` is a data-driven property, however, if we apply this property in `PointAnnotationOptions`
```
val pointAnnotationOptions: PointAnnotationOptions = PointAnnotationOptions()
.withTextFont( listOf( "Arial Unicode MS Bold",   "Open Sans Regular" ))
```
We will have the following error:
```
Layer 'mapbox-android-symbol-layer-4' has an invalid value for text-font and will not render text. Output values must be contained as literals within the expression.
``` 
This is because we are using `get` expression …

Move text-font property from PointAnnotation to PointAnnotationManager

---

extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
sdk/src/androidTest/java/com/mapbox/maps/MapIntegrationTest.kt

This PR brings following changes to async geojson behavior:
- If __synchronised__ method is called to change `data` property (those are `GeoJsonSource.data(...)`, `GeoJsonSource.feature(value: Feature)`, `GeoJsonSource.featureCollection(value: FeatureCollection)`, `GeoJsonSource.geometry(value: Geometry)`) while worker thread is already busy parsing some previous data - handler thread queue should be cleared, current task should be canceled and new `data` should be applied immediately.
- If __async__ method is called to …

Geojson async data parsing: fixes and improvements

---

app/src/main/java/com/mapbox/maps/testapp/examples/RuntimeStylingActivity.kt
extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/BaseStyleTest.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/Light.kt

Rename setter for Light object from add to set. This matches API from GL-JS and clarifies there is only 1 Light object.

[style] rename setter for Light object from add to set

---

CHANGELOG.md

Fixed an typo in beta.21 changelog.

Fixed an typo in beta.21 changelog.

---

extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/BaseStyleTest.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/StyleExtensionImpl.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/Terrain.kt

Rename setter for Terrain object from add to set, this is to align more with gl-js and other platforms.

[style] rename setter for Terrain object from add to set

---

app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt
sdk/src/androidTest/java/com/mapbox/maps/MapboxMapIntegrationTest.kt
sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
sdk/src/main/java/com/mapbox/maps/MapboxConstants.kt
sdk/src/test/java/com/mapbox/maps/MapInitOptionsTest.kt
sdk/src/test/java/com/mapbox/maps/ResourceAttributeParserTest.kt
sdk/src/test/java/com/mapbox/maps/ResourceOptionsManagerTest.kt

This PR changes the default dataPath to the one core sets, i.e. `"${context.filesDir.absolutePath}/.mapbox/map_data/"`,
the path to the database file will be changed to `"${context.filesDir.absolutePath}/.mapbox/map_data/map_data.db"` by default.

Use the default dataPath from core.

---

plugin-attribution/build.gradle.kts
plugin-attribution/src/main/res-public/values/public.xml
plugin-compass/build.gradle.kts
plugin-compass/src/main/res-public/values/public.xml
plugin-gestures/build.gradle.kts
plugin-locationcomponent/build.gradle.kts
plugin-logo/build.gradle.kts
plugin-logo/src/main/res-public/values/public.xml
plugin-scalebar/build.gradle.kts
plugin-scalebar/src/main/res-public/values/public.xml
sdk/build.gradle.kts
sdk/src/main/res-public/values/public.xml

We use public.xml for indicating which attributes are private vs public (more context [here](https://developer.android.com/studio/projects/android-library#PrivateResources)). With using the public.xml configuration, we should be able to find a public.txt file in the resulting aar:
> When building a library, the Android Gradle plugin gets the public resource definitions and extracts them into the public.txt file, which is then packaged inside the AAR file.
This is currently broken since we didn't configure the …

Include xml attribute strings from res-public to sourceSet.

---

buildSrc/src/main/kotlin/Project.kt
sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt
sdk/src/main/java/com/mapbox/maps/Style.kt
sdk/src/test/java/com/mapbox/maps/NativeMapTest.kt
sdk/src/test/java/com/mapbox/maps/StyleTest.kt

* Bump gl-native to v10.0.0-rc.2
* Introduce experimental Style#addPersistentStyleLayer, Style#addPersistentStyleCustomLayer and Style#isStyleLayerPersistent API.

Bump gl-native to v10.0.0-rc.2, introduce addPersistentLayer/isPersistentLayer API.

---

sdk/src/main/java/com/mapbox/maps/MapView.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxSurfaceHolderRenderer.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxSurfaceRenderer.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxTextureViewRenderer.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxRendererTest.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxSurfaceHolderRendererTest.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxSurfaceRendererTest.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxTextureViewRendererTest.kt

Fixes: #420 
This PR fixes memory leak for texture view renderer. It also improves overall render thread management - in some situations some essential code was not executed before killing render thread.
Additionally tests were added for `MapboxSurfaceHolderRenderer`.
After fix, surface view:
After fix, texture view:

Fix memory leak on render destroy

---

extension-style/src/main/java/com/mapbox/maps/extension/style/layers/Layer.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/layers/LayerExt.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/LayerExtTest.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImpl.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManager.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImplTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationLayerWrapper.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImplTest.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerWrapperTest.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationLayerWrapperTest.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapperTest.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManager.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPlugin.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPlugin.kt
sdk/src/main/java/com/mapbox/maps/Style.kt

This PR integrates the experimental `addPersistentStyleLayer` API to annotation plugin and location component plugin, and improves the performance of Annotation Plugin and Location Component Plugin during the style change. 
Before:
https://user-images.githubusercontent.com/2764714/119505810-0144aa80-bd76-11eb-93ab-88ef3acc3f1a.mp4
After:
https://user-images.githubusercontent.com/2764714/119505828-0570c800-bd76-11eb-92d8-6bb345ebfa7a.mp4

Integrate the `addPersistentStyleLayer` to annotation plugin and location component plugin.

---

app/build.gradle.kts

This PR sets the maximum heap size for dex operation to 4g, to avoid flaky builds in CI.

[app] Set the maximum heap size for dex operation to 4g.

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/mapbox/maps/testapp/examples/StyleCrossFadeAnimationActivity.kt
app/src/main/java/com/mapbox/maps/testapp/utils/StyleSwitcher.kt
app/src/main/res/layout/activity_style_cross_fade.xml
app/src/main/res/values/example_descriptions.xml
app/src/main/res/values/example_titles.xml
app/src/main/res/values/strings.xml

Add activity showcasing style cross fading. 
For easier use added utility class of `StyleSwitcher` to `:app` module (not part of SDK itself).
Before:
https://user-images.githubusercontent.com/15800566/122414411-cce89680-cf8f-11eb-8a30-92e934b135b8.mp4
After:
https://user-images.githubusercontent.com/15800566/122414084-8c891880-cf8f-11eb-9cc4-332d1ff9101e.mp4

Add activity showcasing style cross fading

---

plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/HighLevelAnimatorSet.kt
plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/animator/CameraAnimator.kt
sdk/src/androidTest/java/com/mapbox/maps/CameraAnimationsPluginTest.kt

Fixes: #164 
When canceling animators manually inside `CameraAnimationsLifecycleListener.onAnimatorStarting` (typical Nav SDK use-case) before starting high-level animation (e.g. `easeTo`) - callbacks for high-level animation listener would be called incorrectly while camera itself would be completely stuck. That happens in concrete scenario when animator with delay was not started before canceling it.
This PR fixes it.

Fix camera deadlock use-case

---

.circleci/config.yml

If a last commit in a branch has `publish_android_snapshot` in a title or description, `build-sdk-release` bot will create a snapshot release. The name of the snapshot release would be:
${LAST_RELEASE_VERSION_BEFORE_THIS_COMMIT}-${BRANCH_NAME}-SNAPSHOT for example:
10.0.0-rc.1-peng-commit-message-based-snapshot-SNAPSHOT

[build] Publish snapshot when the commit message contains publish_android_snapshot keyword.

---

extension-localization/src/main/java/com/mapbox/maps/extension/localization/Localization.kt
extension-localization/src/main/java/com/mapbox/maps/extension/localization/SupportedLanguages.kt

We replaced all the `get` expression with selected language and for those with expression `coalesce` and only have a default language it will not show the default language.
This pr will make the replacement not applied on such expression like `get("name")` to show the default language. 
However, users might pass in a not supported language, then we will output a warning logcat.

Coalesce to the default language if not supported

---

CHANGELOG.md
extension-style/README.md
plugin-animation/README.md
plugin-attribution/README.md
plugin-compass/README.md
plugin-gestures/README.md
plugin-locationcomponent/README.md
plugin-logo/README.md
plugin-overlay/README.md
plugin-scalebar/README.md

Changelog for v10.0.0-rc.2

---

app/src/androidTest/java/com/mapbox/maps/testapp/annotation/UpdateAnnotationWithMultiManagersTest.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PointAnnotationActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/annotation/PolygoneAnnotationActivity.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImpl.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt

Fixes: #433 
Some annotation updates could be ignored as we will remove the pending GeojsonSource update in the queue.
This pr remove this logic to guarantee all annotation update could be executed.

Fix annotation update missing issue.

---

extension-style/src/main/java/com/mapbox/maps/extension/style/layers/Layer.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/Source.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/BackgroundLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/CircleLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/FillLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/HeatmapLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/HillshadeLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/LineLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/LocationIndicatorLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/RasterLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/SkyLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/SymbolLayerTest.kt

Refs: #364 
Optimise the `style#getLayer` and `style#getSource` APIs' performance by avoid using the heavy `style#getStyleLayerProperties` and `style#getStyleSourceProperties` API.
The initial benchmarking showed the CPU utilisation improvement as follows when the getLayer is used frequently, for example, inside the camera animator:
Before(`getLayer` takes 12.1% CPU time, `getStyleLayerProperties` takes 8.7% CPU time):
After(`getLayer` takes 5.47% cpu time, `getStyleLayerProperty` takes 2.14% CPU time):

[style] Optimise the style#getLayer and style#getSource APIs.

---

extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/BackgroundLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/CircleLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/FillLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/HeatmapLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/HillshadeLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/LineLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/LocationIndicatorLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/RasterLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/SkyLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/SymbolLayerTest.kt
sdk/src/androidTest/java/com/mapbox/maps/MapIntegrationTest.kt

Rebase gone wrong before merging https://github.com/mapbox/mapbox-maps-android/pull/332, this PR restores the generated style code.

[style] restore recent changes to generated style code

---

app/src/main/java/com/mapbox/maps/testapp/examples/localization/LocalizationActivity.kt
app/src/main/res/menu/menu_languages.xml
app/src/main/res/values/strings.xml
extension-localization/src/main/java/com/mapbox/maps/extension/localization/Localization.kt
extension-localization/src/main/java/com/mapbox/maps/extension/localization/StyleInterfaceExtension.kt

This pr add a new param `layerIds` for API `localizeLabels`,  `layerIds` is a list, user can put all the layers they want to localize in this list, other layers not in this list will not be localized.
The default value of `layerIds` is null which means localize all the feasible layers.
https://user-images.githubusercontent.com/8577318/123926832-dece2e80-d9be-11eb-9817-5a92245803c1.mp4

[Localization] Add new param to allow users localize selected layers.

---

plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
plugin-animation/src/test/java/com/mapbox/common/ShadowLogger.java
plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPlugin.kt

Fixes: #243 
Add API to disable not critical logs for camera plugin. `debugMode` is set to false by default. Logs could be enabled with:
```
mapView.camera.debugMode = true
```
Additionally even if logs are enabled non-critical logs are downgraded to use `Logger.d` instead of `Logger.i`.

Add API to control logs for animators

---

app/src/androidTest/java/com/mapbox/maps/testapp/scalebar/generated/ScaleBarAttributeParserDefaultValueTest.kt
app/src/androidTest/java/com/mapbox/maps/testapp/scalebar/generated/ScaleBarAttributeParserTest.kt
app/src/main/res/layout/generated_test_scalebar.xml
plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarImpl.kt
plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginImpl.kt
plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/generated/ScaleBarAttributeParser.kt
plugin-scalebar/src/main/res-public/values/public.xml
plugin-scalebar/src/main/res/values/attrs.xml
plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/ScaleBarImplTest.kt
plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginTest.kt
plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/generated/ScaleBarAttributeParserTest.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBar.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarPlugin.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/scalebar/generated/ScaleBarSettings.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/scalebar/generated/ScaleBarSettingsBase.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/scalebar/generated/ScaleBarSettingsInterface.kt

Scale bar custom view was previously rendering on demand. Drawing was happening when camera was moving. However when scalebar is disabled it actually means that no more draw calls would happen. That actually leads to incorrect data from `gfxinfo` in terms of `Total frames rendered` as number of such frames would we always 3 or 4 despite map itself is rendering OK. This is actually not visible if scalebar is visible and map is moving but results are totally incorrect if we do `mapView.scalebar.enabled = false`.
In order …

Introduce option to use continuous rendering for scale bar

---

plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt
plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactoryTest.kt

Fixes: #475 
Fixes: https://github.com/mapbox/mapbox-maps-android/issues/177
Fix a crash (if changing center as well) or zoom reporting NaN (if changing zoom) when using `mapView.camera.flyTo` with 1-pixel padding or `mapView.width == padding.left + padding.right && mapView.height == padding.bottom + padding.top`

Fix flyTo crash when using single-pixel paddings

---

extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
sdk/src/androidTest/java/com/mapbox/maps/MapIntegrationTest.kt

Fixes: https://github.com/mapbox/mapbox-maps-android/issues/481
If sync method is called using `getSourceAs` while some parsing is already happening e.g.:
```
style.getSourceAs<GeoJsonSource>("source")!!
.featureCollection(
FeatureCollection.fromFeatures(
listOf(feature)
)
)
```
async task will __not__ overwrite data now.

Fix overwriting sync geojson data with getSourceAs by async

---

plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraOptionsUtils.kt

Fixes: https://github.com/mapbox/mapbox-maps-android/issues/483
Try to apply camera changes accumulated in `cameraOptionsBuilder` when all animators finish. This is relevant for Android SDK <= 23 versions and has visual effect for gestures because they use `easeTo` with zero-duration. In general last animator is skipped for low-end devices without this fix which leads to incorrect behaviour.

[CameraAnimationsPluginImpl] Fix camera animations on Android 6

---

app/src/main/java/com/mapbox/maps/testapp/examples/LocationComponentActivity.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LayerSourceProvider.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapper.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentAttributeParser.kt
plugin-locationcomponent/src/main/res-public/values/public.xml
plugin-locationcomponent/src/main/res/values/attrs.xml
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LayerSourceProviderTest.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapperTest.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/ConfigProperties.kt

This pr add a new property `modelTranslation` for LocationPuck3D, which enable users to shift the model with directions of [lon, lat, z]

Add modelTranslation support for LocationPuck3D

---

sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapCameraManagerDelegate.kt
sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt

Add default values to parameters of `MapCameraManagerDelegate#cameraForCoordinates`, `MapCameraManagerDelegate#cameraForCoordinateBounds` and `MapCameraManagerDelegate#cameraForGeometry`.
Allows user to hook into these functions more easily, not needing them to provide null values.

[sdk-base] add default parameters to coordinate conversion functions

---

app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/MapSnapshotterActivity.kt
sdk/src/main/java/com/mapbox/maps/SnapshotOverlayOptions.kt
sdk/src/main/java/com/mapbox/maps/Snapshotter.kt

Created a new data class `SnapshotOptions` which wrap `MapSnapshotOptions` and `showLogo`/`showAttribution`. 
`Snapshotter` now take a `SnapshotOptions` as construct param.

Add showLogo and showAttributes config for snapshotter

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/mapbox/maps/testapp/examples/AnimatedImageSourceActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/SurfaceActivity.kt
plugin-attribution/src/main/java/com/mapbox/maps/plugin/attribution/AttributionPluginImpl.kt
plugin-attribution/src/main/java/com/mapbox/maps/plugin/attribution/AttributionViewImpl.kt
plugin-attribution/src/test/java/com/mapbox/maps/plugin/attribution/AttributionViewImplTest.kt
plugin-attribution/src/test/java/com/mapbox/maps/plugin/attribution/AttributionViewPluginImplTest.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationProviderImpl.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/attribution/AttributionView.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxSurfaceHolderRenderer.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxTextureViewRenderer.kt

Update codebase to be compliant with building against Android 12.
- add exported attribute to activities/services in manifest
- be explicit about runnable and SurfaceHolder nullability
- avoid overriding View#setOnClickListener

[build] update code to be Android 12 target SDK compatible

---

sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
sdk/src/main/java/com/mapbox/maps/renderer/gl/PixelReader.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxRendererTest.kt

Fixes: #42 
Fix issues with MapView#snapshot methods that could cause black snapshot or ANR in some cases.
Additionally releasing buffers for `PixelReader` is moved to thread with GL context to make it work.

Fix issues with MapView#snapshot methods

---

.circleci/config.yml

This pr contains the following changes:
- Output the snapshot name if a snapshot is uploaded to registry to enable us to use the snapshot easily.
- As we now generate and create the pr for docs locally,  the `generate-docs` step is not needed, so delete this stop from release steps

Remove generate-docs step in release

---

.circleci/config.yml

This PR adds commit hash to the built snapshot releases.
Before:
Snapshots on main branch are overwritten every time there's a new commit, and the version name is:
`com.mapbox.maps:android:10.0.0-SNAPSHOT`
After:
Snapshots on the main branch will have unique version name for each commit, the proposed version name is:
Appending the commit hash before the -SNAPSHOT defined in the gradle.properties file, so it would become:
`com.mapbox.maps:android:10.0.0-a1d95e7a-SNAPSHOT`

[ci] Add commit hash to the snapshots' name built on main branch.

---

.circleci/config.yml

This PR fixes the snapshot circle CI config, to use CIRCLE_BRANCH instead of CIRCLE_TAG to check for main branch. And also fixed the logic to only change the snapshot version name if it is not a release tag.

[ci] Fix the snapshot circle CI config.

---

.circleci/config.yml

This PR increases robo test and build sdk release CI bot's resources to fix flaky tests due to OOM.
The recent flaky tests are build-sdk-release and robo tests(building release version of the SDK), so this PR only covers these two bots.

[ci] Increase robo test and build sdk release CI bot's resources to fix flaky tests due to OOM.

---

sdk/src/main/java/com/mapbox/maps/FontUtils.kt

Hey folks, quick fix. I'm playing around on Android a bit and noticed my log :cat2: showing me this all day
```
I/Mbgl-FontUtils: Couldn't map font family for local ideograph, using %s instead sans-serif
```
instead of the properly interpolated string.
That's it :v:

Fixes string interpolation in font utils log message

---

app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/DataDrivenMapSnapshotterActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/LocalStyleMapSnapshotterActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/snapshotter/MapSnapshotterActivity.kt
sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
sdk/src/test/java/com/mapbox/maps/SnapshotterDelegateTest.kt
sdk/src/test/java/com/mapbox/maps/SnapshotterTest.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxRendererTest.kt

Fixes: #448 
Fix memory leaks that were caught during going thru our example activities.
- Clean up `OnFpsChangeListener` on render thread destroy.
- Introduce `Snapshotter#destroy` method that must be called in `Activity#onDestroy`

Fix memory leaks in SDK

---

app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/CircleAnnotationActivity.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt

Fixes: #378 
If create an AnnotationManager before loading a style, the layer and source will not be initiated because while loading a style, the previously added styleload listener will be removed. To fix this, this pr add a check in `updateSource` method and init layer and source if they are not initiated before

Add check for layer and source while creating annotations and init them if not initiated before

---

extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/GeoJsonSourceTest.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt

This PR adds `generateId` property to the GeoJsonSource.

Add generateId for GeoJsonSource.

---

extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/GeoJsonSourceTest.kt
extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/ImageSourceTest.kt
extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/RasterDemSourceTest.kt
extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/RasterSourceTest.kt
extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/VectorSourceTest.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/ImageSource.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterDemSource.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterSource.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/VectorSource.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/ImageSourceTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/RasterDemSourceTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/RasterSourceTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/VectorSourceTest.kt

Currently we generate expression getter/setters for source properties, however, capturing from gl-native team, sources don't support expressions at all.
We need to remove the expression getter/setters for source properties.

[style-extension] Remove the expression getter/setters for source properties

---

sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
sdk/src/test/java/com/mapbox/maps/SnapshotterTest.kt

Fixes: #570 
Remove strong ref dependency in snapshotter that was leading to a memory leak if Snapshotter#destroy was not called explicitly.

Remove strong ref dependency in snapshotter

---

LICENSE.md
android-auto-app/build.gradle.kts
app/build.gradle.kts
app/src/main/java/com/mapbox/maps/testapp/examples/LegacyOfflineActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/MapViewCustomizationActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/SurfaceRecyclerViewActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/java/DSLStylingJavaActivity.java
app/src/main/java/com/mapbox/maps/testapp/examples/java/RuntimeStylingJavaActivity.java
app/src/main/java/com/mapbox/maps/testapp/examples/linesandpolygons/PolygonHolesActivity.kt
app/src/main/res/layout/activity_annotation.xml
app/src/main/res/layout/activity_custom_attribution.xml
app/src/main/res/layout/activity_custom_layer.xml
app/src/main/res/layout/activity_fill_extrusion.xml
app/src/main/res/layout/activity_inset_map.xml
app/src/main/res/layout/activity_map_localization.xml
app/src/main/res/layout/activity_map_overlay.xml
app/src/main/res/layout/activity_rts_fill_pattern_tint.xml
app/src/main/res/layout/activity_show_hide_layers.xml
app/src/main/res/layout/activity_view_snapshot.xml
app/src/main/res/values/strings.xml
buildSrc/src/main/kotlin/Project.kt
extension-style-app/build.gradle.kts
gradle/jacoco.gradle
gradle/lint.gradle
gradle/wrapper/gradle-wrapper.properties
sdk/build.gradle.kts

This PR bumps the kotlin to 1.5.21 and dokka to 1.4.20
Newer version of dokka includes capability to generate API documentation with default values:

[deps] Bump kotlin to 1.5.21, dokka to 1.4.20, AGP to 4.2.2, jacoco to 0.8.7.

---

app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PointAnnotationManagerAndroidTest.kt
app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PolylineAnnotationManagerAndroidTest.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotation.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotation.kt

Fixes: #576
While using `valueOf` to create an enum,  the param must the same with enum name which is upper case, however, the value we saved in annotation is lower case, so the compare will fail and crash. 
This pr changes the value to the upper case while creating new enum instance.
cc: @AndreasBoehm

Fix get annotation enum property crash

---

LICENSE.md
android-auto-app/build.gradle.kts
app/build.gradle.kts
app/src/main/java/com/mapbox/maps/testapp/examples/LegacyOfflineActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/MapViewCustomizationActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/OfflineActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/SurfaceRecyclerViewActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/java/DSLStylingJavaActivity.java
app/src/main/java/com/mapbox/maps/testapp/examples/java/RuntimeStylingJavaActivity.java
app/src/main/java/com/mapbox/maps/testapp/examples/linesandpolygons/PolygonHolesActivity.kt
app/src/main/res/layout/activity_annotation.xml
app/src/main/res/layout/activity_custom_attribution.xml
app/src/main/res/layout/activity_custom_layer.xml
app/src/main/res/layout/activity_fill_extrusion.xml
app/src/main/res/layout/activity_inset_map.xml
app/src/main/res/layout/activity_map_localization.xml
app/src/main/res/layout/activity_map_overlay.xml
app/src/main/res/layout/activity_rts_fill_pattern_tint.xml
app/src/main/res/layout/activity_show_hide_layers.xml
app/src/main/res/layout/activity_view_snapshot.xml
app/src/main/res/values/strings.xml
buildSrc/src/main/kotlin/Project.kt
extension-style-app/build.gradle.kts
gradle/jacoco.gradle
gradle/lint.gradle
gradle/wrapper/gradle-wrapper.properties
sdk/build.gradle.kts

Proposal to revert Android Gradle Plugin upgrade for now. This breaks building from source as upstream projects are still using older syntax that is not compatible with the 4.2.2 version. To re-revert this commit, we should start bumping the android tools version from top down (common -> gl-native -> mapbox-maps-android). 
@mapbox/maps-android thoughts?

Revert AGP bump

---

app/src/androidTest/java/com/mapbox/maps/testapp/featurestate/FeatureStateTest.kt
app/src/main/java/com/mapbox/maps/testapp/examples/featurestate/FeatureStateActivity.kt
sdk/src/main/java/com/mapbox/maps/MapboxMap.kt

This PR add default value(null) for sourceLayerId property in getFeatureState API.

Add default value to improve usability of FeatureState APIs.

---

plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapper.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LayerSourceProviderTest.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapperTest.kt

Enable location-indicator model type for 3D location puck.
The 3D puck will always over (in front of) 3D layers (buildings, landmarks, custom layer) but behind hill (terrain).

[locationcomponent] Enable location-indicator model type for 3D location puck.

---

plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesConstants.kt
plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturePluginTest.kt

This PR changes the focal point of the fling gesture to match the motion event focal point (instead of center of screen). This is the equivalent of https://github.com/mapbox/mapbox-maps-android/pull/593 but for the fling event instead of scrolling. This PR does a cleanup of unused constants and simplifies the fling calculation. The used arbitrary boundary value of `VELOCITY_THRESHOLD_IGNORE_FLING` remains 1000 after testing multiple variations. Additionally, this PR cleans up the commented code of `cameraChangeDispatcher` which is a remains of the previous version of the SDK. 
https://user-images.githubusercontent.com/2151639/131368931-d8dec247-45c5-4fa6-bf50-2188539a44ea.mp4
https://user-images.githubusercontent.com/2151639/131368864-89eb6f0f-6674-4ffa-85b2-f49ab57ea63f.mp4

[gestures] use the gesture focal point for fling displacement

---

app/src/main/AndroidManifest.xml
extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/GeoJsonSourceTest.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt

Allowing initialisation of geojson source with empty data.
Fixes : #552 
https://user-images.githubusercontent.com/11589497/131514678-115a09fc-9c37-49dd-868b-9a91d2d2358a.mp4

Allow empty geojson source

---

sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt

Fixes: https://github.com/mapbox/mapbox-maps-android/issues/595
Preserve EGL setup on renderer stop. It was too much releasing the whole surface, it should be enough to release only `EGLSurface`. For situations when there's not enough resources while app is in the background and GL context will be lost / Android did provide us new surface we have the code to recreate EGL setup fully.
This fixes full map reloading when map is brought out from background.
Before:
https://user-images.githubusercontent.com/15800566/131340782-0d723033-8e8f-47fe-8feb-93ee3ff6b484.mp4
After: …

Preserve EGL setup on renderer stop

---

app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/CircleAnnotationManagerAndroidTest.kt
app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PointAnnotationManagerAndroidTest.kt
app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PolygonAnnotationManagerAndroidTest.kt
app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PolylineAnnotationManagerAndroidTest.kt
app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/CircleAnnotationActivity.kt
app/src/main/res/values/example_descriptions.xml
app/src/main/res/values/example_titles.xml
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManager.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt

In the past we will update all annotations while dragging, so the more annotations, the worse performance will be.
In this pr, a drag layer/source is introduced and will only refresh the drag annotation on this layer while dragging. This can improve drag performance dramatically.
The following is a compare test with 2000+ CircleAnnotations  
before:
https://user-images.githubusercontent.com/8577318/130190840-9b07876a-f1c0-48ae-80e5-583f8ad2e9f1.mp4
after
https://user-images.githubusercontent.com/8577318/130190854-a89298c …

Introduce drag layer/source for annotation plugin

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/mapbox/maps/testapp/examples/OngoingAnimationActivity.kt
app/src/main/res/values/example_descriptions.xml
app/src/main/res/values/example_titles.xml
plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/animator/CameraAnimator.kt
plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsChangeListenersTest.kt
plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt
sdk/src/androidTest/java/com/mapbox/maps/CameraAnimationsPluginTest.kt

Fixes: #596
The root of the problem is in the order of callbacks from ValueAnimators, that is different on Android 6. This PR changes core logic of applying animators making it easier to support and delegating updating accumulated `CameraOptions` to `Handler` instead of relying on update of "oldest" animator (which as said before is not working as expected on Android 6 and below). This should not affect camera animation in any way, the only possible drawback is applying camera changes on each animator update if user has added `ValueAnimator.AnimatorUpdateListener` instead of accumulating which should be a pretty rare use-case.

Fix camera animators ordering on Android 6 and lower

---

extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/ImageSource.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterDemSource.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterSource.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/VectorSource.kt

Update prefetch zoom delta documentation to match actual behavior:
```
When loading a map, if PrefetchZoomDelta is set to any number greater than 0, the map
will first request a tile at zoom level lower than zoom - delta, but so that
the zoom level is multiple of delta, in an attempt to display a full map at
lower resolution as quick as possible. It will get clamped at the tile source minimum zoom.
The default delta is 4.
```

Update prefetch zoom delta documentation to match actual behavior

---

extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/dsl/generated/ExpressionDsl.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/generated/Expression.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/expressions/generated/ExpressionTest.kt

This PR adds index-of and slice expression support to the expression DSL:
- [index-of](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#index-of)
- [slice](https://docs.mapbox.com/mapbox-gl-js/style-spec/expressions/#slice)

[style] add support for the index-of and slice expressions:

---

.circleci/config.yml

No need to setup mbx-ci for snapshot build as we set it in release job.

Remove mbx-ci setup in snapshot build

---

app/src/androidTest/java/com/mapbox/maps/testapp/LoadStyleCallbackTest.kt
app/src/main/AndroidManifest.xml
app/src/main/java/com/mapbox/maps/testapp/TestMapActivity.kt
sdk/src/main/java/com/mapbox/maps/MapController.kt
sdk/src/main/java/com/mapbox/maps/NativeObserver.kt
sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
sdk/src/test/java/com/mapbox/maps/NativeObserverTest.kt

Fixes: #618 
With these changes all MapboxMap callbacks will be called if a fragment/activity is stopped.
changelog: `<changelog>onStyleLoaded/onMapLoaded callbacks are called even if hosting fragment/activity is stopped</changelog>`

#618: continue to listen for event while map is stopped.

---

plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt

In this pr, we will remove the drag annotation from the drag source only when the map is idle and 1 sec later, so there will be no blink issue after drag.
Before:
https://user-images.githubusercontent.com/8577318/130190854-a89298ce-b63d-4b77-a6d6-29d754885c5e.mp4
After:
https://user-images.githubusercontent.com/8577318/133201118-aa534c68-1026-412a-be75-d981fb66223b.mp4

Fix drag annotation blink issue

---

sdk-base/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPlugin.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnMapIdleListener.kt

Fixes: #613 
This PR fixes some documentation issues on the OnMapIdleListener and CameraChangeListeners.

[docs] Fix documentation for OnMapIdleListener and CameraChangeListeners.

---

plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManager.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt

In the past, we haven't applied the properties to drag layer, so when dragging an annotation, the properties like test font will not keep the same as the original.
This pr applies all the properties to the drag layer to keep annotations the same while dragging.

Apply annotation manager properties to drag layer

---

app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/PointAnnotationActivity.kt
app/src/main/res/menu/menu_symbol.xml
app/src/main/res/values/strings.xml
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotation.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt

Fixes: #587 
This pr changes the way to generate `iconImage` value for PointAnnotation and update the check condition for updating bitmap.
https://user-images.githubusercontent.com/8577318/132826011-d2a99d8f-7597-4224-a263-48df7efe6795.mp4

Fix point annotation update bitmap affect others issue.

---

sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt

Fixes: #634 
Fixes: https://github.com/mapbox/mapbox-maps-android/issues/583
`onStyleLoaded` will only be triggered once for one style, so if users add a new source to style after style loaded, `onStyleLoaded` will never be invoked. And during the loading time for this new source, `getStyle` will return null because `style.isStyleLoaded` will be false.
This pr add a property `styleLoaded` to record wheter the style is loaded or not no matter how many sources or layers are added after style loaded.

Fix getStyle returns null after adding a source

---

app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/CircleAnnotationManagerAndroidTest.kt
app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PointAnnotationManagerAndroidTest.kt
app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PolygonAnnotationManagerAndroidTest.kt
app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PolylineAnnotationManagerAndroidTest.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotation.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotation.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotation.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManager.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotation.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManager.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/CircleAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PointAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolygonAnnotationManagerTest.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/generated/PolylineAnnotationManagerTest.kt

In the past, we ignore null values while users set them to annotation nullable properties so that users are not able to remove previously set properties.
In this pr, the properties will be removed from annotation if users set null value.

Enable annotations to set null value to nullable properties.

---

extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/GeoJsonSourceTest.kt
extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/VectorSourceTest.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/VectorSource.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/types/PromoteId.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSourceTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/VectorSourceTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/utils/PromoteIdTest.kt

This PR adds support for `promoteId` which allows a developer to promote a particular string / source-property to be the feature state id in features.
'promoteId' is a feature for geojson and vector sources. The feature allows to promote feature's property to a feature id, so that promoted id can be used with FeatureState API.

Add support for promoteId

---

sdk/src/main/java/com/mapbox/maps/MapAttributeParser.kt
sdk/src/main/java/com/mapbox/maps/MapInitOptions.kt
sdk/src/main/res-public/values/public.xml
sdk/src/main/res/values/attrs.xml
sdk/src/test/java/com/mapbox/maps/MapAttributeParserTest.kt
sdk/src/test/java/com/mapbox/maps/MapInitOptionsTest.kt

Expose optimizeForTerrain flag

Expose optimizeForTerrain flag

---

app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/SantaCatalinaActivity.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
sdk/src/main/java/com/mapbox/maps/renderer/WorkerHandlerThread.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxRendererTest.kt

Fix memory leak in renderer destroy.
Previously in surface mode we did not call releasing native renderer as `Activity.onDestroy` call is happening after Android system was sending `SurfaceHolder.Callback.surfaceDestroyed` when we have already stopped render thread.
Diagram from the profiler after the fix and several opening / closing activity with `MapView`

Fix memory leak in renderer destroy

---

sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLCore.kt

Fixes: #669 
Explicitly set no context when releasing EGL surface.
Tests could not be written as pixel-match tests required here.

#669: try to fix black screen on emulator

---

plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsExt.kt
sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt

Exception will be thrown when camera functionality trying to use but plugin was not added to MapView. Reported in #1118

Throw exception when camera plugin is missing

---

sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt

Fixes: https://github.com/mapbox/mapbox-maps-android/issues/684
It seems that at least on Android 8 system sends `SurfaceHolder.Callback.surfaceCreated` __earlier__ than even `Activity#onStart()` if stopping / resuming the map with a power button. That is leading to the deadlock in our renderer as we release lock when trying prepare EGL as we don't call it because thread is in paused state. Now this issue is fixed because we will be always trying to create EGL if we schedule `prepareRenderFrame` from surface creation (but not from other places).

Fix map render deadlock on Android 8 on power on button

---

plugin-attribution/src/main/java/com/mapbox/maps/plugin/attribution/AttributionViewImpl.kt
plugin-attribution/src/test/java/com/mapbox/maps/plugin/attribution/AttributionViewImplTest.kt
plugin-logo/src/main/java/com/mapbox/maps/plugin/logo/LogoViewImpl.kt

Created to resolve https://github.com/mapbox/mapbox-maps-android/issues/635
Before: 
After:

Fix attribution/logo jumble when RTL layout is configured

---

sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLCore.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt

Revisiting fix introduced in https://github.com/mapbox/mapbox-maps-android/pull/671.
Moved explicit setting `EGL10.NO_CONTEXT` from surface destroy to surface creation as surface destroy may be followed up by complete render thread destruction and in this case we still need valid EGL context to perform cleanup of GPU buffers / textures.

Move EGL no current context to surface creation

---

plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationProviderImpl.kt

This pr uses WeakReference to wrap context instance to prevent context leak.

Fix context leak in LocationProviderImpl.kt

---

sdk/src/main/java/com/mapbox/maps/MapController.kt
sdk/src/main/java/com/mapbox/maps/MapProvider.kt
sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
sdk/src/main/java/com/mapbox/maps/Snapshotter.kt
sdk/src/main/java/com/mapbox/maps/Style.kt
sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt
sdk/src/test/java/com/mapbox/maps/StyleTest.kt

Fix native memory leak by explicitly nulling map reference from renderer.
Additionally refactor code a bit by making `MapController` more responsible for storing main strong link to `MapInterface`.
Memory consumption looks now after the fix

Explicitly null map reference from renderer

---

app/src/androidTest/java/com/mapbox/maps/testapp/integration/surface/SurfaceViewOrientationChangeTest.kt
app/src/androidTest/java/com/mapbox/maps/testapp/integration/texture/TextureViewOrientationChangeTest.kt

Added waitForIdle in flaky instrumentation test before performing rotations.
With measures on emulator this command added around 800ms before changing rotation, so luckily it should solve the problem with full initialisation of views.

WaitForIdle before perform flaky instrumentation test

---

app/src/main/java/com/mapbox/maps/testapp/examples/terrain3D/SantaCatalinaActivity.kt
extension-localization/src/main/java/com/mapbox/maps/extension/localization/Localization.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/layers/LayerExt.kt

Currently `StyleMangerInterface.getLayerAs` has return type which is non-nullable.
It should be a nullable type.
Breaking change to get layer from style using `getLayerAs` function.
```
fun <T : Layer> StyleManagerInterface.getLayerAs(layerId: String): T {
@Suppress("UNCHECKED_CAST")
return getLayer(layerId) as T
}
```
Changed to 
```
inline fun <reified T : Layer> StyleManagerInterface.getLayerAs(layerId: String): T? {
val layer = getLayer(layerId)
if (layer !is T) {
Logger.e("StyleLayerPlugin", "Given layerId = …
```

fix getLayerAs return optional Layer type.

---

.circleci/config.yml
app/src/androidTest/java/com/mapbox/maps/testapp/LoadStyleCallbackTest.kt
app/src/main/java/com/mapbox/maps/testapp/examples/DebugModeActivity.kt
extension-androidauto/build.gradle.kts
sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnMapLoadErrorListener.kt
sdk/src/main/java/com/mapbox/maps/MapboxConfigurationException.kt
sdk/src/main/java/com/mapbox/maps/NativeObserver.kt
sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
sdk/src/main/java/com/mapbox/maps/extension/observable/model/MapLoadingErrorEventData.kt
sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/Error.kt
sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/Request.kt
sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/ResourceEventData.kt
sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/Response.kt
sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/eventdata/RequestDataSourceType.kt
sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/eventdata/RequestPriority.kt
sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/eventdata/RequestType.kt
sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/eventdata/ResponseErrorType.kt
sdk/src/main/java/com/mapbox/maps/extension/observable/resourcerequest/eventdata/ResponseSourceType.kt
sdk/src/test/java/com/mapbox/maps/NativeObserverTest.kt
sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt
sdk/src/test/java/com/mapbox/maps/extension/observable/MapboxMapTest.kt

This PR updates the map events data models, so they match the gl-native MapEvents.
List of changes:
* add optional `sourceId` and `tileId` in the `MapLoadingErrorEventData` and `OnMapLoadErrorListener`.
* make `response` in `ResourceEventData` optional.
* make `etag`, `modified`, `expires` inside resource request's `Response` optional.
* add `DataSourceType` , `RequestPriority` , `RequestType` ,`ResponseErrorType` , `ResponseSourceType` enum for `resource-request` event which conform to java docs from gl-native.

[observable-extension] Update map events data models.

---

sdk/src/main/java/com/mapbox/maps/MapController.kt
sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt

In this PR has been changed order of methods called on lifecycle event onStart. Now plugins will receive onStart after style has been loaded. This reorder prevent of loosing callbacks from StyleObserver when callback were added before style starts loading.
User with styleUri attribute in XML will have all plugins started correctly after style has been loaded. Before in this case it was the issue reported here: #641

Call plugin onStart after start loading style

---

CHANGELOG.md
extension-localization/README.md
extension-style/README.md
plugin-animation/README.md
plugin-annotation/README.md
plugin-attribution/README.md
plugin-compass/README.md
plugin-gestures/README.md
plugin-lifecycle/README.md
plugin-locationcomponent/README.md
plugin-logo/README.md
plugin-overlay/README.md
plugin-scalebar/README.md

v10.0.0 changelog

---

.circleci/config.yml

Remove `build-sdk-from-source` CI job because its duplicate [`build-sdk-release`](https://github.com/mapbox/mapbox-maps-android/blob/main/.circleci/config.yml#L475)

remove useless CI job build-sdk-from-source

---

plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarImpl.kt

Fixes: #809 
Scale bar uses the half of mapview width as its width, so the right part will be cut off if set the ratio bigger than o.5.
This pr applies ratio to scalebar and make the width changes with ratio.
The following picture shows the width of scalebar when setting ratio to 1.0

Apply ratio to the width of scalebar

---

app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationShowcaseActivity.kt
sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotationManager.kt
sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotationManagerImpl.kt

Nice idea from @yunikkk - in order to simplify maintaining async inflater which we include only as `compileOnly` - we move it out to client code.

View annotations: move async inflater instance out of SDK

---

plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarImpl.kt

The texts in scalebar are missing on Android 6 devices. The root cause is `drawPath` does not work on these devices.
This PR replace `drawPath` with drawText to fix this issue.
The following screenshot is taken from emulator of API 23

Fix scale bar texts missing on devices with Android 6 issue

---

plugin-lifecycle/src/main/java/com/mapbox/maps/plugin/lifecycle/MapboxLifecyclePluginImpl.kt
plugin-lifecycle/src/test/java/com/mapbox/common/ShadowLogger.java
plugin-lifecycle/src/test/java/com/mapbox/maps/extension/lifecycle/MapboxLifecyclePluginImplTest.kt

This PR replaces ComponentCallbacks2 instead ComponentCallbacks and hook into onTrimMemory. As it has more granular control and works better for Android Q and later according to [Android memory and games (Google I/O'19)](https://www.youtube.com/watch?v=Do7oYWwOXTk)

[lifecycle-plugin] Use ComponentCallbacks2 instead ComponentCallbacks and hook into onTrimMemory.

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/mapbox/maps/testapp/examples/style/TileJsonActivity.kt
app/src/main/res/values/example_descriptions.xml
app/src/main/res/values/example_titles.xml

While validating if something was correctly working with tilejson, I noticed we didn't have any code using the TileSet API in an actual map example. The added example uses OSM based raster tiles through tileset configuration of a RasterSource and visualising it with a RasterLayer.

Add example that uses tilejson through the tileset class.

---

plugin-scalebar/build.gradle.kts
plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarImpl.kt
plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginImpl.kt
plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/ScaleBarImplTest.kt
plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginTest.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBar.kt

| <img src="https://user-images.githubusercontent.com/8577318/141930496-31bf31bd-a0f6-4c63-a4ac-20af094d37ce.png"/> | <img src="https://user-images.githubusercontent.com/8577318/141930349-a8b1f73c-d465-4179-97f5-5f7bd2c9224b.png"/> |
This PR fixes Scale bar texts overlap and clipped issue and extract the logic of calculating width and height into a method to add test for it.

Fix Scale bar texts overlap and clipped issue

---

extension-style/src/main/java/com/mapbox/maps/extension/style/layers/LayerExt.kt
sdk/src/main/java/com/mapbox/maps/Style.kt

This PR promotes persistent style layer APIs to be production-ready. And removes the `MapboxExperimental` annotation from the related APIs.

[style] Promote persistent style layer APIs to be production-ready.

---

app/src/main/java/com/mapbox/maps/testapp/examples/GesturesActivity.kt
plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt

Update maximum allowed angle between touch points to qualify it as a shove gesture.
| <video src="https://user-images.githubusercontent.com/11589497/142613735-83b9b8c5-4c61-4382-9e37-bb512ca6ca17.mp4" width = 250/> | <video src="https://user-images.githubusercontent.com/11589497/142613750-315b186c-8221-44d4-b28c-432c5bc78fce.mp4" width = 250/> |

[Gesture] Update default shove gesture angle

---

sdk/src/androidTest/java/com/mapbox/maps/TestUtils.kt
sdk/src/androidTest/java/com/mapbox/maps/ViewAnnotationTest.kt
sdk/src/androidTest/res/layout/view_annotation.xml

Port https://github.com/mapbox/mapbox-maps-android/pull/894 so that if instrument test for potential view annotation bug will arrive - it could be easily added here without any porblems.

Port view annotations: add instrument tests

---

build.gradle.kts
settings.gradle.kts

With dokka version 1.4.10.2, transitive dependencies not present on mavencentral were failing. this pr fixes the ci job issue by adding jcenter to build file.

revert jcenter to fix ci job

---

extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/listeners/OnSourceDataLoadedListener.kt

- When applying data to geojson source, we should listen to `SOURCE_DATA_LOADED` events.

[Doc] Fix geojson doc for listener events

---

sdk-base/src/main/java/com/mapbox/maps/plugin/attribution/generated/AttributionSettings.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/compass/generated/CompassSettings.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettings.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/logo/generated/LogoSettings.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/scalebar/generated/ScaleBarSettings.kt

The unit of dimension properties in plugin settings are not clear, this pr update the jave to make it clear to users that they are in pixel.

Update the java doc in plugin settings to clarify the margin properties are in pixel

---

app/src/main/java/com/mapbox/maps/testapp/examples/RawExpressionActivity.kt

This PR updates the RawExpressionExample to use high level style extension instead of low level APIs.

[testapp] Update raw expression example to use style extension.

---

app/src/main/java/com/mapbox/maps/testapp/examples/style/TileJsonActivity.kt
app/src/main/res/menu/menu_tilejson.xml
app/src/main/res/values/strings.xml
extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/RasterDemSourceTest.kt
extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/RasterSourceTest.kt
extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/sources/generated/VectorSourceTest.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterDemSource.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/RasterSource.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/VectorSource.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/RasterDemSourceTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/RasterSourceTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/sources/generated/VectorSourceTest.kt

Introduce `tile-requests-delay` and `tile-network-requests-delay` APIs to set delay in tile requests for vector, raster and raster-dem sources.
The `tile-requests-delay` property:
```
/**
* For vector, raster and raster-dem sources, this property sets the tile requests delay.
*
* The given delay comes in action only during an ongoing animation or gestures.
* It helps to avoid loading, parsing and rendering of the "transient" tiles and
* thus to improve the rendering performance, especially on low-end devices.
*
* The delay is represented by a Double value in milliseconds.
*/
```
The `tile-network-requests-delay` property:
```
/**
* For vector, raster and raster-dem sources, this property sets the tile network requests delay.
*
* The given delay comes in action only during an ongoing …
```

Add tile requests delay apis

---

gradle/jacoco.gradle

Enable all output report formats for jacoco tool

enable all output report formats

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/AnnotationWithCalloutActivity.kt
app/src/main/res/values/example_descriptions.xml
app/src/main/res/values/example_titles.xml
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/annotation/Annotation.kt

Expose unique feature identifier for all annotations created by annotation plugin. This feature id is used when preparing a `Feature` that backs up annotation. This feature id could now be used to connect annotation with view annotation.
Prepare an example of annotation usage (drawing a marker) and associated view annotation.
https://user-images.githubusercontent.com/15800566/146143453-be75920c-9e70-41ba-8e88-873ecb69acfc.mp4

Add feature id to annotations; prepare showcase of callout annotations

---

sdk/src/main/java/com/mapbox/maps/Snapshotter.kt

This PR adds the function to send turnstiles for snapshotter.

Send turnstiles for Snapshotter usage

---

extension-localization/src/main/java/com/mapbox/maps/extension/localization/Localization.kt
extension-localization/src/main/java/com/mapbox/maps/extension/localization/SupportedLanguages.kt

lower the bar for localizing a symbol layer, allow more sources besides streets-v7/v8. Align logic with [iOS implementation](https://github.com/mapbox/mapbox-maps-ios/blob/main/Sources/MapboxMaps/Style/Style+Localization.swift#L9)
Developers are now able to localize more layers that aren't associated with Mapbox Streets v7/v8.

[localization] lower the bar for localizing a symbol layer

---

sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt

Unsubscribe MapboxRenderer from RENDER_FRAME_FINISHED events after readyForSnapshot is set.
It is a minor performance optimization to reduce cpu load on each frame. The change became less important after getRenderFrameFinishedEventData was implemented without json operations but is still relevant.
There is no change in behavior.

MapboxRenderer: unsubscribe from RENDER_FRAME_FINISHED after the first event

---

app/src/main/java/com/mapbox/maps/testapp/examples/viewport/AdvancedViewportGesturesExample.kt
app/src/main/java/com/mapbox/maps/testapp/utils/NavigationSimulator.kt
plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/ViewportPluginImpl.kt
plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/state/FollowingViewportStateImpl.kt
plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/state/OverviewViewportStateImpl.kt
plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/transition/MapboxViewportTransitionFactory.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/ViewportConstants.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/ViewportPlugin.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/FollowingViewportStateOptions.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/OverviewViewportStateOptions.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/ViewportOptions.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/FollowingViewportState.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/OverviewViewportState.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/ViewportState.kt
sdk-base/src/test/java/com/mapbox/maps/EqualsHashCodeTest.kt

This PR aligns the naming of the viewport options, and make the linear transition take the transition duration directly.
This PR also removed the states/addState/removeState APIs and updated documentation accordingly.

[viewport] Align viewport options naming and remove add/remove state APIs.

---

sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt
sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotation.kt
sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerTest.kt

When removing single view annotation or actually calling complete destroy wrong ref was used for view tree observer which caused leak in some scenarios (e.g. when using fragments).
Now this is fixed by revisiting an approach to use correct moments of time to register / unregister global layout listener under the hood.
Fixes: #1020 

Fix leak in view tree observer for view annotations

---

plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/state/FollowingViewportStateImpl.kt
plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/state/FollowingViewportStateImplTest.kt

This PR fixes an issue that causes transition to following viewport state not being fired when the bearing is set to constant.

[viewport] Fix an issue that causes transition not fired when bearing is set to constant.

---

plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/state/FollowingViewportStateImpl.kt
plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/state/FollowingViewportStateImplTest.kt

This PR ports viewport fix #1064 to the v10.3 release branch.

Port viewport fix #1064

---

plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt

Currently, in order to keep the 3d puck visible across all zoom levels, we use scale expression to calculate the scale according to the current zoom based on two anchor `maxZoom` and `minZoom` from coordinate bounds, the issue is if CoordinateBounds changes, the 3d puck size also change with it. 
this pr fixes this issue using a constant value for `minZoom` and `maxZoom`. Keeping the constants same as before so existing users don't have to scale the puck.

fix 3d puck scaling issue

---

plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt

port 3d puck scaling fix (#1067)

---

plugin-viewport/README.md
plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/ViewportPluginImpl.kt
plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/state/FollowPuckViewportStateImpl.kt
plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/state/OverviewViewportStateImpl.kt
plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/ViewportPluginImplTest.kt
plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/state/FollowPuckViewportStateImplTest.kt
plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/state/OverviewViewportStateImplTest.kt
plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/MapboxViewportTransitionFactoryTest.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/CompletionListener.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/ViewportConstants.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/ViewportStatus.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/ViewportStatusObserver.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/DefaultViewportTransitionOptions.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/FollowPuckViewportStateBearing.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/FollowPuckViewportStateOptions.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/OverviewViewportStateOptions.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/ViewportOptions.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/ViewportStatusChangeReason.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/FollowPuckViewportState.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/OverviewViewportState.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/ViewportState.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/state/ViewportStateDataObserver.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransition.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/transition/ViewportTransition.kt

This PR aligns the viewport public API surface with iOS, changes include:

[viewport] Align public API surface with iOS.

---

CHANGELOG.md
sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLConfigChooser.kt

At least Google simulators seem not to support MSAA option when configuring EGL. This will result in map not being rendered at all. Now logic is introduced to try double down `EGL_SAMPLE` value in a loop until either supported MSAA config will be found (fixing an issue of map not being rendered even on physical device when setting huge MSAA value) or EGL will be configured without MSAA (fixing an issue with emulators).
Fixes: #1076 

Fix map not rendering on emulators when MSAA is enabled

---

CHANGELOG.md
sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLConfigChooser.kt

At least Google simulators seem not to support MSAA option when configuring EGL. This will result in map not being rendered at all. Now logic is introduced to try double down `EGL_SAMPLE` value in a loop until either supported MSAA config will be found (fixing an issue of map not being rendered even on physical device when setting huge MSAA value) or EGL will be configured without MSAA (fixing an issue with emulators).
Port for https://github.com/mapbox/mapbox-maps-android/pull/1077

V10.3 port: Fix map not rendering on emulators when MSAA is enabled

---

sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt

When limiting rendering FPS with `MapView#setMaxFps(fps)` last render call will be skipped leading to map state being inconsistent (not all tiles are loaded, not all labels are placed, layers are not added to the map).
Fixes: https://github.com/mapbox/mapbox-maps-android/issues/1098
Fixes: https://github.com/mapbox/mapbox-maps-android/issues/1097
Fixes: https://github.com/mapbox/mapbox-maps-android/issues/1099

Fix issue with map rendering when limiting max FPS

---

CHANGELOG.md
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImplTest.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt

This PR fixes possible crash with Location persistent layer being added twice. 
This had happened [for 1tap](https://github.com/mapbox/1tap-android/issues/1594#issuecomment-1022591586), for example. 

Don't call initialize twice when getStyle callback fires several times.

---

CHANGELOG.md
buildSrc/src/main/kotlin/Project.kt

This PR updates gl-native to v10.3.1
* Avoid possible crash at program exit caused by dummy tracer accessed after destruction. ([#1116](https://github.com/mapbox/mapbox-maps-android/pull/1116))
* Fix crash for the case when a map event is handled by an Observer of a destructed map. ([#1116 ](https://github.com/mapbox/mapbox-maps-android/pull/1116))

[Dependencies] Bump gl-native to v10.3.1

---

scripts/ci-circleci-start-pipeline.py

This PR allows to invoke internal CI with datetime to have more granular control over the generated datapoints (unlocks retroactively capturing data). 

[ci] add support for invoking internal CI with a datetime

---

plugin-attribution/src/main/java/com/mapbox/maps/plugin/attribution/AttributionDialogManagerImpl.kt
sdk/src/main/java/com/mapbox/maps/attribution/AttributionParser.kt
sdk/src/test/java/com/mapbox/maps/attribution/AttributionParseTest.java

this pr port Attribution parser fix to v10.3

[port] Show attribution present in TileJson source in attribution #1087

---

CHANGELOG.md
sdk-base/src/main/java/com/mapbox/maps/plugin/delegates/MapStyleStateDelegate.kt
sdk/src/androidTest/java/com/mapbox/maps/StyleLoadTest.kt
sdk/src/main/java/com/mapbox/maps/MapController.kt
sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt

Problem this PR addresses : location puck is not displayed after style load #321, #1048.
Background context  : at #300 the logic that clears `style loaded` callbacks added with `mapboxMap.getStyle` / `mapboxMap.loadStyle` was introduced. 
However, for the `getStyle` the behaviour doesn't feel right. `getStyle` name doesn't suggest that it depends on the specific `loadStyle` call, instead it would be natural to return ANY style whenever it is loaded.
Existing `getStyle` implementation also leads to the issues (mentioned above) with our own LocationComponent. If location component was triggered before style load was started (possible if `MapInitOptions.styleUri = null` or style fails to load), it needs style and waits for it to appear at `getStyle` (in couple places, e.g. …

Split callbacks originating on getStyle and loadStyle requests.

---

.circleci/config.yml
.github/pull_request_template.md
.gitignore
build.gradle.kts
buildSrc/src/main/kotlin/Project.kt
extension-androidauto/api/extension-androidauto.api
extension-localization/api/extension-localization.api
extension-style/api/extension-style.api
mapbox-lint/api/mapbox-lint.api
module-telemetry/api/module-telemetry.api
plugin-animation/api/plugin-animation.api
plugin-annotation/api/plugin-annotation.api
plugin-attribution/api/plugin-attribution.api
plugin-compass/api/plugin-compass.api
plugin-gestures/api/plugin-gestures.api
plugin-lifecycle/api/plugin-lifecycle.api
plugin-locationcomponent/api/plugin-locationcomponent.api
plugin-logo/api/plugin-logo.api
plugin-overlay/api/plugin-overlay.api
plugin-scalebar/api/plugin-scalebar.api
plugin-viewport/api/plugin-viewport.api
sdk-base/api/sdk-base.api
sdk/api/sdk.api

This PR:
* Adds [binary compatibility validator](https://github.com/Kotlin/binary-compatibility-validator
) integration to the Maps SDK.
* Commited the latest public API signature.
* Add CI to validate public API changes.
Here's the suggested [**Workflow**](https://github.com/Kotlin/binary-compatibility-validator#workflow):
When starting to validate your library public API, we recommend the following workflow:
- Preparation phase (one-time action):
* As the first step, apply the plugin, configure it and execute `apiDump`.
* Validate your public API manually.
* Commit `.api` files to your VCS.
* At this moment, default `check` task will validate public API along with test run and will fail 
the build if API differs.
- Regular workflow
* When doing code changes that do not imply any changes …

Integrate Kotlin binary compatibility validator.

---

CHANGELOG.md
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/DefaultLocationProvider.kt

This PR adds a new class `CurrentLocationEngineCallback` to hold `LocationProviderImpl` instance with a weak reference to avoid memory leak issue.
Invoke `removeCompassListener` when there is no `LocationConsumer` registed.

Fix memory leak in location component.

---

CHANGELOG.md
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerWrapper.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerWrapperTest.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt

The fix resolves the issue with puck bearing, that can jump to zero on when location component settings are changed. The wrong animation looks in the following way : 
https://user-images.githubusercontent.com/2265924/143263474-a9588dc7-9327-4518-917b-103ffaac44ee.mp4
There are two issues causing such behaviour. 
First - we add layer on the map _before_ applying current bearing value. Renderer, which is running in parallel on the background thread, may (and sometimes does) actually run rendering before bearing is applied, thus jumping to the default (0) bearing. 
Second - `bearing-transition` property is not set and defaults to animating during 300 milliseconds. I'm not actually sure about this one since after the first fix it seems not necessary, but iOS for example resets this to zero …

Fix bearing of the puck being reset on settings change.

---

.circleci/config.yml
CHANGELOG.md
android-auto-app/build.gradle.kts
app/build.gradle.kts
buildSrc/src/main/kotlin/Project.kt
extension-style-app/build.gradle.kts
sdk/build.gradle.kts
sdk/src/androidTest/java/com/mapbox/maps/ViewAnnotationTest.kt

Bump gl-native to 10.4.0-beta.2
Revert common.so changes.

[Deps] Bump gl native 10.4.0 beta.2

---

CHANGELOG.md
app/src/main/java/com/mapbox/maps/testapp/examples/CircleLayerClusteringActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java
extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceCallbackTest.kt
sdk/api/sdk.api
sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
sdk/src/main/java/com/mapbox/maps/Style.kt
sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt

Introduce new function `MapboxMap.setStyleTransition` and deprecate `Style.setStyleTransition`. 
Main idea is that we need to apply transition options in the correct moment of time _during_ style is loading while our current API allows to actually operate on `Style` object when style is already fully loaded.
Please take a look at the visuals, what we do there is:
- load first streets style with following options `TransitionOptions.Builder().duration(0).build()`
- wait for 2 seconds and load dark style with `TransitionOptions.Builder().duration(5000).delay(3000).build()`
Following pseudo-code:
```
loadStyleUri(Style.MAPBOX_STREETS) { firstStyle ->
firstStyle.styleTransition = TransitionOptions.Builder()
.duration(0)
.build()
}
```
should be replaced with:
```
loadStyleUri(
styleUri = …
```

Add map function to apply style transition during style load

---

sdk/api/sdk.api
sdk/src/main/java/com/mapbox/maps/renderer/widget/Widget.kt

This PR makes constructor internal to indicate more clearly that this class cannot be implemented outside of our module. Previously it was abstract and contained internal property `renderer` thus could not be implemented in the other modules anyways, but it was less explicit and metalava treated this an error. 
A bit of motivation behind `Widget` class being internal and not intended for general use. 
The only way intended for use now is to instantiate or inherit [BitmapWidget](https://github.com/mapbox/mapbox-maps-android/blob/main/sdk/src/main/java/com/mapbox/maps/renderer/widget/BitmapWidget.kt), that provides correct [renderer](https://github.com/mapbox/mapbox-maps-android/blob/main/sdk/src/main/java/com/mapbox/maps/renderer/widget/BitmapWidgetRenderer.kt) for the Widget. 
There's no …

Fix custom widget metalava incompatibility

---

scripts/java-api-check.sh

CI job `verify-api-revapi ` keeps failing now with the output like 
```
old: field com.mapbox.maps.plugin.annotation.BuildConfig.VERSION_CODE
new: <none>
java.field.removedWithConstant: Field with constant value has been removed.
SEMANTIC: POTENTIALLY_BREAKING, SOURCE: BREAKING, BINARY: NON_BREAKING
```
The reason for this is we bumped gradle and java after 10.3.
This pr temporarily applies the last release to check the api, need to roll it back after v10.4 is released. 

Apply the last release to check api

---

scripts/update-android-docs.sh

According to the discussions at https://github.com/mapbox/android-docs/pull/2034#discussion_r814279568 version number to the new version in android-docs repo is now added to the end of the list every time instead of replacing previous when alpha-beta-rc is published.
This is same to the way navigation supports versions - https://github.com/mapbox/android-docs/blob/publisher-production/src/data/navigation-version-numbers.json, results in all the versions above the current public one displayed in the prereleases section at https://docs.mapbox.com/android/navigation/api-reference/ …

Append version every release

---

CHANGELOG.md
extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/expressions/ExpressionTest.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/generated/Expression.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/expressions/LiteralExpressionTest.kt

This PR ports #1204 
Fix match expression DSL when label list is used.

Port Match expression fix

---

CHANGELOG.md
app/src/androidTest/java/com/mapbox/maps/testapp/BaseMapTest.kt
app/src/androidTest/java/com/mapbox/maps/testapp/annotation/UpdateAnnotationTest.kt
app/src/androidTest/java/com/mapbox/maps/testapp/viewport/ViewportPluginTest.kt
app/src/main/java/com/mapbox/maps/testapp/examples/DebugModeActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/NinePatchImageActivity.kt
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImpl.kt
plugin-annotation/src/test/java/com/mapbox/maps/plugin/annotation/AnnotationPluginImplTest.kt
plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
sdk-base/api/metalava.txt
sdk-base/src/main/java/com/mapbox/maps/MapboxExceptions.kt
sdk/api/metalava.txt
sdk/api/sdk.api
sdk/src/androidTest/java/com/mapbox/maps/BaseAnimationMapTest.kt
sdk/src/androidTest/java/com/mapbox/maps/OfflineTest.kt
sdk/src/androidTest/java/com/mapbox/maps/StyleLoadTest.kt
sdk/src/androidTest/java/com/mapbox/maps/ViewAnnotationTest.kt
sdk/src/main/java/com/mapbox/maps/MapController.kt
sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
sdk/src/main/java/com/mapbox/maps/Style.kt
sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
sdk/src/test/java/com/mapbox/maps/StyleTest.kt

In `MapboxMap` and `Style`, the reference to `nativeMap` will be reset to null in onDestroy, so any method calls related to `nativeMap` will throw `MapboxMapMemoryLeakException`
`tearDown` method in BaseMapTest.kt is removed to avoid duplicate method call to `MapboxMap.onDestroy()` as it will be triggerd by lifecycle plugin.
Automatically unsubscribe all observers in MapboxMap when `MapboxMap.onDestroy()` is invoked.

Reset nativeMap to null in onDestroy

---

.github/pull_request_template.md

Refresh changelog management description in the pr template.

---

CHANGELOG.md
extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/LocationIndicatorLayerTest.kt
extension-style/api/extension-style.api
extension-style/api/metalava.txt
extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LocationIndicatorLayer.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/LocationIndicatorLayerTest.kt

Generated property bearing-transition

Generate bearing-transition style property.

---

android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarCameraController.kt
android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/MapScreen.kt
android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/testing/CarJavaInterfaceChecker.java
extension-androidauto/api/extension-androidauto.api
extension-androidauto/api/metalava.txt
extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceCallback.kt
extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceOwner.kt
extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/DefaultMapboxCarMapGestureHandler.kt
extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMap.kt
extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapGestureHandler.kt
extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapObserver.kt
extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceOwnerTest.kt
extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/DefaultMapboxCarMapGestureHandlerTest.kt
extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/MapboxCarMapTest.kt

Resolves https://github.com/mapbox/mapbox-maps-android/issues/1152
The issue it resolves has all the details. This is refining the gesture detector api for android auto. Currently, every `MapboxCarMapObserver` is a gesture detector; this pull request makes it so there can only be a single gesture detector at a time. Below is an example of usage. A downstream developer can implement their own gestures.
``` kotlin
class MyGestureHandler = object : DefaultMapboxCarMapGestureHandler() {
override fun onScroll(
carMapSurface: MapboxCarMapSurface,
visibleCenter: ScreenCoordinate,
distanceX: Float,
distanceY: Float
) {
// My own function that will do something, such as disabling location following
disableLocationFollowing()
// Continue to tell the default gestures to move the map …
```

[Android Auto] Refactor gesture detection interface

---

CHANGELOG.md
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/generated/GeoJsonSource.kt
sdk-base/api/metalava.txt
sdk-base/api/sdk-base.api
sdk-base/src/main/java/com/mapbox/maps/MapboxExceptions.kt

When applying data to geojson `ConcurrentModificationException` may occur if underlying collections are mutated. We introduce new `MapboxConcurrentGeometryModificationException` extending `ConcurrentModificationException` that contains more data helping to find out what source exactly was not updated and some instructions how that could be fixed.
Sample output:
```
2022-03-31 14:47:49.965 428-559/com.mapbox.maps.testapp E/AndroidRuntime: FATAL EXCEPTION: GEOJSON_PARSER
Process: com.mapbox.maps.testapp, PID: 428
com.mapbox.maps.MapboxConcurrentGeometryModificationException: While applying FeatureCollection to geojson source with id="DRIVING_ROUTE_POLYLINE_SOURCE_ID" some collection was mutated which is not allowed as data parsing happens on another thread.
Please make sure all collections …
```

Throw specific Mapbox exception when geojson data is mutated

---

.circleci/config.yml
DEVELOPING.md
Makefile
build.gradle.kts
buildSrc/src/main/kotlin/Project.kt
extension-androidauto/build.gradle.kts
extension-androidauto/gradle.properties
gradle/artifact-settings.gradle
gradle/sdk-registry.gradle

This PR adds scripts and CI integration to publish Android Auto separate from the main SDK.
The SDK, the default extensions and the default plugins use the same versioning, which is defined by the
`VERSION_NAME` variable in the root project's gradle.properties. However, the project also allows to use
separate versioning for individual subprojects/modules. Subprojects can define the `MODULE_VERSION_NAME`
in the subproject-level gradle.properties to overwrite the `VERSION_NAME` defined in the root project.
Currently, the only module that uses its own versioning is the `extension-androidauto` and it's published
separately from the main SDK.
The CI is setup to publish new releases when new tag that follows the release tag pattern is created.
* To publish a Maps SDK release with all the …

Enable publish Android Auto separately from the main sdk.

---

CHANGELOG.md
LICENSE.md
buildSrc/src/main/kotlin/Project.kt
sdk/api/sdk.api
sdk/src/androidTest/java/com/mapbox/maps/GlobeIntegrationTest.kt
sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt
sdk/src/main/java/com/mapbox/maps/Style.kt
sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
sdk/src/test/java/com/mapbox/maps/NativeMapTest.kt
sdk/src/test/java/com/mapbox/maps/StyleTest.kt

update gl-native to 10.5.0-beta.1, common to v21.3.0-beta.2
* Map projection API moved from Map to Style, in order to allow specifying the map projection in the style. ([#1244](https://github.com/mapbox/mapbox-maps-android/pull/1244))
* Automatic transition between the globe and mercator projection updated to appear visually more subtle. ([#1244](https://github.com/mapbox/mapbox-maps-android/pull/1244))
* Map render call optimized further by further reducing computational overhead. ([#1244](https://github.com/mapbox/mapbox-maps-android/pull/1244))
* Layer properties transitions performance improved if the layer is transitioning to the same constant value or if transitioning from/to data-driven property. ([#1244](https://github.com/mapbox/mapbox-maps-android/pull/1244))
* New line layer …

update gl-native to 10.5.0-beta.1, common to v21.3.0-beta.2

---

CHANGELOG.md
sdk-base/src/main/java/com/mapbox/maps/plugin/viewport/data/FollowPuckViewportStateOptions.kt

This PR deprecates `FollowPuckViewportStateOptions.animationDurationMs`, the transition will will handled properly by the Viewport plugin internally.

Deprecate FollowPuckViewportStateOptions.animationDurationMs.

---

CHANGELOG.md
sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotationManager.kt

Mark View Annotation API as non-experimental

---

CHANGELOG.md
plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransitionImpl.kt
plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransitionImplTest.kt

This PR fixes the camera jump issue when default transition is canceled.
| <video src="https://user-images.githubusercontent.com/2764714/162010950-3240a6b1-f2c0-43ec-af33-b588d2ebdf33.mp4" width = 250/> | <video src="https://user-images.githubusercontent.com/2764714/162010890-b789b5f6-a4ad-4d87-bb8b-bc8044b73579.mp4" width = 250/> |

[viewport] Fix camera jump when default transition is canceled.

---

extension-style/src/main/java/com/mapbox/maps/extension/style/projection/generated/Projection.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/projection/generated/ProjectionExt.kt

When calling `Style.getProjection()` for globe view constantly (like in our example) - we will keep setting the same globe projection to core leading to flickering. 
As no other properties are available for projection right now - we simply not call `bindTo` during getter to fix this.

Fix globe flickering when calling getter

---

CHANGELOG.md
plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt
sdk/src/androidTest/java/com/mapbox/maps/CameraAnimationsPluginTest.kt

In some very specific cases when using paddings close to screen size and high zoom `flyTo` could have produced native exception:
```
java.lang.Error: latitude must not be NaN
```
Fix this issue by treating infinite values in algorithm properly.

Fix latitude being NaN during flyTo

---

CHANGELOG.md
sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt

Android counterpart of https://github.com/mapbox/mapbox-maps-ios/pull/1195
Currently we cannot guarantee that the returned point of `MapboxMap#pixelForCoordinate` is valid outside of the MapView bounds. Originally the underlying implementation was designed to convert points only on the visible parts of the map. Until the GL-Native implementation is reworked we have to limit the public API.

Limit  to the bounds of MapView.

---

CHANGELOG.md
plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt

This PR enables two finger pan gesture.
| <video src="https://user-images.githubusercontent.com/2764714/163360716-b9b18083-6a04-492d-8215-b120a954b06a.mp4" width = 250/> | <video src="https://user-images.githubusercontent.com/2764714/163360845-10f28fef-a003-42d9-b46f-dd957da98c98.mp4" width = 250/> |

[gestures] Enable two finger pan gesture.

---

CHANGELOG.md
buildSrc/src/main/kotlin/Project.kt

This PR bumps the Mapbox Android base library version to v0.8.0, to support incremental annotation processing.
More context in https://github.com/mapbox/mapbox-base-android/pull/69

[deps] Bump Android base library to v0.8.0, to support incremental annotation processing.

---

CHANGELOG.md
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/Source.kt
sdk/src/main/java/com/mapbox/maps/Style.kt

Due to nulling delegate explicitly when `Style` is not valid anymore we faced the situation that geojson updates were skipped after style was changed but only _when using persistent layers_. Now that's fixed and also as the temp solution we do not write warnings for using invalid style object in order not to confuse the users - this will be revisited later as it requires a bit deeper thinking how to treat style object when using persistent layers.

Fix geojson missing updates with persistent layer after style change

---

CHANGELOG.md
plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarImpl.kt
plugin-scalebar/src/main/java/com/mapbox/maps/plugin/scalebar/ScaleBarPluginImpl.kt
plugin-scalebar/src/test/java/com/mapbox/maps/plugin/scalebar/ScaleBarImplTest.kt

Instead of minus `INTERNAL_PADDING_DP` while calculating unitBarWidth, now add `INTERNAL_PADDING_DP` to the width of scalebar to avoid the issue that scalebar is a litter shorter than it should be.
Invoke `invalidateScaleBar()` while updating scalebar settings to make sure it updates to the new state.

Remove padding while calculating unitBarWidth; invalidateScaleBar while applySettings

---

CHANGELOG.md
plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt

Fixes https://github.com/mapbox/mapbox-maps-android/issues/1312
This PR keeps the original owner for animators when using `CameraAnimationsPlugin.playAnimatorsTogether` and `CameraAnimationsPlugin.playAnimatorsSequentially`. 
The original owner is useful, as we detect whether the animation is driven by Gestures in the viewport plugin.

Keep the original animator owner for playAnimatorsTogether and playAnimatorsSequentially.

---

CHANGELOG.md
sdk/src/main/java/com/mapbox/maps/NativeObserver.kt

Trigger exception coming from observer callback code path to trigger on the main thread. 
This avoids raising a native crash with pending java exception.
```
2022-05-18 09:31:50.043 21267-21267/com.mapbox.maps.testapp W/System.err: java.lang.RuntimeException: HELLO WORLD
2022-05-18 09:31:50.043 21267-21267/com.mapbox.maps.testapp W/System.err:     at com.mapbox.maps.testapp.examples.SimpleMapActivity.onCreate$lambda-0(SimpleMapActivity.kt:21)
2022-05-18 09:31:50.043 21267-21267/com.mapbox.maps.testapp W/System.err:     at com.mapbox.maps.testapp.examples.SimpleMapActivity.$r8$lambda$XCnBnNpGBwvzAsgkwLSb_B8XL60(Unknown Source:0)
2022-05-18 09:31:50.043 21267-21267/com.mapbox.maps.testapp W/System.err:     at com.mapbox.maps.testapp.examples.SimpleMapActivity$$ExternalSyntheticLambda0.onStyl …
```

Rethrow exception on main thread for observer callback code paths

---

CHANGELOG.md
plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt

Fix crash due to invalid focal point when panning the map by skipping camera movement logic in case focal point returned from `MoveGestureDetector` is invalid meaning that X or Y are non-finite values.

Fix crash due to invalid focal point when panning the map

---

CHANGELOG.md
sdk/api/metalava.txt
sdk/api/sdk.api
sdk/src/androidTest/java/com/mapbox/maps/MapboxMapIntegrationTest.kt
sdk/src/main/java/com/mapbox/maps/MapView.kt
sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLCore.kt

Even before creating an instance of `MapView` it's not possible to validate if 3D terrain will be supported on given device:
```kotlin
val supported = MapView.isTerrainRenderingSupported()
```

Add static method to validate if 3D terrain is supported

---

sdk/src/main/java/com/mapbox/maps/MapController.kt
sdk/src/main/java/com/mapbox/maps/MapProvider.kt
sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt
sdk/src/main/java/com/mapbox/maps/NativeMapProvider.java

Tailwork of #1357, a distinction needs to be made between the NativeMapImpl which as a wrapper around the native map object vs the actual native map object. This went unnoticed since they both comply to the MapInterface which is used as its return type.

[provider] rework map providers

---

CHANGELOG.md
app/src/main/java/com/mapbox/maps/testapp/examples/GlobeActivity.kt
app/src/main/java/com/mapbox/maps/testapp/examples/HeatmapLayerActivity.kt
sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
sdk/src/test/java/com/mapbox/maps/NativeObserverTest.kt
sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt

Another approach to fix #1353 - apply styleExtension properties as soon as the corresponding style data event arrives.
With this change order of styleExtension properties applied is as follows :
1. fog, light, terrain, projection - after StyleDataType.STYLE
2. images - after StyleDataType.SPRITE
3. sources and layers - after StyleDataType.SOURCES
Note that order of StyleDataType.SPRITE and StyleDataType.SOURCES events is _NOT_ guaranteed and in fact often arrives differently. However this does not seem to be a problem (discussed with @alexshalamov, but please confirm). 
Tested briefly - everything seems working, however since change can be very impactful will require more thorough manual / unit tests.
Fixes: #1127 …

Rework MapboxMap.loadStyle

---

CHANGELOG.md
plugin-compass/src/main/java/com/mapbox/maps/plugin/compass/CompassViewImpl.kt

Fix #1295 
For some reason, in "edge-to-edge" mode compass will not show while turning visibility to `VISIBLE` from `INVISIBLE`. However, it works if we change the visibility to `GONE`.

Fix compass is not showing in "edge-to-edge" mode

---

CHANGELOG.md
extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/generated/Expression.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/sources/TileSet.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/types/FormattedSection.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/utils/TypeUtils.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerWrapper.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerRenderer.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapper.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/ModelSourceWrapper.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationIndicatorLayerWrapperTest.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerRendererTest.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelLayerWrapperTest.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/ModelSourceWrapperTest.kt

Use `orientation` model source property to update the 3D puck's bearing, as it is more efficient than updating the layer property.

Use `orientation` model source property to update the 3D puck's bearing.

---

CHANGELOG.md
sdk/src/androidTest/java/com/mapbox/maps/StyleLoadTest.kt
sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
sdk/src/main/java/com/mapbox/maps/NativeObserver.kt
sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
sdk/src/test/java/com/mapbox/maps/NativeObserverTest.kt
sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt

Fire sprite/sources loaded MapboxMap callbacks on onStyleLoad if no style data events arrived. 
Fixes: #1371 

Load sprites and sources style extensions earlier during onStyleLoad.

---

sdk/src/main/java/com/mapbox/maps/MapController.kt
sdk/src/main/java/com/mapbox/maps/renderer/EventType.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
sdk/src/main/java/com/mapbox/maps/renderer/RenderEvent.kt
sdk/src/main/java/com/mapbox/maps/renderer/RenderHandlerThread.kt
sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxRendererTest.kt
sdk/src/test/java/com/mapbox/maps/renderer/RenderHandlerThreadTest.kt

Previously we were ignoring tasks scheduled from gl-native if there was no EGL / render was not prepared fully, as well as clearing the queues with tasks when new surface arrives. 
Hence, various async tasks scheduled from gl-native could be just silently removed from the queue when new surface arrives (e.g. if activity was paused and then resumed). 
For example such behaviour caused 3d puck (and other models loaded async, potentially) not being loaded. 
With this change we will reschedule all the tasks indefinitely (with 50 millis delay), until with render thread is not fully destroyed (together with gl-native's renderer). …

Fix issue when tasks are skipped if surface is recreated - MAPSAND-177.

---

CHANGELOG.md
extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/expressions/ExpressionTest.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/generated/Expression.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/utils/TypeUtils.kt

This PR fixes an issue when literal array is used as output inside the match expression, for example:
```
modelRotation(
match {
mod {
id()
literal(4)
}
literal(0)
literal(listOf(0.0, 0.0, 0.0))
literal(1)
literal(listOf(0.0, 0.0, 20.0))
literal(2)
literal(listOf(3.0, 0.0, 40.0))
literal(listOf(-3.0, 0.0, 60.0))
}
)
```
will fail with error: 
```
com.mapbox.maps.MapboxStyleException: Add layer failed: Failed to set `model-rotation` property for `model-layer-id` layer. Error: [3][0]: Expression name must be a string, but found number instead. If you wanted a literal array, use [“literal”, [...]].
```
This issue is related to the fix we made previously to fix the arrays used as labels within the match expression #965. We had some issues with `match` expression when the label is a list, …

Fix using arrays inside match expression dsl - MAPSAND-226

---

app/src/androidTest/java/com/mapbox/maps/testapp/annotation/generated/PointAnnotationManagerAndroidTest.kt

Updating test which was added again somehow after removing in #1458 .
This makes codegen-verify job passes again.

[codegen] update annotation test to fix codegen job

---

.circleci/config.yml

Change robo test device from virtual Pixel2 to Pixel3 and added Pixel 6 running at API level 31.

Update robo test devices MAPSAND-268

---

CHANGELOG.md
buildSrc/src/main/kotlin/Project.kt

[deps] bump telemetry to v8.1.4 - MAPSAND-287

---

CHANGELOG.md
plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt

This patch a crash reported by a user. The crash is very much edge case and while the usage of ScreenCoordinate(0,0) might be a band-aid solution, it's better than crashing the end-user application.

Avoid NaN when converting screen coordinates to geographical coordinates

---

CHANGELOG.md
buildSrc/src/main/kotlin/Project.kt

Includes telemetry lib with fix for the crash when targetSdk = 31+ is used due to WorkManager 2.6 issues (https://github.com/mapbox/mapbox-events-android/pull/571#issuecomment-1179010463).

Update telemetry to 8.1.5.

---

android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/MapScreen.kt
android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/SearchScreen.kt
extension-androidauto/CHANGELOG.md
extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceOwner.kt
extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceOwnerTest.kt
scripts/check-changelog.sh

When building Android Auto for Android Automotive, the automotive surface library has a different behavior for creating surfaces when transitioning screens. 
Tested and reproduced on `androidx.car.app:app-automotive:1.1.0` and `androidx.car.app:app-automotive:1.2.0-rc`.
Fixes a blocking issue for anyone trying to build an Android Auto app for Android Automotive
cc: @yunikkk @pengdev 
Fixes: Resolves https://github.com/mapbox/mapbox-maps-android/issues/1503
Related: https://github.com/mapbox/mapbox-maps-android/issues/1397

[Android Auto] Fix android automotive surface recreation issue

---

.circleci/config.yml

COMMIT_SHA was not added to the uploaded snapshot, thus reuploading snapshots from the same branch could fail for different reasons - either cached locally, or somewhere at the proxy server etc.

Add COMMIT_SHA to the snapshot name.

---

CHANGELOG.md
sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt

Do not throw exception and just log instead in case StyleDataType.SOURCES is fired before StyleDataType.STYLE.
Fixes MAPSMBL-127

Fix weird crash in StyleObserver

---

CHANGELOG.md
sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt

Fix several edge-case situations:
- when new Android surface arrived and previous one is not valid anymore - we additionally recreate native renderer. Previously just EGL core was recreated while native renderer could still reference to outdated GPU resources.
- when `EGL_CONTEXT_LOST` is triggered during buffer swap (which should not even happen due to other checks) - we re-create EGL as well as native renderer so that it does not reference to outdated GPU resources.

Fix edge cases for renderer that could result in map not rendered

---

CHANGELOG.md
plugin-annotation/src/main/java/com/mapbox/maps/plugin/annotation/AnnotationManagerImpl.kt

AnnotationManager fires `onAnnotationDragStarted` events even the annotation is not draggable.  In this pr, we will check the `isDraggable` property when start dragging and return directly if the annotation is not draggable so that `onAnnotationDragStarted` event will not be fired.

Fix onAnnotationDragStarted event is still fired when annotation is not draggable - MAPSAND-356

---

LICENSE.md
buildSrc/src/main/kotlin/Project.kt
extension-style/api/metalava.txt

Downgrade androix core to pass metalava checks for current kotlin version (`1.5.31`).
With current core version (`1.8.0`) we not compatible with current Kotlin version, because it's required 1.6.+.

downgrade androidx core to 1.7.0

---

CHANGELOG.md
app/src/main/java/com/mapbox/maps/testapp/examples/BasicLocationPulsingCircleActivity.kt
app/src/main/res/menu/menu_pulsing_location_mode.xml
app/src/main/res/values/strings.xml
plugin-locationcomponent/api/metalava.txt
plugin-locationcomponent/api/plugin-locationcomponent.api
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentConstants.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimatorManager.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckPulsingAnimator.kt
plugin-locationcomponent/src/main/res-public/values/public.xml
plugin-locationcomponent/src/main/res/values/attrs.xml
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimatorManagerTest.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettings.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsBase.kt
sdk-base/src/main/java/com/mapbox/maps/plugin/locationcomponent/generated/LocationComponentSettingsInterface.kt

This pr adds support for the pulsing puck to follow accuracy radius, currently pulsing puck has constant radius, which is not in consistent with v6 ios behaviour. 
Note : In order to not introduce breaking changes in LocationComponentSettings by adding extra parameter. introduced  new constant `PULSING_MAX_RADIUS_FOLLOW_ACCURACY` that will trigger pulsing puck to follow accuracy radius.
In order to apply the settings, use `pulsingMaxRadius` as `LocationComponentConstants.PULSING_MAX_RADIUS_FOLLOW_ACCURACY`.
eg.
```
binding.mapView.location.apply {
pulsingEnabled = true
pulsingMaxRadius = LocationComponentConstants.PULSING_MAX_RADIUS_FOLLOW_ACCURACY
}
```
<video src="https://user-images.githubusercontent.com/11589497/182851544-e487325a-e642-4b18-90ec-4f05c113fb91.mp4" />
Fixes: < Link to …

Add support for pulsing puck to follow accuracy radius. [MAPSAND-318]

---

CHANGELOG.md
plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/transition/DefaultViewportTransitionImpl.kt

Default viewport implementation doesn't use the shortest bearing transition when animating, this pr fixes the bug calculating the shortest path for bearing rotation.
| <video src="https://user-images.githubusercontent.com/11589497/181219789-ef6e2dd7-9283-44e1-b9fa-093eff248566.mp4" width = 250/> | <video src="https://user-images.githubusercontent.com/11589497/181220039-72611178-d809-4eec-a6f5-c84d18f823b1.mp4" width = 250/> |

[viewport] use shortest path for viewport bearing transition MAPSAND-188

---

CHANGELOG.md
app/src/main/java/com/mapbox/maps/testapp/examples/DebugModeActivity.kt
sdk/src/main/java/com/mapbox/maps/MapController.kt
sdk/src/main/java/com/mapbox/maps/MapSurface.kt
sdk/src/main/java/com/mapbox/maps/MapView.kt
sdk/src/main/java/com/mapbox/maps/renderer/FpsManager.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
sdk/src/main/java/com/mapbox/maps/renderer/RenderHandlerThread.kt
sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
sdk/src/test/java/com/mapbox/maps/renderer/FpsManagerTest.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxRenderThreadTest.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxRendererTest.kt

This PR fixes 2 problems that are pretty close to each other.
- when adding FPS listener via `MapView.setOnFpsChangedListener` previously callback was triggered immediately after render call was executed. That was actually not correct as docs stated that callback should return average amount of rendered frames during last second. Now this is fixed and FPS values are much more readable and reliable. Assuming we use rendering on demand (and not continuous) corner situations are also covered:
- when not interacting with the map for some time and starting to interact after some delay - we will not report huge amount of missed VSYNC events, instead we will report last FPS update after 50 ms update of map being IDLE and reset counters.
- when going to background we will also report last FPS …

Fix setting max fps and fps count for renderer

---

CHANGELOG.md
extension-style/src/main/java/com/mapbox/maps/extension/style/atmosphere/generated/Atmosphere.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/atmosphere/generated/AtmosphereExt.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/Light.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/light/generated/LightExt.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/Terrain.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/terrain/generated/TerrainExt.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/atmosphere/generated/AtmosphereTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/light/generated/LightTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/terrain/generated/TerrainTest.kt

Style extension getters for terrain, light and atmosphere were actually calling core setter method under the hood which is unexpected for the user and could cause visual glitches e.g.:
```kotlin
mapboxMap.loadStyle(
styleExtension = style(Style.SATELLITE_STREETS) {
+terrain(SOURCE) {
exaggeration(8.0)
}
}
) { style ->
// correct exagerration is used
println("Exagerration : ${style.getStyleTerrainProperty("exaggeration")}") 
val terrain = style.getTerrain(SOURCE)
// will get null exaggeration property after this call and gl-native uses default value (1.0)
println("After get terrain : ${terrain.exaggeration}")
}
```
This will be fixed now - correct value will be returned and when calling `style.getTerrain(SOURCE)` - no terrain will be re-added.
Fixes: < Link to related issues that will be …

Fix style getters for terrain, light and atmosphere resetting properties

---

CHANGELOG.md
sdk/src/main/java/com/mapbox/maps/MapSurface.kt

When implementing MapSurface (e.g. for Android Auto) it is regular practice to overload just `surfaceCreated`, `surfaceChanged` and `surfaceDestroyed` methods. However in that case we're missing `MapControllable.onSizeChanged` call that actually notifies all the plugins.
That will lead as an example to incorrect map shove gesture as center focal point will always be (0, 0). Now `surfaceChanged` call will also call `MapControllable.onSizeChanged` under the hood.

Fix MapSurface#surfaceChanged to update dimensions for plugins

---

.circleci/config.yml

Fix snapshot name by adding conditions for the last release to accommodate different version tags and create correct version name for snapshot build.
snapshot name will be; 

[ci] fix snapshot version name MAPSAND-377

---

.circleci/config.yml

Fixing ci to get the correct internal branch after changing tag name from `android-v*` to `v*`
Our internal ci currently runs on specific target branches rather than main. 

[ci ] Fix ci to run on correct internal branch

---

Makefile

Fix the upload script to avoid parallel execution.
Previously as we run aws ls command for every module in parallel, the aws command sometimes fail. This typically causes issue when running locally, as in circle-ci, we have a global gradle option set to `GRADLE_OPTS: -Xmx4096m -Dorg.gradle.daemon=false -Dkotlin.compiler.execution.strategy=in-process`.
This PR avoid parallel execution of the upload task, to make it more reliable.

Fix the upload script to avoid parallel execution.

---

CHANGELOG.md
sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderThread.kt
sdk/src/main/java/com/mapbox/maps/renderer/egl/EGLCore.kt

There is a possibility that calling native `EGLSurface  eglCreateWindowSurface(EGLDisplay display, EGLConfig config, Object native_window, int[] attrib_list);` could produce the `java.lang.IllegalArgumentException` even although we are checking that Android `Surface` is valid right beforehand.
Now we will try to create it later, similar solution is implemented in an Android `GLSurfaceView` is to actually retry creating it later:
full AOSP delta is [here](https://github.com/aosp-mirror/platform_frameworks_base/commit/7d73df83f9a28950f404e957eb2e4ea1e8525c55#diff-c7a96cfebb7b482f891bd4862d5976e99240ecadc9698b3cd7e21a45b065b4b5R1453).
PRs must be submitted under the terms of our Contributor License …

Try recreate EGL surface when it throws exception

---

CHANGELOG.md
sdk/src/main/java/com/mapbox/maps/renderer/MapboxWidgetRenderer.kt

Fix concurrent modification exception when using OpenGL ES widgets (e.g. for Android Auto case).
Fixes https://github.com/mapbox/mapbox-maps-android/issues/1596

Fix concurrent modification exception when using widgets

---

CHANGELOG.md
buildSrc/src/main/kotlin/Project.kt
extension-localization/README.md
extension-style/README.md
plugin-animation/README.md
plugin-annotation/README.md
plugin-attribution/README.md
plugin-compass/README.md
plugin-gestures/README.md
plugin-lifecycle/README.md
plugin-locationcomponent/README.md
plugin-logo/README.md
plugin-overlay/README.md
plugin-scalebar/README.md
plugin-viewport/README.md

* Relax LOD requirements for maps with insets and zero terrain exaggeration, leading to more content shown in easily readable map areas
* Make CameraManager.setCamera method exception free. In cases when incorrect CameraOptions are provided, error would be logged.
* Fix black holes in the globe view when edge insets are used 
* Upgrade mapbox-common version to v23.0.0-rc.2

Bump gl-native to 10.8-rc.1

---

CHANGELOG.md
app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/infowindow/MarkerManager.kt
sdk/src/androidTest/java/com/mapbox/maps/ViewAnnotationTest.kt
sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt

In view annotation manager we were relying on `ViewTreeObserver.OnGlobalLayoutListener` listener to control 2 state changes for the view annotation:
- dimension change caused by `WRAP_CONTENT`
- visibility changes based on user calling `View.setVisibility` in order to update core with new visible status
However it turned out that changing view visibility from `VISIBLE` to `INVISIBLE` does not actually trigger `OnGlobalLayoutListener` as the view still remains in the view tree. That actually was breaking view annotation logic when user was simply setting view annotation visibility to `INVISIBLE`, dragging the map and making it `VISIBLE` again.
The solution found here is to actually check view visibility inside `ViewTreeObserver.OnDrawListener` that is called on each frame for the view. In …

Use on draw listener in view annotation manager for more granular control

---

CHANGELOG.md
plugin-gestures/src/main/res-public/values/public.xml
sdk-base/api/metalava.txt
sdk-base/src/main/java/com/mapbox/maps/plugin/gestures/generated/GesturesSettingsInterface.kt

Deprecate gesture settings `increaseRotateThresholdWhenPinchingToZoom` property.
None. The property was not used and had no effect.

Deprecate gesture settings increaseRotateThresholdWhenPinchingToZoom

---

CHANGELOG.md
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManager.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/animators/PuckAnimatorManager.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationPuckManagerTest.kt

Disabling the puck in LocationPuckManager will now cause the puck direction to snap back to north.  This was requested by a customer.
Calling LocationPuckManager.applySettings2 with LocationComponentSettings2.puckBearingEnabled == false will cause the puck to instantly animate to the north position.  When calling with puckBearingEnabled == true, the puck will animate smoothly back to the last reported heading.
| <video src="https://user-images.githubusercontent.com/16490463/187616284-da6a58c8-9cc9-459c-9530-6c4b3e82487a.mp4" width = 250/>
Fixes: 
https://mapbox.atlassian.net/jira/software/c/projects/MAPSAND/issues/MAPSAND-221

MAPSAND-221 setting puck bearing enabled to false does not reset bearing

---

CHANGELOG.md
buildSrc/src/main/kotlin/Project.kt

This PR bumps mapbox-gestures dependency to [0.8.0](https://github.com/mapbox/mapbox-gestures-android/releases/tag/v0.8.0)

Bump mapbox gestures dependency to 0.8.0.

---

CHANGELOG.md
sdk/src/main/java/com/mapbox/maps/MapController.kt
sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt

If `configChanges` is specified in AndroidManifest.xml and device is rotated when `MapView` in background - `MapView` was using incorrect old dimensions when bringing it back to front.
That is now fixed by checking if renderer dimensions should be updated if `MapView#onSizeChanged` was called by Android.

Fix incorrect MapView dimensions on background orientation change

---

app/src/main/java/com/mapbox/maps/testapp/examples/LargeGeojsonPerformanceActivity.kt

I noticed that `long_route.json` is in DirectionsResponse format, but we only use GeoJSON data from it. I converted the file to GeoJSON format to skip the unneeded conversion.
Not applicable for the example.

Convert long_route.json to GeoJSON format

---

plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImpl.kt
plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsPluginImplTest.kt

- After gl-native bump to v10.8.0-rc.1, exceptions in set camera will be handled in native, which makes the fix in https://github.com/mapbox/mapbox-maps-android/pull/652 redundant. Reverting old fix in this pr. 
More context can be found in MAPSAND-389.

[v10.9] revert setCamera exception fix #652

---

CHANGELOG.md
sdk/src/main/java/com/mapbox/maps/renderer/widget/BitmapWidgetRenderer.kt

Horizontally and/or vertically centred widgets in BitmapWidgetRenderer were right aligned, this PR should fix them.
Widget positions may be affected which have `WidgetPosition.Horizontal.CENTER` or `WidgetPosition.Vertical.CENTER`
After change:
Before change:
Fixes: https://github.com/mapbox/mapbox-maps-android/issues/1531

MAPSMBL-159 android auto wrong bitmap widget position after calling update bitmap with a bitmap that has different size

---

CHANGELOG.md
app/src/main/java/com/mapbox/maps/testapp/examples/DSLStylingActivity.kt
extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/expressions/ExpressionTest.kt
extension-style/api/extension-style.api
extension-style/api/metalava.txt
extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/dsl/generated/ExpressionDsl.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/expressions/generated/Expression.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/expressions/generated/ExpressionTest.kt

Added support for `pitch` and `distanceFromCenter` in filter expressions for symbol layers.
See counterpart `gl-js` https://github.com/mapbox/mapbox-gl-js/pull/10795
Users can now use `pitch {...}` and `distanceFromCenter {..}` expressions in symbol layers.
See following capture where `mag x` text symbols are hidden when the pitch is higher than 70º.
https://user-images.githubusercontent.com/691172/191190437-90876320-c207-4726-9edb-5a83cf98d5ca.mp4

Added `pitch` and `distance-from-center` expressions support

---

android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/testing/CarJavaInterfaceChecker.java
extension-androidauto/CHANGELOG.md
extension-androidauto/api/extension-androidauto.api
extension-androidauto/api/metalava.txt
extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceOwner.kt
extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMap.kt
extension-androidauto/src/test/java/com/mapbox/maps/extension/androidauto/MapboxCarMapTest.kt

Adding an example of `onClick` requires a compileVersion 33 and a kotlin upgrade. This pull request is adding support to add `onClick` downstread https://github.com/mapbox/mapbox-maps-android/pull/1682, except this change is not blocked by the repo upgrades.
Please see the full description and video in the example https://github.com/mapbox/mapbox-maps-android/pull/1682. This change creates no functional changes, but adds the ability to customize the `SurfaceCallback`.

[Android Auto] Allow for downstream upgrades

---

extension-androidauto/CHANGELOG.md
extension-androidauto/gradle.properties

* Allow `MapboxCarMap` to be initialized before the `CarContext` is created. ([#1603](https://github.com/mapbox/mapbox-maps-android/pull/1603))
* Add `MapboxCarMapSessionInstaller` and `MapboxCarMapScreenInstaller` for simpler setup. ([#1603](https://github.com/mapbox/mapbox-maps-android/pull/1603))
* Add `Session.mapboxMapInstaller` and `Screen.mapboxMapInstaller` extension functions to create the installers. ([#1603](https://github.com/mapbox/mapbox-maps-android/pull/1603))
* Change `MapboxCarMapGestureHandler` to a java interface so default methods can be added without breaking java backwards compatibility. ([#1670](https://github.com/mapbox/mapbox-maps-android/pull/1670))
* Change `MapboxCarMapObserver` to a java interface so default methods can be added without breaking java …

[Android Auto] Add changelog for 0.3.0

---

sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
sdk/src/main/java/com/mapbox/maps/Style.kt

- soften wording when using outdated `MapboxMap` / `Style` as it's not the mandatory leak and it might confuse the users
- downgrade log level from `Error` to `Warning` for the same reason as above

Soften log message when using outdated map / style objects

---

CHANGELOG.md
sdk/src/main/java/com/mapbox/maps/MapController.kt
sdk/src/main/java/com/mapbox/maps/MapProvider.kt

This is an alternative approach to https://github.com/mapbox/mapbox-maps-android/pull/1693.
It's less intrusive as it doesn't remove the module setup but makes a singleton instance of MapTelemetry. This avoids recreation that could occur when coming from background. This aligns with our http stack setup which we haven't seen issues with. 

Provide telemetry module as a singleton

---

CHANGELOG.md
buildSrc/src/main/kotlin/Project.kt

Port Bump common sdk to v23.1.0-beta.2. (#1696) to v10.9 release branch.

Bump common sdk to v23.1.0-beta.2. (#1696)

---

CHANGELOG.md
buildSrc/src/main/kotlin/Project.kt

* Fix a potential style load error when non-ASCII characters are used in the version name, by escaping non US ASCII characters in user-agent header.
* Bump common sdk to 23.0.1.

Bump common sdk to 23.0.1.

---

CHANGELOG.md
sdk/src/androidTest/java/com/mapbox/maps/StyleLoadTest.kt
sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
sdk/src/main/java/com/mapbox/maps/StyleObserver.kt
sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt
sdk/src/test/java/com/mapbox/maps/StyleObserverTest.kt

When we load styles many times in a row there's a possibility that `style data : sources` event from the previous style will arrive after new style has been started loading. Here we add the fix for it and actually wait for the `style data : style` event after the style load has been initiated and skip all the other events. 
This is actually part of MAPSNAT-516 that couldn't be fixed in gl-native. 

Fix raster dem crash style reload

---

CHANGELOG.md
buildSrc/src/main/kotlin/Project.kt

* Eliminate tiles re-creation and re-layout on zooming map with globe, when the camera is trespassing the zoom projection border.
* Fix "phantom tiles" artefacts after GeoJSON source update when asynchronous tile loading is enabled.
* Mitigate symbol flickering on zooming out globe map.
* Fix random crash on tiles update when asynchronous uploading is enabled.
* Fix a crash when Google location service is started in background but stopped in foreground.
* Fix an issue where mock field is missing from the LocationEngine updates.
PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-android/blob/main/CONTRIBUTING.md#contributor-license-agre …

Bump gl-native to v10.9.0-rc.1

---

CHANGELOG.md
sdk/build.gradle.kts
sdk/src/androidTest/java/com/mapbox/maps/TestUtils.kt
sdk/src/androidTest/java/com/mapbox/maps/ViewAnnotationTest.kt
sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt
sdk/src/main/java/com/mapbox/maps/plugin/MapPluginRegistry.kt
sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerAddTest.kt
sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerTest.kt
sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerZOrderingTest.kt

Problem was caused calling bringToFront() on every update of the annotations, that happens on any map animation or gesture.
bringToFront() was needed to guarantee that : 
- view annotations are displayed in the correct order (same as items in the `onViewAnnotationPositionsUpdate(@NonNull List<ViewAnnotationPositionDescriptor> positions);` callback). This order changes if some ViewAnnotation is being selected, for example
- plugins (compass, ruler etc) are displayed on top of ViewAnnotations
Also I've added separate FrameLayout to the MapView on top of the actual surface/texture view but below any other plugin - so that removing or adding new view annotation does not interfere with the plugins at all. 
MapView adds a SurfaceView/TextureView that actually displays map at the index 0 here, …

Fix view annotations triggering excessive onMeasure [MAPSAND-516]

---

gradle.properties

Modified Gradle JVM `gradle.properties` to use 8G and parallel GC.
N/A

Increase Gradle JVM max memory to 8G and use parallel GC

---

.circleci/config.yml

Due to changes introduced by #1750 the `check-gradle-dependencies` job was failing.
This PR changes the machine type used by that CI job.
N/A

Use xlarge machine for `check-gradle-dependencies` job

---

.circleci/config.yml
build.gradle.kts

While doing #1742 and #1750 I played with the different Gradle options we pass to CI.
It turns out that it is faster to use daemons. Specially jobs like `verify-api-revapi` where multiple `gradle` commands are called within the same job.
For example:
- `verify-api-revapi` went from ~9 minutes to ~5 minutes.
- `build-modules-and-instrumentation-tests` from ~7.5 minutes to ~4.5 minutes
N/A

Use daemons in CI

---

.circleci/config.yml

Increased docker machine in Circleci for job `verify-api-revapi` to `Large` which is sometimes failing since the changes introduced in #1756.
N/A

Changed job `verify-api-revapi` to use Large machine in CI

---

CHANGELOG.md
buildSrc/src/main/kotlin/Project.kt

* Updated mapbox-common to v23.1.1.
* Introduced `location-indicator-opacity` to location indicator layer that allows to control layer opacity.
* Rendering performance improvements for fast paced camera changes
* Fixed flickering of vertically shifted line labels on style change, caused by the wrong initial placement.
* Fixed location indicator rendering as a rectangle on low zoom levels.
* Fixed crash caused by using of invalid paint property binders.
* Fixed "phantom tiles" artefacts after GeoJSON source update when asynchronous tile loading is enabled.
* Mitigated symbol flickering on zooming out globe map.
* Fixed random crash on tiles update when asynchronous uploading is enabled.
* Fixed pixel flickering between tiles with darker styles in globe view.
* Location indicator layer now …

Bump gl-native 10.9.0, common 23.1.1.

---

CHANGELOG.md
buildSrc/src/main/kotlin/Project.kt

This is port of https://github.com/mapbox/mapbox-maps-android/pull/1760 to the release branch

[port] GL native bump port to v10.9 release branch

---

CHANGELOG.md
sdk/api/sdk.api
sdk/src/main/java/com/mapbox/maps/MapView.kt

Fix an issue when touch events didn't pass through the view annotation.

Fix touch event with many annotations MAPSAND-459

---

CHANGELOG.md
app/src/main/java/com/mapbox/maps/testapp/examples/markersandcallouts/ViewAnnotationBasicAddActivity.kt
app/src/main/res/layout/activity_view_annotation_showcase.xml
sdk/api/metalava.txt
sdk/api/sdk.api
sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt
sdk/src/main/java/com/mapbox/maps/viewannotation/ViewAnnotationManager.kt
sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerTest.kt

Introduce `ViewAnnotationManager.cameraForAnnotations` that returns `CameraOptions` for provided annotations. Users can use custom animation to move camera to fit specified anntations.
If users set `ViewAnnotationOptions.visible = false ` explicitly, we will exclude those views from the calculation for `cameraOptions`. Also, only the views for which visibility is set to Visible, will be considered in the calculation.
<video src="https://user-images.githubusercontent.com/11589497/196913569-e0d0c782-89d7-4a3d-bb51-ff4bfa3847c9.mp4" width = 500/>
PRs must be submitted under the terms of our Contributor License Agreement [CLA](https://github.com/mapbox/mapbox-maps-android/blob/main/CONTRIBUTING.md#contribu …

[viewannotation] Introduce show annotations api [MAPSAND-464]

---

sdk/src/main/java/com/mapbox/maps/MapView.kt

Fix for view annotation multitouch events when annotations are clickable. Our cached touch event list shouldn't be clear so fast.
Related PR #1745

fix touch event for annotations

---

CHANGELOG.md
sdk/api/metalava.txt
sdk/api/sdk.api
sdk/src/main/java/com/mapbox/maps/MapboxMap.kt
sdk/src/test/java/com/mapbox/maps/MapboxMapTest.kt

Expose `RenderWorldCopies` property that sets whether multiple copies of the world will be rendered side by side beyond -180 and 180 degrees longitude.

expose RenderWorldCopies property MAPSAND-588

---

CHANGELOG.md
sdk/src/main/java/com/mapbox/maps/MapController.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxRenderer.kt
sdk/src/main/java/com/mapbox/maps/renderer/MapboxWidgetRenderer.kt
sdk/src/main/java/com/mapbox/maps/renderer/widget/BitmapWidget.kt
sdk/src/main/java/com/mapbox/maps/renderer/widget/Widget.kt
sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
sdk/src/test/java/com/mapbox/maps/renderer/MapboxRendererTest.kt

Port #1797 to v10.10 release branch.

[Port] Trigger repaint after `BitmapWidget` is updated. (#1797)

---

CHANGELOG.md
buildSrc/src/main/kotlin/Project.kt

bump gl native v10.9.1

---

android-auto-app/build.gradle.kts
android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarCameraController.kt
android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/car/CarMapShowcase.kt
android-auto-app/src/main/java/com/mapbox/maps/testapp/auto/testing/CarJavaInterfaceChecker.java
extension-androidauto/CHANGELOG.md
extension-androidauto/api/metalava.txt
extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/CarMapSurfaceOwner.kt
extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/DefaultMapboxCarMapGestureHandler.kt
extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMap.kt
extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapGestureHandler.java
extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapObserver.java
extension-androidauto/src/main/java/com/mapbox/maps/extension/androidauto/MapboxCarMapSurface.kt

Note that the next release will still be `0.4.0`. When the `1.0.0` is released, that is when these interfaces are actually locked down.
Removing `@MapboxExperimental` from the following
- MapboxCarMap
- MapboxCarMapObserver
- MapboxCarMapSurface
- MapboxCarMapGestureHandler
- DefaultMapboxCarMapGestureHandler
All of these are required in order to use the default experience provided by the extension.
Intentionally keeping `@MapboxExperimental` on the following
- MapboxCarMap.prepareSurfaceCallback
- CompassWidget
- LogoWidget
- MapboxCarMapSessionInstaller
- MapboxCarMapScreenInstaller
- MapboxCarMapInitializer
`prepareSurfaceCallback` is a function to support an `androidx.car.app:app:1.3.0-beta` upgrade. The widgets depend on `BitmapWidget` which is experimental. The installers are …

[Android Auto] Remove experimental annotation

---

module-telemetry/build.gradle.kts
module-telemetry/src/main/java/com/mapbox/maps/module/telemetry/MapLoadEvent.kt
module-telemetry/src/main/java/com/mapbox/maps/module/telemetry/MapTelemetryImpl.kt
module-telemetry/src/test/java/com/mapbox/maps/module/telemetry/MapEventFactoryTest.kt
module-telemetry/src/test/java/com/mapbox/maps/module/telemetry/MapTelemetryTest.kt
sdk-base/build.gradle.kts
sdk/src/main/java/com/mapbox/maps/MapController.kt
sdk/src/main/java/com/mapbox/maps/MapProvider.kt
sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
sdk/src/test/java/com/mapbox/maps/shadows/ShadowEventsService.kt

This is a one-liner change that changes the events priority to queued by default. Queued events are batched in groups of up to 180 events and sent as a single gzip-compressed HTTP request, thus reducing network bandwidth consumption.
Interaction and feedback events are not time-critical, so there is no need for marking these as immediate priority.
No added tests as this logic implementation is part of Common SDK.
Because we're marking Maps SDK interaction and feedback events as queued, there will be a reduction in terms of HTTP requests generated from the SDK.

Set events as queued by default

---

extension-localization/README.md
extension-style/README.md
plugin-animation/README.md
plugin-annotation/README.md
plugin-attribution/README.md
plugin-compass/README.md
plugin-gestures/README.md
plugin-lifecycle/README.md
plugin-locationcomponent/README.md
plugin-logo/README.md
plugin-scalebar/README.md
plugin-viewport/README.md

This reverts commit aeb5ea6a3da8dcae02f7c30b86469d26df7ae2f4.
Reverting changes did by automation during patch release v10.9.1.
Context: During the patch release automation run ,`changelog.md` and `readme.md` files were updated incorrectly, and all entries of changelog.md was removed. discussed offline and found that it's a bug in release automation. this pr reverts the changes done by automation.

Revert "changelog for v10.9.1 (#1810)"

---

sdk/src/main/java/com/mapbox/maps/MapProvider.kt
sdk/src/test/java/com/mapbox/maps/MapControllerTest.kt
sdk/src/test/java/com/mapbox/maps/shadows/ShadowTelemetryService.kt

Flush pending events for telemetry service on map controller stop.

Flush pending events for telemetry service on map controller stop.

---

CHANGELOG.md
sdk/src/main/java/com/mapbox/maps/ViewAnnotationManagerImpl.kt
sdk/src/test/java/com/mapbox/maps/ViewAnnotationManagerTest.kt

Opened instead of https://github.com/mapbox/mapbox-maps-android/pull/1829 to let CI pass.
Fixes: #1723
1. remove view annotation from currentlyDrawnViewIdSet as well
2. on edge cases (view has animation or transition) onViewDetachedFromWindow will not be called on view removal from viewAnnotationsLayout, so make sure we call it to cleanup viewTreeObserver listener

Fix a crash after removing the view annotation if view has an attached animation or transition

---

CHANGELOG.md
app/src/androidTest/java/com/mapbox/maps/testapp/viewport/ViewportPluginTest.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImpl.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImplTest.kt

This PR emits the last indicator state when new listeners are added to the location component.
We have [introduced a threshold](https://github.com/mapbox/mapbox-maps-android/pull/1398) of 0.01 to update the puck when the bearing is changed, so if the change in bearing is too small, we will not trigger a puck update, thus the `IndicatorBearingChangedListener` is not triggered if the bearing does not change. This will cause troubles that the new subscriber don't get the last status in a timely manner. 
In this PR, we emit the last know puck status immediately when a new listener is added, so they don't need to wait for the new data points, this is especially helpful in the viewport plugin, as we consume the location puck's position update in the `FollowPuckViewportState`.
Fixes: < Link to …

[locationcomponent] Emit the last indicator state when new listeners are added to the location component. MAPSAND-570

---

buildSrc/src/main/kotlin/Project.kt
extension-androidauto/CHANGELOG.md

The `1.2.0` Jetpack Car Library is out with many bug fixes, and there is a final version out. Let's bump and release https://developer.android.com/jetpack/androidx/releases/car-app#1.2.0
It is also possible to keep 1.1.0 and upgrade to 1.2.0 downstream, but we have not found a reason to continue to support 1.1.0 because it has issues that were addressed in 1.2.0.

[Android Auto] Bump car library to 1.2.0

---

CHANGELOG.md
app/src/androidTest/java/com/mapbox/maps/testapp/viewport/ViewportPluginTest.kt
plugin-animation/api/plugin-animation.api
plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/animator/CameraAnimator.kt
plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsListenersTest.kt
sdk/src/androidTest/java/com/mapbox/maps/CameraAnimationsPluginTest.kt

This PR bypasses the immediate camera animation(where duration and start delay of the animation is 0) on the animator, and emit a single animator update instead of trying to start the ValueAnimator directly.
More context on the issue with animators on API 23 or below:
> Devices with API <= 23 animating with duration = 0 will send initial value from Looper with some small delay as a result.
> Hence multiple immediate animations sent close to each other may cancel previous ones.
This change particularly affects the camera animation and viewport plugin on API level 23 or below.
For example viewport plugin's `FollowPuckViewportState` behaviour will be fixed as shown below:
| <video src="https://user-images.githubusercontent.com/2764714/202478245-d6b1ebc4-cb …

[camera] Fix immediate camera animation on API level 23 or below - MAPSAND-614

---

CHANGELOG.md
app/src/androidTest/java/com/mapbox/maps/testapp/viewport/ViewportPluginTest.kt
plugin-animation/api/plugin-animation.api
plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/animator/CameraAnimator.kt
plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimationsListenersTest.kt

This PR ports #1842 immediate camera animation fix to v10.10 release 

[port] Port #1842 immediate camera animation fix.

---

app/src/main/java/com/mapbox/maps/testapp/examples/GesturesActivity.kt

This PR updates the GesturesActivity example to match our documentation on [listening to gesture events](https://docs.mapbox.com/android/maps/guides/user-interaction/#listen-for-gesture-events). Now, gestures are added from the gesturesPlugin and removed within `onDestroy`. This will prevent any confusion for developers when manipulating/detecting gestures within the map view. 
Fixes https://github.com/mapbox/mapbox-maps-android/issues/1641

Update GesturesActivity example to match documentation

---

CHANGELOG.md
app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java
sdk-base/api/metalava.txt
sdk-base/api/sdk-base.api
sdk-base/src/main/java/com/mapbox/maps/module/MapTelemetry.java

This PR introduce `MapTelemetry.getUserTelemetryRequestState` API.
Note that MapTelemetry interface is rewritten in Java: for more context in https://github.com/mapbox/mapbox-maps-android/pull/1670#discussion_r972473077, as we want to make the default interface backwards-compatible with Java, writing default method with `@JvmDefault` in Kotlin will require `-Xjvm-default compiler option`.
As summarised by @kmadsen 
> The -Xjvm-default compiler flag may do what we want in the future. But right now, it does not generate default interfaces in an SDK. The app developer has to include the flag in their app to make the app compile when it uses an sdk that is relying on the flag.
PRs must be submitted under …

Introduce MapTelemetry.getUserTelemetryRequestState API - MAPSAND-645

---

extension-androidauto/gradle.properties
gradle/artifact-settings.gradle

Fixes typo in "REGISTRY_EXCLUDE_FROM_ROOT_PROEJCT", must be intended to be "REGISTRY_EXCLUDE_FROM_ROOT_PROJECT"

MAPSAND-650 fix REGISTRY_EXCLUDE_FROM_ROOT_PROEJCT typo

---

CHANGELOG.md
app/src/main/java/com/mapbox/maps/testapp/examples/JavaInterfaceChecker.java
sdk-base/api/metalava.txt
sdk-base/api/sdk-base.api
sdk-base/src/main/java/com/mapbox/maps/module/MapTelemetry.java

Port Introduce MapTelemetry.getTelemetryCollectionState API #1877 to v10.10.

[port] Port Introduce MapTelemetry.getTelemetryCollectionState API #1877 to v10.10.

---

CHANGELOG.md
buildSrc/src/main/kotlin/Project.kt

* Update mapbox-common to v23.2.0.
* Eliminate tiles re-creation and re-layout on zooming map with globe, when the camera is trespassing the zoom projection border.
* Avoid tiles re-layout on enabling terrain with zero exaggeration.
* Added API to enable/disable rendering of world copies in mercator mode.
* Improve symbol filtering performance when `distance-from-camera` and `pitch` expressions are used.
* Reduce number of operations when terrain is used with zero exaggeration.
* Handle OOB when getting DEM Data
* Fix a rare precision issue with symbol and circle layer occlusion when terrain is enabled.
* Fixes a rare crash caused by a race condition during gesture handling.
* Disable location indicator occlusion testing with the terrain when exaggeration is set to 0. This fixes …

[deps] Bump gl-native to v10.10.0, common to v23.2.0.

---

app/src/main/java/com/mapbox/maps/testapp/utils/LocationPermissionHelper.kt
plugin-locationcomponent/src/main/java/com/mapbox/maps/plugin/locationcomponent/DefaultLocationProvider.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/DefaultLocationProviderTest.kt
plugin-locationcomponent/src/test/java/com/mapbox/maps/plugin/locationcomponent/LocationComponentPluginImplTest.kt

As part of core telemetry migration in https://github.com/mapbox/mapbox-maps-android/pull/1672, we used compat packages to host the location engine, this PR reverts location engine packages back to `com.mapbox.android.core`, to validate the removal of MME dependency.

Revert location engine packages.

---

CHANGELOG.md
buildSrc/src/main/kotlin/Project.kt

This PR bumps common SDK to v23.2.1.

Bump common SDK to v23.2.1.

---

CHANGELOG.md
plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt

Resolves https://github.com/mapbox/mapbox-maps-android/issues/1529
[gestures] Fix crash due to invalid distance when panning the map.

[gestures] Fix crash due to invalid distance when panning the map. - MAPSAND-627

---

.circleci/config.yml
Makefile
app/permission.json
scripts/check-permissions.py

Continuously verify if permission changes with either ourselves, upstream Mapbox or external dependencies. This PR introduces continuous verification in CI env (`make check-permissions`) to get notified about permissions changes. If a change occurs and is permitted, we can update hte baseline file (`make update-permissions`)
```sh
make check-permissions 
python3 scripts/check-permissions.py 
--apk app/build/outputs/apk/debug/app-debug.apk 
--file app/permission.json 
make update-permissions 
python3 scripts/check-permissions.py 
--apk app/build/outputs/apk/debug/app-debug.apk 
--file app/permission.json 
--update True
```
```
$ make check-permissions 
python3 scripts/check-permissions.py \
--apk app/build/outputs/apk/debug/app-debug.apk \
--file app/permission.json
Utility to validate …
```

[ci] continously verify if permission changes 

---

CHANGELOG.md
plugin-viewport/src/main/kotlin/com/mapbox/maps/plugin/viewport/state/FollowPuckViewportStateImpl.kt
plugin-viewport/src/test/kotlin/com/mapbox/maps/plugin/viewport/state/FollowPuckViewportStateImplTest.kt

Fix transition to FollowPuckViewportState when no new location update is available.

[viewport] Fix transition to FollowPuckViewportState when no new location update is available.

---

CHANGELOG.md
buildSrc/src/main/kotlin/Project.kt
sdk/api/metalava.txt
sdk/api/sdk.api
sdk/src/main/java/com/mapbox/maps/NativeMapImpl.kt
sdk/src/main/java/com/mapbox/maps/Style.kt

* Update gl-native to v10.11.0-beta.1 and common to v23.3.0-beta.1.

Bump GL Native to 10.11.0-beta.1 and Common to 23.3.0-beta.1

---

CHANGELOG.md
plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt
plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraTransform.kt
plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactoryTest.kt

Current `flyTo()` animation doesn't wrap longitude values to world bounds. which results in invalid tiles in native. This pr fixes it by wraping longitude values as per native implementation.

[MAPSAND-679] wrap longitude to world bound for flyTo animation.

---

CHANGELOG.md
extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/BackgroundLayerTest.kt
extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/FillExtrusionLayerTest.kt
extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/FillLayerTest.kt
extension-style-app/src/androidTest/java/com/mapbox/maps/testapp/style/layers/generated/LineLayerTest.kt
extension-style/api/metalava.txt
extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/BackgroundLayer.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayer.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/FillLayer.kt
extension-style/src/main/java/com/mapbox/maps/extension/style/layers/generated/LineLayer.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/BackgroundLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/FillExtrusionLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/FillLayerTest.kt
extension-style/src/test/java/com/mapbox/maps/extension/style/layers/generated/LineLayerTest.kt

SInce native has removed transition properties. syncing codegen for that.

[MAPSAND-710] deprecate layer transition apis.

---

CHANGELOG.md
plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactory.kt
plugin-animation/src/main/java/com/mapbox/maps/plugin/animation/CameraTransform.kt
plugin-animation/src/test/java/com/mapbox/maps/plugin/animation/CameraAnimatorsFactoryTest.kt

* wrap longitude to world bounds for flyTo
* update changelog
* update tests and address review comments

[port] wrap longitude to world bound for flyTo animation. (#1949)

---

CHANGELOG.md
plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GestureState.kt
plugin-gestures/src/main/java/com/mapbox/maps/plugin/gestures/GesturesPluginImpl.kt
plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GestureOptionsTest.kt
plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GestureStateTest.kt
plugin-gestures/src/test/java/com/mapbox/maps/plugin/gestures/GesturesPluginTest.kt

`GestureState` class added to save and restore state of gesture handlers during map operations, where gestures are temporarily disabled and later restored when the map operation (e.g. pan, shove, double-tap) complete.
Original gesture settings should be maintained after map operations (such as panning the map) complete.

MAPSAND-709 Remember GesturesManager state during gesture handling

---

CHANGELOG.md
buildSrc/src/main/kotlin/Project.kt

* bump common to v23.3.0
* update gl-native snapshot
* update gl-native and common
* update changelog
* test gl-native snapshot
* update gl-native to latest v10.11.1

port gl-native and common bump
